### ISSUE TITLE
希望增加对obsidian笔记的支持

### ISSUE THREAD

**Issue by Yang11291999** [webclipper/web-clipper#1020]
希望增加对obsidian笔记的支持

**Comment by hzz888** [comment]
附议，希望开发者考虑一下obsidian剪藏支持

**Comment by vivi9527** [comment]
得益于Obisian的本地优化储存原则，你可以用插件把网页转成MD 文件，然后下载保存在Obisian的本地库文件夹里，挺方便的

**Comment by Mlk1225** [comment]
我目前的解决方法是先用这个插件将网页剪切到**joplin**中，再将**joplin**中的文件夹拉到**Obsidian**的库中，这样可以解决一部分需求，但是会产生多个存放附件的文件夹

**Comment by DiamondYuan** [comment]
try 1.38.0
