### ISSUE TITLE
希望增加链接在开头还是结尾的选项

### ISSUE THREAD

**Issue by seyeeL** [webclipper/web-clipper#1026]
链接更想在开头，并且可以留下剪藏时间，比如思源的剪藏
![image](https://user-images.githubusercontent.com/71479570/155840948-83ad903c-96ad-4c5a-acd5-9aea771386ce.png)

**Comment by hardheadedmooseknuckle** [comment]
This is the above chinese translated to english    Want to add options for linking at the beginning or end #1026
 Open
seyeeL opened this issue Feb 26, 2022 0 comments
Comments
@seyeeL
seyeeL commented Feb 26, 2022
The link is more like at the beginning, and can leave clipping time, such as Siyuan's clipping
image
