### ISSUE TITLE
希望增加对思源笔记的支持

### ISSUE THREAD

**Issue by xueyuntao** [webclipper/web-clipper#1032]
**您的功能要求与问题有关吗？ 请描述。**

清楚，简洁地说明问题所在。 例如 当[...]时，我总是感到沮丧

**描述您想要的解决方案**

对您想要发生的事情的简洁明了的描述。

**描述您考虑过的替代方案**

对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**

在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by DiamondYuan** [comment]
已经支持
