### ISSUE TITLE
语雀授权报401错误

### ISSUE THREAD

**Issue by yezige** [webclipper/web-clipper#1073]
**Bug 描述**

语雀授权报401错误

**截图**

![微信截图_20220607095831](https://user-images.githubusercontent.com/11436166/172279369-295a3a80-1f50-4461-baad-4381436a5ad3.png)

**请填写以下信息**

- 笔记平台: yuque
- 浏览器 chrome
- 版本 102.0.5005.63（正式版本） （64 位）

**Comment by ZengXianTong001** [comment]
我也出现这个问题！

**Comment by junjie97** [comment]
+1
