### ISSUE TITLE
无法绑定notion账号了

### ISSUE THREAD

**Issue by suka233** [webclipper/web-clipper#1077]
**Bug 描述**

无法绑定notion账户

**复现步骤**

重现的步骤：

1. 打开 '插件'
2. 点击按钮 '绑定账户'
3. 看到错误

**预期行为**

能够正常绑定notion账户

**截图**

![Snipaste_2022-06-16_12-02-16](https://user-images.githubusercontent.com/43712875/173988753-5cce8879-e43c-42e0-84a2-8bf360dbba76.png)

**请填写以下信息**

- 笔记平台: [notion]
- 浏览器 [chrome]
- 版本 [ 102.0.5005.115（正式版本） （64 位）]

**其他背景**

同时登录了两个notion账户

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases/tag/v1.31.0-alpha.16

试试看这个版本
