### ISSUE TITLE
功能请求：希望添加Flowus支持

### ISSUE THREAD

**Issue by whimian** [webclipper/web-clipper#1082]
**您的功能要求与问题有关吗？ 请描述。**

web-clipper 已经支持了notion和wolai

**描述您想要的解决方案**

希望添加对Flowus的支持

**描述您考虑过的替代方案**

对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**

在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by whimian** [comment]
#1059

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/issues/1095

**Comment by DiamondYuan** [comment]
重复了，先关掉。
