### ISSUE TITLE
不更新了？好可惜

### ISSUE THREAD

**Issue by LawrenceLiuQuanzhou** [webclipper/web-clipper#1083]
虽然目前的功能已经几近完美，完全符合我的要求，但是这插件一年多更新还是让人遗憾。
毕竟智能提取还不够智能，很多时候标题会错误提取成加粗。
希望作者归来。

**Comment by Leo-Ni88** [comment]
现在已经不兼容notion了。

**Comment by DiamondYuan** [comment]
修复中～

**Comment by LawrenceLiuQuanzhou** [comment]
> 

爷关更，喜大普奔啊。

**Comment by LawrenceLiuQuanzhou** [comment]
> 回来了。 可以试试看新版本

很高兴你回来了。

作为一个Web Clipper刚上线就在用的老用户，给一个小小的发展方向的建议：

目前Web Clipper最大的问题（自认为），是不够智能的自动选择，很多页面自动选取后，轻则换行、加粗、标题等出错，重则图片消失、出现乱码字符。

然而想凭借作者的一己之力，想适配茫茫多的网页，**是不可能的事情**。

所以，作者可以参考 [简悦](https://github.com/Kenshin/simpread) 的做法：

以Markdown为中间层，使用模板，将网站的内容同模板相适配，然后WebClipper将网站内容通过模板转换成Markdown格式并导入。

至于模板，直接在GitHub整个库，让广大网友来开发模板，WebClipper读取这个库来直接导入。

为了方便没有代理的网友使用，还可以更进一步设置CDN加速。

这样就能直接适配从语雀、Evernote、Notion在内的一大票需求。

而且还能形成与简悦不同的竞争力：

——简悦的流程是：访问对应网站，通过简悦阅读，使用简悦导入不同的地方。

但是简悦的功能，通过拓展以及简悦同步助手，已经是达到一个堪称繁杂的程度，就连我这种（自诩为）非小白用户的用户，很多时候都一头雾水。

WebClipper不妨在简洁、易用上达到另一种极致，即如下工作流程：

用户直接在网页上浏览，觉得文章合适就通过WebClipper保存。

这样，当用户后续要回顾时，就可以直接前往对应的内容库（如语雀、Notion）搜索并阅读。

而且，与简悦那种本地高于一切、并且试图包办你所有的网页阅读优化体验的理念不同，WebClipper不妨采取另一策略，即：

WebClipper本身不试图保存任何内容，也不试图“做”什么，WebClipper就只是帮助用户，把网页上纷杂的浏览格式，统一为一种统一的格式——Markdown，并保存到本地。

在这一流程中，其实还有一个困难，那就是关于图片的处理，我觉得不妨采用三种策略：
1. 保持原图，以链接形式写入Markdown；
2. 下载原图，以文件形式保存到本地；
3. 上传到指定图床，以链接形式写入Markdown。

1 和 2 自不必说，WebClipper很容易就能实现这两个功能。

我们的重心在3，也就是将图片上传到指定图床。

在使用的过程中，我发现，WebClipper虽然支持，但容易出错。

我觉得：**既然WebClipper干这活容易出错，干脆就不要干了，把这活丢给PicGo，反正PicGo能够通过一个本地端口给它发图片让它上传。**

所以，最后的WebClipper，应该会成为这样一个插件，并在自己的道路上不断前进：
1. 用户编辑特定网页的模板，该模板描述了如何将该网页中的某个元素直接指定成Markdown的某个元素；
2. WebClipper负责将网页中的内容与模板中的一一对应，并“翻译”成Markdown，保存到对应平台；
3. 此过程中，对图片的处理可以通过设置来交给用户，让用户来选择是保存原链接、保存原图、上传图床；
4. 至于格式是否美观，用户完全可以根据自己阅读保存下的内容的终端不同，在对应的程序中配置、美化。

我觉得，能够将这一工作流程做到极致，WebClipper将大有可为。

欢迎回来，请继续加油。🎉🎉🎉
