### ISSUE TITLE
Cannot read properties of undefined 

### ISSUE THREAD

**Issue by Leo-Ni88** [webclipper/web-clipper#1088]
### Discussed in https://github.com/webclipper/web-clipper/discussions/1039

<div type='discussions-op-text'>

<sup>Originally posted by **Amppa** March 23, 2022</sup>
Hi guys,
I can't connect with Notion.so. 
Chrome addon keeps showing:
`Cannot read properties of undefined (reading 'ceebd4fc...`

And firefox addon showing:
`M is undefined`

What should I do next?

</div>

**Comment by yahkun** [comment]
Notion changed their API recently, and the maintainer hasn't updated this project for a long time, and has probably abandoned it. It's too bad.

**Comment by Leo-Ni88** [comment]
> Notion changed their API recently, and the maintainer hasn't updated this project for a long time, and has probably abandoned it. It's too bad.

我现在用简悦，这个插件比较活跃，对notion也支持，感觉还不错，你可以试试。

**Comment by DiamondYuan** [comment]
试试看这个版本

https://github.com/webclipper/web-clipper/releases/tag/v1.31.0-alpha.16
