### ISSUE TITLE
notion已经无法剪藏

### ISSUE THREAD

**Issue by mysouly** [webclipper/web-clipper#1091]
**Bug 描述**

notion剪藏失效

**预期行为**
恢复正常

**截图**
剪藏后，显示成功
<img width="363" alt="image" src="https://user-images.githubusercontent.com/100445748/180605794-4791bd0c-51e8-479b-adc2-35b64600bc69.png">
但是notion中查看却是空白
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/100445748/180605848-788bcaac-a3a8-4bc9-8377-2c047b4bc1f3.png">

**请填写以下信息**

- 笔记平台: notion
- 浏览器 Chrome
- 版本  103.0.5060.114（正式版本） (arm64)
**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by yahkun** [comment]
因为最近Notion API有改动

**Comment by cjwdoing** [comment]
针对这个问题，我已经提了能够修复的PR，如果有哪位小伙伴认识作者的话，可以帮忙告知一下，更新一下版本；

如果比较长的时间后作者都不回复的话，我也可以单独发一个能解决此问题的版本

**Comment by mysouly** [comment]
大神好厉害👍，作者大大好像好久没更新了

**Comment by jth445600** [comment]
@cjwdoing 大佬发出来吧,现在这个作者已经停止

**Comment by yanyiyi** [comment]
期待 @cjwdoing  發出！

**Comment by jth445600** [comment]
用上边的cjwdoing大佬的仓库编译的,https://github.com/jth445600/hello-world/raw/master/web_clipper_chrome.zip

**Comment by mysouly** [comment]
> 用上边的cjwdoing大佬的仓库编译的，[https://github/jth445600/hello-world/raw/master/web_clipper_chrome.zip](https://github.com/jth445600/hello-world/raw/master/web_clipper_chrome.zip)

大佬大佬，牛皮plus！
大部分功能都回来了，
但有个小bug，英文翻译成中文的文章，选中保存的时候，会出现很多文中没有的乱码。
比如这样：
![Uploading image.png…]()

**Comment by jth445600** [comment]
@mysouly 我想问你点问题，加我电报吧https://t.me/yunbaitech

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases/tag/v1.31.0-alpha.16

试试看最新版本

**Comment by oceanyyy** [comment]
> > 用上边的cjwdoing大佬的仓库编译的,https://github.com/jth445600/hello-world/raw/master/web_clipper_chrome.zip
> 
> 感谢大佬！可以了！

大佬！可以再修复下吗，又不行了，还是上次的问题，应该是notion API又改动了😭  球球了😭

**Comment by oceanyyy** [comment]
> 针对这个问题，我已经提了能够修复的PR，并且有和作者沟通，建议方便的时候更新一下版本；
> 
> 如果比较长的时间后作者都不回复的话，我也可以单独发一个能解决此问题的版本

大佬！可以再修复下吗，又不行了，还是上次的问题，应该是notion API又改动了😭 球球了😭

**Comment by oceanyyy** [comment]
大佬，上次的这个问题又出现了，notion貌似又改了API，希望大佬可以再帮忙修复一下，可以有偿，太感谢了🙏
