### ISSUE TITLE
增加 flowus 的支持

### ISSUE THREAD

**Issue by king-zhangbn** [webclipper/web-clipper#1095]
**您的功能要求与问题有关吗？ 请描述。**

增加Flouws的支持

**描述您想要的解决方案**

加入Flowus的知识库

**描述您考虑过的替代方案**

notion导出，flowus导入缺少图片

**其他内容**

flowus加载速度快，秒杀弄notion

**Comment by jth445600** [comment]
作者估计停止更新了

**Comment by DiamondYuan** [comment]
和 flouws 对接中

**Comment by DiamondYuan** [comment]
最新的 1.31.0 已经支持
