### ISSUE TITLE
chrome上校验notion失败 

### ISSUE THREAD

**Issue by LuoTianHua** [webclipper/web-clipper#1102]
提示 Cannot read properties of undefined (reading '869ac609-adbd-4547-82f5-fd7d3f3e5535')

- 浏览器 chrome  104.0.5112.79（正式版本） （64 位）

但是在edge上可以

**Comment by DiamondYuan** [comment]
你下载 1.32.0 版本试试看，最近又修复了一点问题。

商店版本在审核。
