### ISSUE TITLE
增加保存到本地，类似的功能SingleFile。

### ISSUE THREAD

**Issue by renxingblack** [webclipper/web-clipper#1104]
有些文章，需要保存到硬盘上。
如果是先保存到其它平台，在导出到本地，步骤麻烦，而且排版、多媒体文件，不一定能完全导出，所以希望能有一个直接导出到本地的选项，类似这个插件的功能：https://github.com/gildas-lormeau/SingleFile  。
文件格式无所谓（MD、PDF、HTML、doc随便什么格式都可以），也不是要做到上面提到的这个插件这么完美的保留任何内容和排版（当然能肯定是最好的）。

**Comment by DiamondYuan** [comment]
> 有些文章，需要保存到硬盘上。 如果是先保存到其它平台，在导出到本地，步骤麻烦，而且排版、多媒体文件，不一定能完全导出，所以希望能有一个直接导出到本地的选项，类似这个插件的功能：https://github.com/gildas-lormeau/SingleFile 。 文件格式无所谓（MD、PDF、HTML、doc随便什么格式都可以），也不是要做到上面提到的这个插件这么完美的保留任何内容和排版（当然能肯定是最好的）。


你可以试试看 joplin， 思源笔记。

**Comment by CaryTrivett** [comment]
可以试试看我开发的 https://hamsterbase.com

1. 数据都在本地
2. 可以完美的保存几乎所有的网站
3. 免费、无广告
