### ISSUE TITLE
Include metadata about original source page

### ISSUE THREAD

**Issue by aisbergde** [webclipper/web-clipper#1121]
**Is your feature request related to a problem? Please describe.**

I also need the information about the original page where the web clipper was used.

**Describe the solution you'd like**

If the content of the page or part of the page is stored as markdown in a GitHub repository (and presumably for various other sources as well), then the information about the source page should also be stored.

If the target is Markdown, that could be a YAML attribute. Or at least a comment. Or whatever. Gladly also at the end as: "Original: http://aaa.bbb.ddd"

**Describe alternatives you've considered**

I have to edit the files afterwards and add the information manually.

**Comment by DiamondYuan** [comment]
<img width="545" alt="CleanShot 2022-09-27 at 11 37 57@2x" src="https://user-images.githubusercontent.com/9692408/192426235-ff257019-15e1-416a-a1fb-3165b02d4e21.png">
<img width="687" alt="CleanShot 2022-09-27 at 11 38 26@2x" src="https://user-images.githubusercontent.com/9692408/192426273-4ae54770-ca5d-4d55-ac20-1cc9fb12850e.png">

**Comment by aisbergde** [comment]
This does not work if you want to save the **whole page**. The template does not come into play.

Here's what I'm doing:

My goal is to save the content of entire web pages on GitHub in my repository. It doesn't matter if I select "Full Page" or "Readability": There is no data about the URL in the saved Markdown content.

Also, the option "Add link at the end of the document" is set.

It only works if I select a section of the page and select the web clipper there via the context menu ("Save Selection").

Then it actually says:
`Save From : [Include metadata about original source page - Issue #1121 - webclipper/web-clipper](https://github.com/webclipper/web-clipper/issues/1121) `

But since I call the Web Clipper for the whole page using the button in the upper right corner, then only the content of the page is saved without specifying the source.

![image](https://user-images.githubusercontent.com/9020187/192583161-268a7f1a-9ce1-412c-bcbd-50c8e7ca9d34.png)
