### ISSUE TITLE
ERROR: Got 400 error attempting to POST to submitTransaction, with data

### ISSUE THREAD

**Issue by h4rk8s** [webclipper/web-clipper#1159]
**Bug 描述**

[无法保存至notion，解决方案已提交](https://github.com/webclipper/web-clipper/pull/1158/files)

**复现步骤**

重现的步骤：

1. 打开 '任意网页'
2. 点击按钮 '剪藏'
3. 滚动到 '....'
4. 看到错误

**预期行为**

保存成功

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: [e.g. notion,yuque]
- 浏览器 [e.g. chrome, safari]
- 版本 [e.g. 1.23.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by RickVincent** [comment]
thanks for quick prompt for the solution. But how can I merge your patch into my Chrome plugin? Sound this service.js file is just running in backend, but not for plugin?

**Comment by ghjdegithub** [comment]
I downloaded your code and build it, but I reported the same error

**Comment by oceanyyy** [comment]
大佬您好，可以加个联系方式吗，不知道如何用您的补丁修复这个问题。
希望您能得倒您的回复，可以有偿。谢谢🙏

**Comment by h4rk8s** [comment]
> 

src/common/backend/services/notion/service.ts

https://github.com/webclipper/web-clipper/pull/1158/files#diff-6a352c6d74a5ae2fe62f26d37ac1978c9daddb76f0f7ded99379b6f1ddb9ccd1

**Comment by h4rk8s** [comment]
> I downloaded your code and build it, but I reported the same error

src/common/backend/services/notion/service.ts

https://github.com/webclipper/web-clipper/pull/1158/files#diff-6a352c6d74a5ae2fe62f26d37ac1978c9daddb76f0f7ded99379b6f1ddb9ccd1

**Comment by h4rk8s** [comment]
> 大佬您好，可以加个联系方式吗，不知道如何用您的补丁修复这个问题。 希望您能得倒您的回复，可以有偿。谢谢🙏

替换这个文件 : src/common/backend/services/notion/service.ts

参考这里：
https://github.com/webclipper/web-clipper/pull/1158/files#diff-6a352c6d74a5ae2fe62f26d37ac1978c9daddb76f0f7ded99379b6f1ddb9ccd1

**Comment by zifeiyu1999** [comment]
你好，大佬，替换后依旧会报400错误，我发现当剪藏至notion的页面(即在notion的保存位置，不是保存的内容）为数据库模式则会报错，若只是普通页面则能成功保存，不知如何解决

**Comment by h4rk8s** [comment]
> 你好，大佬，替换后依旧会报400错误，我发现当剪藏至notion的页面(即在notion的保存位置，不是保存的内容）为数据库模式则会报错，若只是普通页面则能成功保存，，这一问题在之前并不存在，是最近才出现的，不知如何解决

你Debug一下，对应方法加一个spaceId就行，新的Notion API有这个参数要求。

**Comment by zifeiyu1999** [comment]
啊这，不会啊，继续难受

**Comment by Arwenleo** [comment]
我看到简悦的开发者也提到了这个问题，说是最近notion的API改了，暂时只能先剪藏到page里再移动到database

**Comment by DiamondYuan** [comment]
1.33.0 版本已经修复，可以在商店下载试试看。
The bug has been fixed in version 1.33.0, you can try it in the store.

**Comment by oceanyyy** [comment]
终于等到作者大佬！太棒啦 太感谢🙏了。  
顺便提个小小的意见哈，
1、每次保存文章到notion，文章名后面都会自带网站名，比如下面这个👇
<img width="825" alt="image" src="https://user-images.githubusercontent.com/100446500/207814224-ac27472f-64e5-4713-b1e3-d96680717528.png">
大佬是否可以考虑出个可以开关，关闭自动带网站名的这个选项呢。

2、为了重度用户的长期稳定使用，大佬是否考虑付费呢，我也很乐意为其付费。谢谢，辛苦了🙏

**Comment by DiamondYuan** [comment]
> 终于等到作者大佬！太棒啦 太感谢🙏了。 顺便提个小小的意见哈， 1、每次保存文章到notion，文章名后面都会自带网站名，比如下面这个👇 <img alt="image" width="825" src="https://user-images.githubusercontent.com/100446500/207814224-ac27472f-64e5-4713-b1e3-d96680717528.png"> 大佬是否可以考虑出个可以开关，关闭自动带网站名的这个选项呢。
> 
> 2、为了重度用户的长期稳定使用，大佬是否考虑付费呢，我也很乐意为其付费。谢谢，辛苦了🙏

1. 网址发一下？我看看
2. 这个项目不准备商业化了。

**Comment by oceanyyy** [comment]
大部份(目测90%)网址的文章，剪藏到notion的时候，文章标题 都会自带网站名后缀。
比如随便点开的下面这一篇
https://wallstreetcn.com/articles/3677580
<img width="368" alt="image" src="https://user-images.githubusercontent.com/100446500/207848926-8806972b-a57e-4c98-b613-8a24d9883d34.png">

由于剪藏后文中会自带文章来源，这个标题后缀显得有点多余，只能手动删除，如果剪藏比较多和频繁，每次都去手动删除就有些麻烦了
谢谢大佬的回复🙏

**Comment by DiamondYuan** [comment]
<img width="388" alt="CleanShot 2022-12-15 at 22 12 46@2x" src="https://user-images.githubusercontent.com/9692408/207882957-d99839e1-aa12-468a-90af-63417c77d19e.png">

**Comment by DiamondYuan** [comment]
这个是他们自己加的，没办法

**Comment by oceanyyy** [comment]
原来是这样，谢谢大佬的耐心回复🙏
