### ISSUE TITLE
Connecting to Notion and getting status code 400

### ISSUE THREAD

**Issue by Christinanine** [webclipper/web-clipper#1164]
Hello,

I am unable to use it with Notion which is the only thing I want to use it with. I added the 'binding' to my Notion account but when I try to use it, I got "Request failed with status code 400" over and over.  I guess it has a problem with Notion but from reading here in the reviews it sounds like it works for others using Notion.  

I am on Mac Chrome Version 108.0.5359.98 (Official Build) (x86_64)

Can I get some help on getting this to work? Thank you!

**Comment by h4rk8s** [comment]
file location：src/common/backend/services/notion/service.ts
like this replace it ：https://github.com/webclipper/web-clipper/pull/1158/files#diff-6a352c6d74a5ae2fe62f26d37ac1978c9daddb76f0f7ded99379b6f1ddb9ccd1

**Comment by DiamondYuan** [comment]
i fix it

**Comment by Christinanine** [comment]
Fantastic, it works now!
Thanks so much,
CN
