### ISSUE TITLE
能否支持 teracloud webdav （或如何解决添加 teracloud webdav 时出现的 http error）

### ISSUE THREAD

**Issue by nfway** [webclipper/web-clipper#1169]
**您的功能要求与问题有关吗？ 请描述。**

目前 Teracloud 应用很广，不知作者有否支持 TeraCloud 的计划

**描述您想要的解决方案**

TeraCloud 有 webdav 功能，添加时出现 http error

TeraCloud webdav 网址一般为 https://abc.teracloud.jp/dav/

**描述您考虑过的替代方案**

对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**

在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by IvanLi-CN** [comment]
我提交了一个 PR，或许能修复这个问题，如果有兴趣的话，可以测试一下 #1179。
