### ISSUE TITLE
is:issue is:open 校验notion时选择的知识库有问题

### ISSUE THREAD

**Issue by vinceL911** [webclipper/web-clipper#1186]
我的notion根目录下的page和web clipper可选择的知识库不一致，少了一部分页面。导致我无法剪藏至目标页面。

尝试过把页面加入收藏，知识库无变化。
也尝试过移除webcliper并重装，知识库也无变化。
能显示的知识库都是第一次绑定notion时生成的，后面增加了几个page，知识库里却一直没有变化。

**Comment by DiamondYuan** [comment]
新版本更新了，可以试试看。
