### ISSUE TITLE
api.clipper.website域名证书到期导致扩展无法点击的问题

### ISSUE THREAD

**Issue by flewsea** [webclipper/web-clipper#1207]
**Bug 描述**

因为api.clipper.website的域名证书到期，导致扩展访问https://api.clipper.website/api/user 时报错，无法继续后续的弹出事件

**复现步骤**

重现的步骤：

1. 点击地址栏右侧的扩展图标

**预期行为**

应弹出对应的面板

**截图**
无

**请填写以下信息**

- 笔记平台: [任意]
- 浏览器 [chrome]
- 版本 [ 112.0.5615.138]

**其他背景**

**Comment by cowcfj** [comment]
同樣問題

**Comment by DiamondYuan** [comment]
im so sorry. 证书已更新
