### ISSUE TITLE
剪切功能用不了http error

### ISSUE THREAD

**Issue by coderbright13** [webclipper/web-clipper#1209]
**Bug 描述**

<img width="1144" alt="image" src="https://github.com/webclipper/web-clipper/assets/35894046/4d2a1c2f-1c4e-4654-ac6b-14546d67ca56">
剪切功能是不是已经用不了了啊，所以的剪切操作都会报http

**Comment by DiamondYuan** [comment]
保存到哪里？

**Comment by GGjin** [comment]
我也这样，有解决办法吗

**Comment by DiamondYuan** [comment]
> 我也这样，有解决办法吗

能详细描述一下吗？ 用的是哪个平台

**Comment by gevikhn** [comment]
> 
保存到坚果云时出现http error，查看控制台出现400错误

**Comment by oudemen** [comment]
可能是标题问题。我往坚果云剪藏的时候，提示 ”Invalid response: 400“， `后来看响应，是坚果云返回的错误：
`<?xml`` version="1.0" encoding="UTF-8" standalone="no"?><d:error xmlns:d="DAV:" xmlns:s="http://ns.jianguoyun.com"><s:exception>IllegalArgument</s:exception><s:message>the nustore path is not valid /安装Composer报错error:14090086:SSL routines:ssl3_get_server_certificate解决方法-PHP基础-自如初个人博客.md</s:message></d:error>`
 因为剪藏时使用文章标题当作文件名，但这种文件名 有时会存在不合法的字符，所以报错，修改保存的文件名后，即可保存成功。我感觉其他云平台可能也有类似的限制。

**Comment by AILogbook** [comment]
我也遇到类似雷锋提，提示Invalid response: 400，把标题中的特殊字符去掉就正常了。

**Comment by sereno37** [comment]
之前遇到一次，应该跟标题没关系，但不知道怎么就解决了；这次又遇到了，随便剪藏一个直接显示http error

**Comment by sereno37** [comment]
> 之前遇到一次，应该跟标题没关系，但不知道怎么就解决了；这次又遇到了，随便剪藏一个直接显示http error

火狐浏览器，放弃之后用Chrome可以正常使用
