### ISSUE TITLE
用web clipper将图片下载到思源笔记本地图床的问题

### ISSUE THREAD

**Issue by freezingbz** [webclipper/web-clipper#1210]
之前用firefox的web clipper扩展剪藏页面到思源笔记时，在提取所需内容后（通常用智能提取），可以通过这个按钮（如下图）将图片直接下载到思源笔记的assets的本地图床。
![图片](https://github.com/webclipper/web-clipper/assets/6426284/e3af74e0-7ee0-47f5-965e-25d899ec6665)

然而最近发现这样操作后图片都不能显示了，点开图片链接看到前面都被加了选中的那部分。当我手动删除该部分后图片能正常显示，但该操作当图片多时比较麻烦。
![图片](https://github.com/webclipper/web-clipper/assets/6426284/b083d4a2-8217-4f83-82ae-497baebaaa2b)

在这里提问前也去问了一下思源那边，说原因可能是在web clipper上。所以在这里也提个issue，麻烦问下能否fix？谢谢~

**Comment by yongnianliu** [comment]
我发现一样的问题，求解决

**Comment by kubulo** [comment]
你们用思源来剪藏？我一般是用FlowUs来剪藏在线的，用Joplin来剪藏离线的。Joplin有专用的浏览器插件，比用web clipper的好用点，缺点在于需要后台运行Joplin。

**Comment by DiamondYuan** [comment]
已修复
