### ISSUE TITLE
onenote无法授权登录

### ISSUE THREAD

**Issue by bluebluff** [webclipper/web-clipper#1236]
使用的国内学校账号，失败，两个授权token都没有获得。使用的edge浏览器

**Comment by DiamondYuan** [comment]
不好意思，不支持 edu 的。

**Comment by DiamondYuan** [comment]
如果您是开发者，欢迎贡献到开源的后端 https://github.com/webclipper/webclipper-backend

**Comment by zgzzx10** [comment]
> 不好意思，不支持 edu 的。

为啥我不是edu的账户，也是两个授权token都没有获得？

**Comment by DiamondYuan** [comment]
已修复
