### ISSUE TITLE
一键剪藏快捷键

### ISSUE THREAD

**Issue by yzhengwei** [webclipper/web-clipper#1244]
剪藏网页时，需要鼠标点击智能提取，再点击保存内容，能否提供快捷键，可以一键智能提取并保存？

**Comment by yqs112358** [comment]
<img width="601" alt="image" src="https://github.com/webclipper/web-clipper/assets/37969157/37da2042-86be-4c74-990a-7fc654512d29">
进设置点这里，把智能提取设置成默认扩展。以后再点剪裁按钮的时候会自动调用智能提取

**Comment by itxtl** [comment]
设置这个功能 之后跟 保存选择的内容 （Alt + S）冲突了，不知道是不是这个原因
