### ISSUE TITLE
无法剪藏文章到wolai

### ISSUE THREAD

**Issue by Archmays** [webclipper/web-clipper#1252]
**Bug 描述**
-2023.10.25早上，剪藏dedao.cn的文章到wolai时，“保存内容”按钮为灰色。
-尝试清空wolai和webclipper的cookie，并重新安装webclipper插件，这次无法绑定wolai账户，显示“http error”。

重现的步骤：
-剪藏错误
1. 打开任意一篇网络文章。
2. 点击webclipper剪藏图标
3. 点击“智能提取”后，“保存内容”按钮为灰色。
-绑定wolai账户错误
1.点击“绑定账户”。
2.下拉菜单选择“wolai”。
3.点击“校验”，显示“http error”。

**截图**
![QQ截图20231027074700](https://github.com/webclipper/web-clipper/assets/128825539/bc11991d-89d1-46bb-a85e-4e842a51412a)

- 笔记平台: wolai
- 浏览器 edge
- 版本 edge版本113.0.1774.35；web clipper版本1.35.0。

**Comment by bigdaronlee163** [comment]
我也复现了。 
![image](https://github.com/webclipper/web-clipper/assets/49524138/c120d542-e437-4973-896a-3bec7cb5f3b5)

**Comment by go1em** [comment]
复现+1，感觉是Wolai那边给封了？

**Comment by jackcsq** [comment]
复现+1

**Comment by jackcsq** [comment]
![微信截图_20231028093356](https://github.com/webclipper/web-clipper/assets/76186511/38575b0c-c39f-4c0b-8bca-f78045118fca)
/

**Comment by hadeser0123** [comment]
有可能是后台服务器被封了，插件好像有个中转的服务器

**Comment by zqbenyip** [comment]
看我来的帮助，好像API的网址变了

**Comment by DiamondYuan** [comment]
试试看这个 https://github.com/webclipper/web-clipper/issues/1256
