### ISSUE TITLE
我来wolai账户无法绑定，已经好多天，作者是不是不更新了，不解决了

### ISSUE THREAD

**Issue by hadeser0123** [webclipper/web-clipper#1253]
**Bug 描述**

我来账户绑定出现http error。无法绑定，已经好多天，作者是不是不更新了，不解决了。

**复现步骤**

重现的步骤：

1. 打开 '插件'
2. 找到'我来'
3. 点击按钮 '绑定按钮'
4. 看到错误提示

**预期行为**

预期可以绑定。

**截图**

![image](https://github.com/webclipper/web-clipper/assets/114035586/43d55e13-291c-46ee-9471-c83cf9f7bbac)

**请填写以下信息**

- 笔记平台: [我来]
- 浏览器 [edge]
- 版本 [118.0.2088.76]

**Comment by YangKunHuanZhen** [comment]
没戏了，我来也一直不做自己官方的剪藏，不想用我来了

**Comment by zqbenyip** [comment]
同问，我的wolai也突然绑定不了。是不是我来API的网址变了，openapi.wolai.com导致呢

**Comment by cyber-surf** [comment]
我问过wolai，我来说，webclipper没有适配我来的新的版本。我来自己要做类似的东西。但是我感觉估计跟flowus赞助webclipper有关。

**Comment by tisfeng** [comment]
可能是接口变了，参考 [wolai 开发者文档](https://www.wolai.com/wolai/7FB9PLeqZ1ni9FfD11WuUi) 

Base URL 是 https://openapi.wolai.com/v1 ，而不是 https://api.wolai.com/v1/authentication/user/getUserInfo

麻烦开发者跟进一下。

<img width="1712" alt="image" src="https://github.com/webclipper/web-clipper/assets/25194972/65393466-8f02-47c8-89f8-278e5eaabf0f">

**Comment by DiamondYuan** [comment]
试试看这个 https://github.com/webclipper/web-clipper/issues/1256

**Comment by tisfeng** [comment]
试了一下，Chrome 没问题，可以保存到 wolai 了。

辛苦了 👍  @DiamondYuan
