### ISSUE TITLE
wolai 的临时版本

### ISSUE THREAD

**Issue by DiamondYuan** [webclipper/web-clipper#1256]
晚点提交到商店。

**Comment by atalia** [comment]
新版本wolai知识库还是空
<img width="514" alt="image" src="https://github.com/webclipper/web-clipper/assets/15249755/ed749882-da7b-4224-aaa8-df6ad4db9953">

**Comment by YMingF** [comment]
不错，现在可以剪藏到wolai了

**Comment by atalia** [comment]
> 不错，现在可以剪藏到wolai了

请问下，wolai如何创建知识库？

**Comment by hadeser0123** [comment]
@DiamondYuan 啥时候上传到正式商店，我egde上还在等正式版

**Comment by DiamondYuan** [comment]
> @DiamondYuan 啥时候上传到正式商店，我egde上还在等正式版

edge 的提交审核了，chrome 的上架了。
