### ISSUE TITLE
DOM based eraser

### ISSUE THREAD

**Issue by silopolis** [webclipper/web-clipper#1260]
Long time ago, there was this fantastic FF extension that allowed to delete/suppress page elements based on the DOM.

When selecting the tool, display switched to a local snapshot of the page and the cursor turned into an air cross target. DOM elements were then highlighted on hovering in the same way as in FF web developer tools (IIRC), and clicking on the element deleted it.
Once done cleaning up the page and removing unwanted content, you were able to save the linted page in a local store.
This was fast and efficient, a pleasure to use.

Upgrading the content removal feature to such an UX would surely be a killer...

**Comment by DiamondYuan** [comment]
Hasn’t this feature already been supported? In Tool Extension, click the trash can.
