### ISSUE TITLE
火狐绑定思源显示http error

### ISSUE THREAD

**Issue by Jastmaskerrr** [webclipper/web-clipper#1275]
**Bug 描述**

使用chrome可以绑定思源，但火狐填完token后显示http error

**复现步骤**

重现的步骤：
重装了干净无其他插件的火狐，同样无法解决，拓展确定为最新版

**预期行为**

请求解决办法，看到其他issues中说，可能是api的问题，该如何解决

**截图**

![图片](https://github.com/webclipper/web-clipper/assets/138276427/b2fdbc84-097e-43fe-9a9a-3df89b43ad0d)

**请填写以下信息**

- 笔记平台: [siyuan]
- 浏览器 [firefox]
- 版本 [1.36.0]

**Comment by Zhe0301** [comment]
我也是同样的问题，思源笔记用不了

**Comment by MyEnergyFiled** [comment]
在思源中设置访问授权码
![image](https://github.com/webclipper/web-clipper/assets/26001520/ee0bef8c-4317-4c41-af2b-cafb8c31e349)

**Comment by DiamondYuan** [comment]
新版本更新了
