### ISSUE TITLE
申请开放第三方Extensions拓展的接入能力

### ISSUE THREAD

**Issue by jacob2826** [webclipper/web-clipper#1278]
**您的功能要求与问题有关吗？ 请描述。**

例如保存到github时，希望可以自动重命名文件名称。在文章开头/结尾增加更多文章元数据等。

**描述您想要的解决方案**

开放拓展插件的第三方接入能力，支持其他人贡献插件。

**Comment by DiamondYuan** [comment]
欢迎贡献，直接提交 PR 就想。
