### ISSUE TITLE
Firefox 安装报错： 安装文件损坏

### ISSUE THREAD

**Issue by xlighting2017** [webclipper/web-clipper#1285]
**Bug 描述**

使用Firefox安装 1.37.2 版本，会提示 安装包损坏

**复现步骤**

重现的步骤：

1. 下载 1.37.2 版本
2. 在 Firefox 中安装该 zip 文件
3. 看到错误

**预期行为**

正常更新

**截图**
报错截图如下
<img width="391" alt="image" src="https://github.com/webclipper/web-clipper/assets/25970065/fa08a144-0ab3-4ba5-bcae-639765a5a421">

**请填写以下信息**

- 笔记平台: notion
- 浏览器 firefox
- 版本：    129.0a1 nightly  和 115.12.0esr  都提示错误

**其他背景**
1.36.0 版本同样步骤安装成功

**Comment by DiamondYuan** [comment]
不好意思，最新版本使用 Manifest V3 完全重构了，暂时没有支持 firefox。

下个版本会把 firefox 的支持加回来。

**Comment by xlighting2017** [comment]
tested working with 1.37.4

Thanks!
