### ISSUE TITLE
不正确的思源笔记图片上传路径（SiYuan 'uploadImage' has incorrect URL: notebook id is not needed)

### ISSUE THREAD

**Issue by Fradeet** [webclipper/web-clipper#1289]
https://github.com/webclipper/web-clipper/blob/29072110e694403aec1b5d118bde7d9d85bdbaae/src/common/backend/clients/siyuan/client.ts#L68
当前的上传图片函数会将图片上传至"`{API 终结点}/{笔记本 ID}/assets/ `”文件夹内：
```url
# 返回文件存放路径
http://127.0.0.1:6806/20230920153236-6rzp0qi/assets/1721031238279-20240715161358-zyoutk3.png
```
~现在思源笔记不支持插入这些图片~，更推荐图片放在根目录的 `assets` 文件夹下，参考：[上传资源文件-SiYuan_API-zh-CN.md](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E4%B8%8A%E4%BC%A0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6)
所以现在正确的写法是：`{API 终结点}/assets/ ` 。
- 作为一个兼容选项，思源仍支持插入上传至笔记本文件夹中的图片，不过路径中不需要加笔记本 ID，URL 和 `{API 终结点}/assets/ `  保持一致。
```url
http://127.0.0.1:6806/assets/1721031238279-20240715161358-zyoutk3.png
```
<details>
<summary>图片引用方式（兼容性）</summary>

![image](https://github.com/user-attachments/assets/b6800762-90bf-4143-9b7f-145117f9d9bb)

![image](https://github.com/user-attachments/assets/2e2d4f65-8118-4482-8948-8be263569441)

</details>

关联旧 issue ：#1210

**Comment by DiamondYuan** [comment]
太感谢啦，我今天就上传发布。
