### ISSUE TITLE
绑定 Notion 失败

### ISSUE THREAD

**Issue by xlighting2017** [webclipper/web-clipper#1292]
**Bug 描述**

在 账户界面添加 Notion 绑定，不显示默认知识库

**复现步骤**

重现的步骤：

1. 打开 插件设置
2. 点击按钮 '绑定账户'
3. 选择 Notion 进行绑定；
4. 此时 无法选择 默认知识库 和 图床；
5. 直接点击 「校验」， 就会看到错误 如下图

<img width="536" alt="image" src="https://github.com/user-attachments/assets/ced907ca-d466-42b1-a672-5688fe89dfd0">

注： 浏览器已经打开了 Notion 并登录了对应的账号

**预期行为**

能添加绑定

**截图**

见上

**请填写以下信息**

- 笔记平台: notion
- 浏览器 Firefox
- 版本 1.37.4

**其他背景**

前几天还能正常使用，最近突然不行了， 现象是  点击剪藏按钮 就会提示  error， 
尝试删除原账户再添加，也会显示同样的 error

推测是 Notion 做了什么改动？

**Comment by DiamondYuan** [comment]
加 telegram 群，或者发微信号给我。 我们私聊排查一下。
