### ISSUE TITLE
[1.38.0 firefox]Plugin Installation Notice:After installing the plugin, if you want to use it on pages that were already open before installation, please refresh the page. 

### ISSUE THREAD

**Issue by haha9527upup** [webclipper/web-clipper#1293]
**Describe the bug**
重启浏览器多次、重新打开网页多次仍然提示
moz-extension://2dc6f714-1d9a-4f50-af36-8fbdf639f8df/chrome/error.html?message=ContentScript%20not%20ready%20yet.

After installing the plugin, if you want to use it on pages that were already open before installation, please refresh the page. 
![图片](https://github.com/user-attachments/assets/17dd96d2-1be2-4539-9ff6-64e49d045c94)

- Browser:firefox下出现bug,chrome使用正常
- Version [1.38.0]

**Comment by DiamondYuan** [comment]
无法复现你的问题。

1.  下载 web-clipper-firefox
2.  开启调试，加载 manifest.json

在我的 firefox 工作一切正常

**Comment by DiamondYuan** [comment]
麻烦补充一下信息，或者录屏看看。

**Comment by haha9527upup** [comment]
> 无法复现你的问题。
> 
>     1. 下载 web-clipper-firefox
> 
>     2. 开启调试，加载 manifest.json
> 
> 
> 在我的 firefox 工作一切正常

按这个方法操作后现在插件可以正常使用了，谢谢！
