### ISSUE TITLE
Please add BuildinAI to list (English version of FlowUs.cn)

### ISSUE THREAD

**Issue by shzk** [webclipper/web-clipper#1303]
Notion recently closed access for Russians to its service.
Our one of the alternatives - buildin.ai, when communicating with the developers, we found out that this is a separate branch in English from the flowus.cn project
The functionality is now slightly different and lags behind, but the team is releasing more and more new features and bringing these 2 applications closer together.
Most likely, the methods for working should be somewhat similar.
Please add support for buildin, users from Russia will be grateful!

**Comment by CatSema** [comment]
I support, it would be super to see the support buildin.ai!

**Comment by DiamondYuan** [comment]
@CatSema @shzk 

try https://github.com/webclipper/web-clipper/releases/tag/v1.39.0

**Comment by CatSema** [comment]
@DiamondYuan @liangxiwei 

In **FireFox** it is not possible to log in to Buildin, it issues "An unexpected error occurred" when trying to verify the account:
![image](https://github.com/user-attachments/assets/fcb44e71-3df4-4263-bbb8-dc45730c0735 )

There are problems with maintaining authorization in **Brave**. After successfully adding an account and going to the resource from where the material is copied, authorization is interrupted, although information about the account is displayed in the extension. Perhaps this is a feature of Brave, and not of the extension itself:
![image](https://github.com/user-attachments/assets/e9679ed2-6ce1-4ded-8cb5-6ab8e1b771ad )
![image](https://github.com/user-attachments/assets/9e97dc0c-f5f3-4a1f-8671-5c5bc63ed930 )

Authorization was successful in **Google Chrome**, but when adding material from the resource, a problem arises: the process freezes, and only a page with a title is created in the selected repository without the material itself:
![image](https://github.com/user-attachments/assets/d9565c8f-64b5-480c-88b7-e7951bd98e54 )
![image](https://github.com/user-attachments/assets/ad114880-a2a3-4545-969e-9af435dc6d6a )

**Comment by liangxiwei** [comment]
> @DiamondYuan @liangxiwei
> 
> In **FireFox** it is not possible to log in to Buildin, it issues "An unexpected error occurred" when trying to verify the account: ![image](https://private-user-images.githubusercontent.com/20588538/370899816-fcb44e71-3df4-4263-bbb8-dc45730c0735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA4OTk4MTYtZmNiNDRlNzEtM2RmNC00MjYzLWJiYjgtZGM0NTczMGMwNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YmMzZTBlMzdjOTI4ZTQwYjMyNGFmOWQ5OGFjYmMxM2NkMTQ0YjQyYzk2YjFhYTk4Yjc3ZDU1NTk1MTFkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4P4vr8jnDC-0Tgp8f_naiSKU5v38EKUP4xKO3rO-bac)
> 
> There are problems with maintaining authorization in **Brave**. After successfully adding an account and going to the resource from where the material is copied, authorization is interrupted, although information about the account is displayed in the extension. Perhaps this is a feature of Brave, and not of the extension itself: ![image](https://private-user-images.githubusercontent.com/20588538/370903661-e9679ed2-6ce1-4ded-8cb5-6ab8e1b771ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDM2NjEtZTk2NzllZDItNmNlMS00ZGVkLThjYjUtNmFiOGUxYjc3MWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTdjZDVlZWZmZTBlOTlkNzYyNDBmZTFlZDM5ZDZmODAwOTUzYmQwODMxMmIwMjc0YzNkNDdmMDNjNTAxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oPd4itNgWhCEgoewJbFh00KsBqf3GL_J4OnBI-oxkZQ) ![image](https://private-user-images.githubusercontent.com/20588538/370903683-9e97dc0c-f5f3-4a1f-8671-5c5bc63ed930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDM2ODMtOWU5N2RjMGMtZjVmMy00YTFmLTg2NzEtNWM1YmM2M2VkOTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MTA2NmNkZmRmZjIxYmEwMWM0MTlkYjlhYzFmYmFkZTBkNjQ2YTA1ZTA4MDcyYmM0ZGM4NmE0ODk5YWM1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tjBvOgJ8yHJ9drD1PsG9shgQrG2sPKGEu93wX92tbnY)
> 
> Authorization was successful in **Google Chrome**, but when adding material from the resource, a problem arises: the process freezes, and only a page with a title is created in the selected repository without the material itself: ![image](https://private-user-images.githubusercontent.com/20588538/370904706-d9565c8f-64b5-480c-88b7-e7951bd98e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDQ3MDYtZDk1NjVjOGYtNjRiNS00ODBjLTg4YjctZTc5NTFiZDk4ZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTY5YWQ2MzkzMzM5MTI1MGRhMGNmN2QyYjIzMGI2MjI1YWY1MDc1N2U4NTNiN2M3NTk1ODQ1OThjMzhjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.16JuSvUVS8MqDTCS9usqVPwsZvFsI7ivsFdpUVnCl5A) ![image](https://private-user-images.githubusercontent.com/20588538/370904854-ad114880-a2a3-4545-969e-9af435dc6d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDQ4NTQtYWQxMTQ4ODAtYTJhMy00NTQ1LTk2OWUtOWFmNDM1ZGM2ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Y2U2ZDMxMmM2YjgwNWY2YTk1MTJmMGM2Njc3NjE2YzhkNzJiZjBhYjQwMzZlOTg1Yzc2Y2RiZDE5OTVhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TNZbx_deZujfKfnlEb_KclTg73xwqge0e4zoZnWaesg)

login with buildin.ai website first before try this chrome plugin

**Comment by CatSema** [comment]
> > @DiamondYuan @liangxiwei
> > 
> > In **FireFox** it is not possible to log in to Buildin, it issues "An unexpected error occurred" when trying to verify the account: ![image](https://private-user-images.githubusercontent.com/20588538/370899816-fcb44e71-3df4-4263-bbb8-dc45730c0735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA4OTk4MTYtZmNiNDRlNzEtM2RmNC00MjYzLWJiYjgtZGM0NTczMGMwNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YmMzZTBlMzdjOTI4ZTQwYjMyNGFmOWQ5OGFjYmMxM2NkMTQ0YjQyYzk2YjFhYTk4Yjc3ZDU1NTk1MTFkNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4P4vr8jnDC-0Tgp8f_naiSKU5v38EKUP4xKO3rO-bac)
> > 
> > There are problems with maintaining authorization in **Brave**. After successfully adding an account and going to the resource from where the material is copied, authorization is interrupted, although information about the account is displayed in the extension. Perhaps this is a feature of Brave, and not of the extension itself: ![image](https://private-user-images.githubusercontent.com/20588538/370903661-e9679ed2-6ce1-4ded-8cb5-6ab8e1b771ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDM2NjEtZTk2NzllZDItNmNlMS00ZGVkLThjYjUtNmFiOGUxYjc3MWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZTdjZDVlZWZmZTBlOTlkNzYyNDBmZTFlZDM5ZDZmODAwOTUzYmQwODMxMmIwMjc0YzNkNDdmMDNjNTAxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oPd4itNgWhCEgoewJbFh00KsBqf3GL_J4OnBI-oxkZQ) ![image](https://private-user-images.githubusercontent.com/20588538/370903683-9e97dc0c-f5f3-4a1f-8671-5c5bc63ed930.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDM2ODMtOWU5N2RjMGMtZjVmMy00YTFmLTg2NzEtNWM1YmM2M2VkOTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MTA2NmNkZmRmZjIxYmEwMWM0MTlkYjlhYzFmYmFkZTBkNjQ2YTA1ZTA4MDcyYmM0ZGM4NmE0ODk5YWM1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tjBvOgJ8yHJ9drD1PsG9shgQrG2sPKGEu93wX92tbnY)
> > 
> > Authorization was successful in **Google Chrome**, but when adding material from the resource, a problem arises: the process freezes, and only a page with a title is created in the selected repository without the material itself: ![image](https://private-user-images.githubusercontent.com/20588538/370904706-d9565c8f-64b5-480c-88b7-e7951bd98e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDQ3MDYtZDk1NjVjOGYtNjRiNS00ODBjLTg4YjctZTc5NTFiZDk4ZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTY5YWQ2MzkzMzM5MTI1MGRhMGNmN2QyYjIzMGI2MjI1YWY1MDc1N2U4NTNiN2M3NTk1ODQ1OThjMzhjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.16JuSvUVS8MqDTCS9usqVPwsZvFsI7ivsFdpUVnCl5A) ![image](https://private-user-images.githubusercontent.com/20588538/370904854-ad114880-a2a3-4545-969e-9af435dc6d6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI3NzIsIm5iZiI6MTcyNzQwMjQ3MiwicGF0aCI6Ii8yMDU4ODUzOC8zNzA5MDQ4NTQtYWQxMTQ4ODAtYTJhMy00NTQ1LTk2OWUtOWFmNDM1ZGM2ZDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Y2U2ZDMxMmM2YjgwNWY2YTk1MTJmMGM2Njc3NjE2YzhkNzJiZjBhYjQwMzZlOTg1Yzc2Y2RiZDE5OTVhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TNZbx_deZujfKfnlEb_KclTg73xwqge0e4zoZnWaesg)
> 
> login with buildin.ai website first before try this chrome plugin

Did you read what I wrote? Or do you think that I'm trying to log in to the extension without logging in to the site itself buildin.ai? 🤣
