### ISSUE TITLE
希望剪藏的内容中包含有原文链接

### ISSUE THREAD

**Issue by someblue** [webclipper/web-clipper#136]
Evernote 用户转来语雀，感谢作者制作了这个方便的工具~
Evernote 剪藏会附带有原文链接，方便有需要时回到原文网站上查看，希望能支持类似功能，谢谢！

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/65972164-03207280-e49c-11e9-80c6-4d43586bbbe2.png)

安装最新版本的插件，然后在插件管理中安装这个扩展。
