### ISSUE TITLE
剪裁的文章的路径特别长，还是旧版本的

### ISSUE THREAD

**Issue by ZuulAndRibbon** [webclipper/web-clipper#14]
现在语雀新建文档的路径都是六位数字结尾，这个插件剪裁的路径还是旧版本的

**Comment by DiamondYuan** [comment]
路径是为了防止重复，所以用了uuid。
编辑器问题无解，年后等语雀官方更新。

路径在之后的版本支持修改，目前在完全重写，近期会重新完毕，然后再考虑新功能。

现在的版本已经可以剪藏到GitHub issue了，可以自己编译体验一下。

**Comment by DiamondYuan** [comment]
最新的 master 分支已经实现这个功能。
