### ISSUE TITLE
剪藏文章的时候，希望把图床转成语雀的

### ISSUE THREAD

**Issue by zihaojiang** [webclipper/web-clipper#171]
我收藏了很多文章，图都是引用原来的地址，过几天就会失效

**Comment by DiamondYuan** [comment]
> 我收藏了很多文章，图都是引用原来的地址，过几天就会失效

本来就支持的。
首先先设定一个语雀的图床
然后把账户绑定图创
剪藏时候可以点击工具栏的同步按钮 就可以把图片传到语雀了。
