### ISSUE TITLE
剪藏文章 同步语雀图床无效

### ISSUE THREAD

**Issue by zihaojiang** [webclipper/web-clipper#173]
![image](https://user-images.githubusercontent.com/36414297/61170705-d09f6180-a59f-11e9-8aad-43a15a580d25.png)
点击上传图床 迁移到语雀里面还是老的链接

![image](https://user-images.githubusercontent.com/36414297/61170710-f462a780-a59f-11e9-9ddb-99780bf35c68.png)

**Comment by zihaojiang** [comment]
我图床是设置了的
![image](https://user-images.githubusercontent.com/36414297/61170764-c5006a80-a5a0-11e9-8d86-2e14e7f61c8a.png)
![image](https://user-images.githubusercontent.com/36414297/61170768-cd58a580-a5a0-11e9-9c06-e8d6345ad499.png)

**Comment by DiamondYuan** [comment]
不好意思，暂时先用 sm.ms 把。语雀图床目前暂时不可用。

**Comment by zihaojiang** [comment]
知乎有些文章，图床只会上传一部分图片

**Comment by DiamondYuan** [comment]
> 知乎有些文章，图床只会上传一部分图片

能否提供一些图片链接

**Comment by zihaojiang** [comment]
https://pic4.zhimg.com/v2-789497b87d8a372dc4712c5220945433_b.jpg

**Comment by zihaojiang** [comment]
https://zhuanlan.zhihu.com/p/73797577

**Comment by zihaojiang** [comment]
https://zhuanlan.zhihu.com/p/73797577  文章地址，图片只转换了前一半 用的 sm.ms图床
