### ISSUE TITLE
智能提取segmentfault相关界面的时候图片路径有问题,导致加载不成功

### ISSUE THREAD

**Issue by DJ7Rap** [webclipper/web-clipper#175]
智能提取segmentfault相关界面的时候图片路径有问题,导致加载不成功
相关链接:https://segmentfault.com/a/119000001972900

**Comment by DiamondYuan** [comment]
> 智能提取segmentfault相关界面的时候图片路径有问题,导致加载不成功
> 相关链接:https://segmentfault.com/a/119000001972900

![image](https://user-images.githubusercontent.com/9692408/61551143-f5f00c00-aa86-11e9-83ce-12b6ba5b80f5.png)


原有页面404了
