### ISSUE TITLE
图库功能不生效

### ISSUE THREAD

**Issue by xzm2000** [webclipper/web-clipper#182]
图片点击上传图库但是点到语雀链接以后，里面的图片链接还是原来的链接

**Comment by DiamondYuan** [comment]
用 sm.ms 图床吧，语雀图床现在有点问题。

**Comment by xzm2000** [comment]
但是sm.ms要配置什么吗，添加了以后剪裁的时候根本不出现叫我选择放图床的按钮

**Comment by DiamondYuan** [comment]
> 但是sm.ms要配置什么吗，添加了以后剪裁的时候根本不出现叫我选择放图床的按钮

账户页面，点击编辑。可以切换图床。

**Comment by xzm2000** [comment]
设置了，但是当我智能剪裁以后，他并没有让我上传图片到图床那个按钮了

**Comment by qianjigit** [comment]
请问语雀的图床可以了吗？ 每次都是提示 `0 success,31 failed. ` 可以的话，希望增加自定义自建的图床

**Comment by xuzhibin** [comment]
请问语雀的图床可以了吗？ 每次都是提示 0 success,31 failed. 可以的话，希望增加自定义自建的图床

**Comment by DiamondYuan** [comment]
> 请问语雀的图床可以了吗？ 每次都是提示 0 success,31 failed. 可以的话，希望增加自定义自建的图床

可以了。目前可以试试看。
需要使用 语雀一键授权。


现在语雀导入时似乎自动插入到图床了。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/71545705-45891b00-29c9-11ea-9e30-f5e127bfde70.png)

**Comment by DiamondYuan** [comment]
晕，一不小心泄漏了自己的 token。大家以后注意。
