### ISSUE TITLE
支持微信剪藏图片

### ISSUE THREAD

**Issue by dennischancs** [webclipper/web-clipper#202]
在data-src图片的引用末尾，增加“&tp=jpg”，可以剪藏微信公众号文章的图片。

![content_script_modify](https://user-images.githubusercontent.com/48424802/63779666-8557cd00-c919-11e9-8583-93a2f3e9d3da.png)

效果如下：webp2jpg
![wechat_webp2jpg](https://user-images.githubusercontent.com/48424802/63780162-424a2980-c91a-11e9-95da-1904a1a41c50.png)

**Comment by DiamondYuan** [comment]
> 在data-src图片的引用末尾，增加“&tp=jpg”，可以剪藏微信公众号文章的图片。
> 
> ![content_script_modify](https://user-images.githubusercontent.com/48424802/63779666-8557cd00-c919-11e9-8583-93a2f3e9d3da.png)
> 
> 效果如下：webp2jpg
> ![wechat_webp2jpg](https://user-images.githubusercontent.com/48424802/63780162-424a2980-c91a-11e9-95da-1904a1a41c50.png)

用图床吧。存到自己服务器上。
