### ISSUE TITLE
求增加剪藏到coda的功能

### ISSUE THREAD

**Issue by origamidance** [webclipper/web-clipper#204]
这里是coda的api
[https://coda.io/developers/apis/v1beta1](https://coda.io/developers/apis/v1beta1)

**Comment by DiamondYuan** [comment]
thanks，会考虑的。

**Comment by DiamondYuan** [comment]
coda 的文档不支持创建文档，也不支持导入 markdown。
所以没办法支持 coda

**Comment by ImSingee** [comment]
我看是可以创建文档的… 

https://coda.io/developers/apis/v1beta1#operation/

Create a doc
POST /docs
