### ISSUE TITLE
代码块中的注释会被忽略

### ISSUE THREAD

**Issue by Wcdaren** [webclipper/web-clipper#205]

**Comment by DiamondYuan** [comment]
链接来一个，我适配一些。

**Comment by Wcdaren** [comment]
```html
<pre><code class="hljs js" lang="js"><span class="hljs-function"><span class="hljs-keyword">function</span> *<span class="hljs-title">foo</span>(<span class="hljs-params">x</span>) </span>{
  <span class="hljs-keyword">let</span> y = <span class="hljs-number">2</span> * (<span class="hljs-keyword">yield</span> (x + <span class="hljs-number">1</span>))
  <span class="hljs-keyword">let</span> z = <span class="hljs-keyword">yield</span> (y / <span class="hljs-number">3</span>)
  <span class="hljs-keyword">return</span> (x + y + z)
}
<span class="hljs-keyword">let</span> it = foo(<span class="hljs-number">5</span>)
<span class="hljs-built_in">console</span>.log(it.next())   <span class="hljs-comment">// =&gt; {value: 6, done: false}</span>
<span class="hljs-built_in">console</span>.log(it.next(<span class="hljs-number">12</span>)) <span class="hljs-comment">// =&gt; {value: 8, done: false}</span>
<span class="hljs-built_in">console</span>.log(it.next(<span class="hljs-number">13</span>)) <span class="hljs-comment">// =&gt; {value: 42, done: true}</span>
```

**Comment by DiamondYuan** [comment]
> ```
> <pre><code class="hljs js" lang="js"><span class="hljs-function"><span class="hljs-keyword">function</span> *<span class="hljs-title">foo</span>(<span class="hljs-params">x</span>) </span>{
>   <span class="hljs-keyword">let</span> y = <span class="hljs-number">2</span> * (<span class="hljs-keyword">yield</span> (x + <span class="hljs-number">1</span>))
>   <span class="hljs-keyword">let</span> z = <span class="hljs-keyword">yield</span> (y / <span class="hljs-number">3</span>)
>   <span class="hljs-keyword">return</span> (x + y + z)
> }
> <span class="hljs-keyword">let</span> it = foo(<span class="hljs-number">5</span>)
> <span class="hljs-built_in">console</span>.log(it.next())   <span class="hljs-comment">// =&gt; {value: 6, done: false}</span>
> <span class="hljs-built_in">console</span>.log(it.next(<span class="hljs-number">12</span>)) <span class="hljs-comment">// =&gt; {value: 8, done: false}</span>
> <span class="hljs-built_in">console</span>.log(it.next(<span class="hljs-number">13</span>)) <span class="hljs-comment">// =&gt; {value: 42, done: true}</span>
> ```

能给一个实际的网站吗？
手动选择和智能提取的逻辑不一样，代码还是推荐手动选择。

**Comment by Wcdaren** [comment]
[链接](https://juejin.im/book/5bdc715fe51d454e755f75ef/section/5bdc715f6fb9a049c15ea4e0)
你试试能不能登录
因为这个是付费的
我刚刚找了下 可以试读的章节

**Comment by Wcdaren** [comment]
(自动获取的不正确)[https://cnodejs.org/topic/545720506537f4d52c414d87]
这个可以也适配下吗

**Comment by DiamondYuan** [comment]
手动提取似乎是有注释的，智能提取主要为了新闻不准备改了。

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/extensions

可以在这个网站提交一下适配。
