### ISSUE TITLE
500错误和超时错误

### ISSUE THREAD

**Issue by Andrew-chh** [webclipper/web-clipper#223]
![image](https://user-images.githubusercontent.com/20946310/65311659-628ca180-dbc3-11e9-8464-ac6f06231d0a.png)
![image](https://user-images.githubusercontent.com/20946310/65311702-7cc67f80-dbc3-11e9-9fe1-f970a927a9d5.png)
您好，今天在使用web-clipper的时候出现了上图两个错误，网络是校园移动网络，挂不挂飞机都一样。 使用的是有道云笔记，测试网站是：https://blog.csdn.net/weixin_38465039/article/details/83246317。

**Comment by DiamondYuan** [comment]
网页版有道云登陆了吗？你用的哪个版本的插件？

**Comment by Andrew-chh** [comment]
有登录，有道云笔记插件使用正常。 有道云剪报插件版本2.1.2,webClipper插件版本1.9.2。 今天已经可以正常使用了。 不知道是不是校园网络的问题。
