### ISSUE TITLE
手动选取时提取的图片地址为相对路径

### ISSUE THREAD

**Issue by lx200916** [webclipper/web-clipper#224]
![image](https://user-images.githubusercontent.com/44310445/65397392-4e72bb00-dde2-11e9-90d3-2a586bd119b0.png)
手动选取时图片地址为相对路径导致无法显示.智能选取时部分代码块会被忽略.
相关网页地址:https://jalammar.github.io/visual-numpy/
希望修复或增强智能模式适配，感谢开发者大大😁

**Comment by DiamondYuan** [comment]
预计下个版本修复
