### ISSUE TITLE
保存到OneNote中时，与所选的笔记本不一致

### ISSUE THREAD

**Issue by yaohunzhanyue** [webclipper/web-clipper#229]
不管选那个笔记本，都会保存到快速笔记分区

**Comment by DiamondYuan** [comment]
的确是 bug，以及修复，但是需要和其他代码一起发布。

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/commit/50771e08e84998d5b5bc620a1ea08a1bdd809bc2
