### ISSUE TITLE
能否支持confluence接口

### ISSUE THREAD

**Issue by leeyaunlong** [webclipper/web-clipper#230]
能否支持confluence接口

**Comment by chendi20082009** [comment]
> 能否支持confluence接口

同样的需求

**Comment by DiamondYuan** [comment]
最新 master 已经支持。

**Comment by DiamondYuan** [comment]
[web-clipper_1.18.0_beta.zip](https://github.com/webclipper/web-clipper/files/4104380/web-clipper_1.18.0_beta.zip)

**Comment by chendi20082009** [comment]
感谢，已经看到了。
请问能否添加下使用说明?Origin验证是什么?
![image](https://user-images.githubusercontent.com/10103354/73012443-35e3d300-3dcb-11ea-94b9-688fbd232a5c.png)

**Comment by chendi20082009** [comment]
![image](https://user-images.githubusercontent.com/10103354/73013011-4f394f00-3dcc-11ea-998f-71675dc9fc21.png)
添加confluence API taken，无法验证
