### ISSUE TITLE
希望支持Office 365 for Business版的OneNote

### ISSUE THREAD

**Issue by yaotouwn** [webclipper/web-clipper#231]
OneNote登录只能登陆个人版的账号，无法登陆商业版

**Comment by XinArkh** [comment]
附议，用教育邮箱申请的帐号也属于商业版，不能用的话对学生来说还是很不方便的，希望作者尽早添加商业版onenote的支持😘

**Comment by DiamondYuan** [comment]
[web-clipper_1.16.0_beta.zip](https://github.com/webclipper/web-clipper/files/4019854/web-clipper_1.16.0_beta.zip)


@XinArkh  试试看这个。

**Comment by XinArkh** [comment]
> [web-clipper_1.16.0_beta.zip](https://github.com/webclipper/web-clipper/files/4019854/web-clipper_1.16.0_beta.zip)
> 
> @XinArkh 试试看这个。

似乎没有变化😵

**Comment by oldzhg** [comment]
+1，无法使用教育邮箱的onenote，提示账号不存在，最新1.19还没有支持
