### ISSUE TITLE
希望能增加为知笔记

### ISSUE THREAD

**Issue by ychgithub** [webclipper/web-clipper#232]
希望能增加为知笔记，http://www.wiz.cn/zh-cn

**Comment by DiamondYuan** [comment]
支持为知笔记私有部署版本

**Comment by sczhg** [comment]
为知笔记公开了[为知笔记API文档](https://www.wiz.cn/wapp/pages/book/bb8f0f10-48ca-11ea-b27a-ef51fb9d4bb4/700c0ba0-48cb-11ea-a61a-d3d58d67def9)，希望同时加入私有部署版本（只需要多一个URL选项）

**Comment by yggcwx** [comment]
恳请支持为知（wiz）私有部署版！谢谢！
