### ISSUE TITLE
能否支持将收藏保存到本地（后端自部署）

### ISSUE THREAD

**Issue by hineH** [webclipper/web-clipper#236]
出于私密性，可靠性，安全性的考虑，希望能够提供一种不使用任何在服务的方式进行收藏。

一个简单的思路是提供一个「后端」，直接在硬盘上保存所有静态资源，可以直接运行在本机localhost，或私人服务器（NAS）上。
然后将其作为「绑定账户」的一个选项供用户选择。

**Comment by DiamondYuan** [comment]
可以啊。实现起来很简单的。

**Comment by DiamondYuan** [comment]
如果你要开发，推荐用 golang 来开发。

**Comment by DiamondYuan** [comment]
> 出于私密性，可靠性，安全性的考虑，希望能够提供一种不使用任何在服务的方式进行收藏。
> 
> 一个简单的思路是提供一个「后端」，直接在硬盘上保存所有静态资源，可以直接运行在本机localhost，或私人服务器（NAS）上。
> 然后将其作为「绑定账户」的一个选项供用户选择。

bear 目前就是一个本地的软件，没有服务器，你可以试试看 bear。

**Comment by vagra** [comment]
保存到本地的需求越来越大了，比方说最近出了个 Obsidian ，也是直接在本地选个文件夹它就可以读取，markdown格式的文档。
