### ISSUE TITLE
可否支持 Notion 的 Gallery View ？

### ISSUE THREAD

**Issue by lcolok** [webclipper/web-clipper#237]
![image](https://user-images.githubusercontent.com/33664979/66391319-5f851400-e9ff-11e9-8279-5d8629fe0b35.png)

目前 Web-clipper 摘抄下来的笔记只能以列表形式来呈现，可否支持 Gallery View，达到以下效果？

![image](https://user-images.githubusercontent.com/33664979/66391391-8e02ef00-e9ff-11e9-92c9-1c967b076487.png)

**Comment by DiamondYuan** [comment]
不支持。目前的原理是导入一个 markdown。
