### ISSUE TITLE
剪藏到notion时能否自己选择目录？

### ISSUE THREAD

**Issue by vkboy** [webclipper/web-clipper#241]
现在剪藏到notion时只能保存在根目录，能否增加选择目录的功能？谢谢

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/67159401-c21ece00-f376-11e9-82bf-b060e7a3cf0f.png)


我试了一下是可以的，需要在首页下面新建普通的 Page
最多只支持一级目录。

**Comment by vkboy** [comment]
确实可以，谢谢

**Comment by lloyd-chi** [comment]
我的情况是无法显示完整的一级目录。
![image](https://user-images.githubusercontent.com/8214700/67577990-76cf3b80-f739-11e9-892d-4a273f63f77a.png)
![image](https://user-images.githubusercontent.com/8214700/67578064-9a928180-f739-11e9-92a0-e8fe8a6f2325.png)
只显示了一个 Personal Home，剩下的 Mobile Analytics 和 Weekly Agenda 来自另一个 Workspace，而不是我 Personal 这个 Space。Personal Workspace 下的 Notes & Draft 以及 My Links 则看不到。
