### ISSUE TITLE
手动选取不能改变选择范围

### ISSUE THREAD

**Issue by TTTPOB** [webclipper/web-clipper#245]
手动选取选择之后，除了刷新页面无法撤销已经做出的选择

**Comment by DiamondYuan** [comment]
安装选择插件，可以重新选择。

原来的内容自己删掉吧。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/67347837-d0870880-f575-11e9-9d0f-c923e540e8ee.png)

**Comment by DiamondYuan** [comment]
可以多次选择，把元素添加到末尾。

**Comment by TTTPOB** [comment]
了解，谢谢解答
