### ISSUE TITLE
"Save to Email" 在哪儿设置？

### ISSUE THREAD

**Issue by wenliang** [webclipper/web-clipper#248]
我通过 paypal 买了一个月 powerpack. 但是没有看到任何改变。

**Comment by DiamondYuan** [comment]
> 我通过 paypal 买了一个月 powerpack. 但是没有看到任何改变。

还没发布吧。......
绑定新账户哪里，不好意思。

**Comment by DiamondYuan** [comment]
不好意思，最新版本虽然开发完了，但是还没正式发布，需要自己构建。
我等一下回家的时候，构建好发布测试版到这个 issue 下面。

**Comment by DiamondYuan** [comment]
[web-clipper_1.11.0.zip](https://github.com/webclipper/web-clipper/files/3775520/web-clipper_1.11.0.zip)

先可以用这个版本

![image](https://user-images.githubusercontent.com/9692408/67629852-1286b600-f8b8-11e9-9561-00e1ae96164c.png)


![image](https://user-images.githubusercontent.com/9692408/67629855-1a465a80-f8b8-11e9-98ff-3e1c2e734720.png)


GitHub 的邮箱要和购买邮箱一样。

**Comment by DiamondYuan** [comment]
登陆后，过期时间可能不太正常，我会手动修复的。

**Comment by wenliang** [comment]
好的多谢。我明天来试试看

**Comment by DiamondYuan** [comment]
我先关闭了
