### ISSUE TITLE
希望能保留原文链接

### ISSUE THREAD

**Issue by lonenol** [webclipper/web-clipper#250]
我用的 notion，没有保存，其它平台没有测试

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/67667808-a2f0f380-f9a9-11e9-8cb0-881d422f1c5e.png)

插件商店安装插件。目前需要手动执行。

**Comment by XinArkh** [comment]
> ![image](https://user-images.githubusercontent.com/9692408/67667808-a2f0f380-f9a9-11e9-8cb0-881d422f1c5e.png)
> 
> 插件商店安装插件。目前需要手动执行。

这个链接插件直接在最后一行添加链接，跟前面的内容之间没有换行分隔，请问可以更新为在文章末尾先换行再插入链接吗
