### ISSUE TITLE
feat: 剪藏添加界面 增加服务平台的logo/tag标识

### ISSUE THREAD

**Issue by nickfan** [webclipper/web-clipper#252]
![image](https://user-images.githubusercontent.com/100613/67666900-b13e1000-f9a7-11e9-9ecb-ce851abc6cbf.png)

如果在添加了多个账户后，比较难辨识所属服务/平台。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/72353032-4dadbe00-371e-11ea-8157-eb38cc901cb5.png)


最新版增加了用户名和描述。
