### ISSUE TITLE
希望剪藏时能附上来源链接。

### ISSUE THREAD

**Issue by Boms** [webclipper/web-clipper#253]
如题，希望剪藏时能附上来源链接。这样，回顾剪藏内容时，容易找到原始页面。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/67785147-c306dc80-faa7-11e9-877d-5a4ba2950fe3.png)

剪藏本身支持安装插件。

**Comment by DiamondYuan** [comment]
能改一下商店的评价么。🥺

**Comment by Boms** [comment]
商店评价已经改成5星了。感谢快速响应。
现在插件实现的来源链接比较简略，要是用markdown的 "[页面标题](http://xxx)" 格式实现就好了，并希望能自定义放页头或页尾，而且是一个默认功能，不需要再手动点击工具。 

> 能改一下商店的评价么。🥺
