### ISSUE TITLE
onenote 授权到期或者失效后无法重新授权

### ISSUE THREAD

**Issue by nickfan** [webclipper/web-clipper#254]
![image](https://user-images.githubusercontent.com/100613/67841996-4a9a2d00-fb34-11e9-8487-3969d5135850.png)

授权到期只能删了账户重新添加吗？没有一个重新授权的流程机制吗？

**Comment by zhanyu8008** [comment]
遇到同样的问题，OneNote剪藏不了了

**Comment by DiamondYuan** [comment]
默认应该是自动授权的

**Comment by DiamondYuan** [comment]
> 遇到同样的问题，OneNote剪藏不了了

添加一个 bear ，然后账户切换到bear，再切回来试试看。

**Comment by zhanyu8008** [comment]
我是win10，没法添加Bear，尝试添加Notion，但是点击完Verify以后，自己创建的笔记本都读不出来，很奇怪
我试着在微软那删除Webclipper权限，然后重新连接，还是一样提示unauthorized……无助

**Comment by zhanyu8008** [comment]
Onenote原因已查明，关闭adguard后恢复正常，正在排查那个过滤器/规则的问题
Notion读不出笔记本依然无解……

**Comment by zhanyu8008** [comment]
关闭：Block the third-party Authorization header 后恢复正常

**Comment by nickfan** [comment]
> 关闭：Block the third-party Authorization header 后恢复正常

在哪里关闭？

**Comment by zhanyu8008** [comment]
> > 关闭：Block the third-party Authorization header 后恢复正常
> 
> 在哪里关闭？

setting → stealth mode，往下多滑动一点页面，Tracking Method中可以找到

**Comment by nickfan** [comment]
没找到，我没安装ad guard

**Comment by zhanyu8008** [comment]
> 没找到，我没安装ad guard

![sp20191112_223933_188](https://user-images.githubusercontent.com/10270522/68680846-53abe500-059d-11ea-90c4-af8575e492a5.png)
应该是你哪个其他的软件或进程做了类似的事情

**Comment by nickfan** [comment]
嗯，那该如何定位是哪个其他软件呢?
我出现unauthorized的情况大多数是：
打开页面然后点了cliper然后点了onenote的设置后，切到别的tab后过了一定时间再切回来可能是不是认证超时了，代码里做个定时器检查一下？

**Comment by zhanyu8008** [comment]
我比较土，一般肯定是涉及网络监控过滤的软件或者浏览器插件，全部关闭再打开排查一遍就行，也省时间

**Comment by DiamondYuan** [comment]
应该已经解决，先关闭了。
