### ISSUE TITLE
对带有行号的代码块识别问题

### ISSUE THREAD

**Issue by lx200916** [webclipper/web-clipper#255]
![image](https://user-images.githubusercontent.com/44310445/67855235-023b3900-fb4d-11e9-9f90-4cd1f6287bcf.png)
![image](https://user-images.githubusercontent.com/44310445/67855303-26971580-fb4d-11e9-8b4e-49f65408a36f.png)
https://www.ibm.com/developerworks/cn/linux/l-linux-filesystem/index.html
此页面的代码块是由table标签呈现,贴到Notion之后既不呈现代码块也不呈现表格,而是变成文本

**Comment by DiamondYuan** [comment]
这个页面的代码块解决了。1.13.0 中发布。
ibm 类似的页面应该也不是问题了。
想提早用的话可以自己构建。
如果以后还碰到类似的问题，可以继续提交 issue。
