### ISSUE TITLE
0.12的智能剪裁裁入了header标签的内容

### ISSUE THREAD

**Issue by lx200916** [webclipper/web-clipper#256]
![image](https://user-images.githubusercontent.com/44310445/67906677-5deade00-fbb0-11e9-98a5-f98aa77f6bdd.png)
如上图,错误裁入了顶栏播放器控件的专辑封面与歌单.
https://blog.lucien.ink/archives/460/

**Comment by DiamondYuan** [comment]
以前版本有吗？

**Comment by lx200916** [comment]
0.11没有这个问题

**Comment by DiamondYuan** [comment]
will fix in 1.17.0
