### ISSUE TITLE
剪藏页面时代码块有内容缺失的情况

### ISSUE THREAD

**Issue by Boms** [webclipper/web-clipper#257]
剪藏页面：[从小白到大师，这里有一份Pandas入门指南](https://mp.weixin.qq.com/s?__biz=MjM5MTI3MzUwMA%3D%3D&chksm=beb8b65989cf3f4fc864c569349c7bcebea779f0ea3ccf95fc2bcc0bfbb6fef7dfa707c94971&idx=1&mid=2650018090&scene=0&sn=8abcafc9eeb7a860d9f5910502ee5a5d&xtrack=1#rd)

# 环境：
Google Chrome 版本 78.0.3904.70（正式版本）
Web Clipper 1.11.0

# 具体差异见下方截图：
## 剪藏的内容：
![截屏2019-10-31上午11 05 22](https://user-images.githubusercontent.com/1822395/67915761-b204bb00-fbce-11e9-983d-3b591aca450b.png)

## 实际页面的内容：
![截屏2019-10-31上午11 05 53](https://user-images.githubusercontent.com/1822395/67915771-b92bc900-fbce-11e9-81e4-7697904d0c73.png)

**Comment by DiamondYuan** [comment]
这个页面的代码块解决了。1.13.0 中发布。
想提早用的话可以自己构建。

**Comment by Boms** [comment]
👍

**Comment by Boms** [comment]
> 这个页面的代码块解决了。1.13.0 中发布。
> 想提早用的话可以自己构建。

👍
