### ISSUE TITLE
无法剪藏到 notion

### ISSUE THREAD

**Issue by TsichiChang** [webclipper/web-clipper#258]
浏览器：Microsoft Edge
Chromium 版本：Version 78.0.276.20
插件版本：1.12.0

剪藏时浏览器报错：
Access to XMLHttpRequest at 'https://www.notion.so/api/v3/loadUserContent' from origin 'chrome-extension://mhfbofiokmppgdliakminbgdgcmbhbac' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by DiamondYuan** [comment]
不好意思， Edge 暂不支持。
