### ISSUE TITLE
如何在开发模式中使用 ReactDevTools 来检查组件呢?

### ISSUE THREAD

**Issue by dive2Pro** [webclipper/web-clipper#259]
目前在开发环境中, 在 chrome 中打开 development app, 在 devTools 中看不到 React 的选项

![image](https://user-images.githubusercontent.com/23192045/68111414-0939c100-ff2a-11e9-8aaa-f1a2e65c3804.png)

这样不能很快知道 app 的元素属于哪个模块的代码, 请问下这里有什么方法吗?

**Comment by DiamondYuan** [comment]
不好意思，没用过 react 的开发插件。
