### ISSUE TITLE
可以上架谷歌商店不？

### ISSUE THREAD

**Issue by longfei8533** [webclipper/web-clipper#260]
解压包安装，每次启动浏览器会有“请停用以开发者模式运行的扩展程序"提示，不太方便

**Comment by DiamondYuan** [comment]
https://chrome.google.com/webstore/detail/web-clipper/mhfbofiokmppgdliakminbgdgcmbhbac

**Comment by DiamondYuan** [comment]
https://chrome.google.com/webstore/detail/web-clipper/mhfbofiokmppgdliakminbgdgcmbhbac
