### ISSUE TITLE
Settings dialog doesn't close when clicking the close button

### ISSUE THREAD

**Issue by beniTrainor** [webclipper/web-clipper#266]
The current version of the Web Clipper Chrome extension displays a settings dialog that doesn't close when clicking the *close* (the *X* at the top right corner) button.

This is what I'm refering to:
![settings_dialog_close_button](https://user-images.githubusercontent.com/18513229/68856499-ed2fdf80-06e0-11ea-9978-da692c91d172.png)

It has taken me a while to figure out that it can be closed by clicking on the previously opened dialog.

If I have some time I'll try to fix it myself. I'm still trying to figure out how it works.

Thanks.

**Comment by DiamondYuan** [comment]
> It has taken me a while to figure out that it can be closed by clicking on the previously opened dialog.
> 
> If I have some time I'll try to fix it myself. I'm still trying to figure out how it works.
> 
> Thanks.

I can close the dialog when i click the X button.

**Comment by DiamondYuan** [comment]
![close](https://user-images.githubusercontent.com/9692408/69061786-d11b9d80-0a54-11ea-9f94-fdd6445b7a91.gif)

**Comment by beniTrainor** [comment]
Yes, it seems to work in your browser. Maybe it's an issue with my particular browser or OS. I'm using the Chromium browser running on Ubuntu.

If you compare how the settings dialog appears on your browser with the image I posted you'll notice that in my case I get a fixed scrollbar showing on all the tabs.

Thanks for looking into this.

**Comment by DiamondYuan** [comment]
Thank you very much, this is a bug.
Is caused by this line of code。

https://github.com/webclipper/web-clipper/blob/797077ebc4afa0aeee76979a3bdd5c4407972496/src/pages/tool/index.tsx#L82

**Comment by DiamondYuan** [comment]
I am very sorry to have troubled you。
If there is no binding account, I will let the extension jump to the account page.
And I need to give the user some tips.

**Comment by beniTrainor** [comment]
Great. No problem.

**Comment by DiamondYuan** [comment]
> Great. No problem.

https://github.com/webclipper/web-clipper/pull/268

I am not good at English, is the current prompt accurate?

**Comment by beniTrainor** [comment]
I don't know. What do you mean by *current prompt*?
