### ISSUE TITLE
OneNote不能选择保存的笔记本

### ISSUE THREAD

**Issue by AprilViolet** [webclipper/web-clipper#280]
您好，想问一下，我的OneNote中有四个笔记本，已经授权登录，可以读取出来但是只读取出来一个笔记本，也只能保存到这个笔记本中，不能选择其它的笔记本。这个笔记本是别人共享给我的，其它三个是自己私有的，并没有共享。是因为这个原因么？

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/70514575-e45eec00-1b6e-11ea-97e8-657cacf61142.png)


![image](https://user-images.githubusercontent.com/9692408/70514592-e9bc3680-1b6e-11ea-98cc-7d4e78981c2b.png)


我试了一下没有问题。

**Comment by DiamondYuan** [comment]
有更多信息吗？

https://www.onenote.com/notebooks?auth=1&nf=1&fromAR=1

这个页面有多少个笔记本？

**Comment by AprilViolet** [comment]
![Snipaste_2019-12-10_17-55-45](https://user-images.githubusercontent.com/40155496/70519909-a7e3be00-1b77-11ea-83f3-f83dbbf389fe.jpg)
![Snipaste_2019-12-10_18-04-12](https://user-images.githubusercontent.com/40155496/70519910-a87c5480-1b77-11ea-86b1-1cdefbc7eb97.jpg)
1.确实有多个笔记本，并且在扩展中能显示出来的那个笔记本还没有在那个里面显示QAQ
2.请问你这个接口是在1中的页面有的吗？但是我找了一遍，并没有发现那个接口的请求额

**Comment by AprilViolet** [comment]
![Snipaste_2019-12-10_19-49-09](https://user-images.githubusercontent.com/40155496/70527155-3828ff80-1b86-11ea-8ee2-2568ba6aba3a.jpg)
您可以看一下

**Comment by DiamondYuan** [comment]
> ![Snipaste_2019-12-10_19-49-09](https://user-images.githubusercontent.com/40155496/70527155-3828ff80-1b86-11ea-8ee2-2568ba6aba3a.jpg)
> 您可以看一下

我发现原因了。
![image](https://user-images.githubusercontent.com/9692408/70546705-bac3b600-1baa-11ea-89cf-a9e057e732cf.png)

剪藏是以分区作为最小单位的。
如果我没猜错的话，你的 Program 学习编程里面应该一个分区都没有。

![image](https://user-images.githubusercontent.com/9692408/70546798-e646a080-1baa-11ea-8f97-aead7c0879ef.png)

只要新建一个分区，就可以选择了。

**Comment by AprilViolet** [comment]
@DiamondYuan 
好吧，刚才试了一下，确实是这样的。我一般是笔记本下有分区组，然后分区组中放分区的，所以前面三个都没很好的识别出来。感谢您的解答。如果可以还是感觉能够把笔记本下的分区组和分区区分开来就非常不错了。
