### ISSUE TITLE
关于notion图标不显示的问题

### ISSUE THREAD

**Issue by Chandler-Lu** [webclipper/web-clipper#291]
开发者您好～
在账户设置中，notion 的图标是正常的
![WX20191212-192316](https://user-images.githubusercontent.com/18322610/70708343-3a6d9400-1d15-11ea-8414-2ec1f6c5cef7.png)

但是在剪藏插件中，notion是一个空图标，不知道能否修复。另外可否允许用户对每一个账户进行自定义备注，并在该选择列表中显示，而不是完全根据图标判断对应的账户？
![WX20191212-192355](https://user-images.githubusercontent.com/18322610/70708344-3a6d9400-1d15-11ea-9a81-ed7cdd60c238.png)

---

另外还有一个支持问题，不知道能否支持阿里OSS，腾讯COS和七牛的图床，这几个可能用的人会更多一些。

谢谢～

**Comment by Chandler-Lu** [comment]
``` html
<li role="option" unselectable="on" title="XXXXXX" class="ant-select-dropdown-menu-item ant-select-dropdown-menu-item-selected" aria-selected="true" style="user-select: none;">
    <span class="ant-avatar ant-avatar-sm ant-avatar-circle">
        <span class="ant-avatar-string" style="transform: scale(1) translateX(-50%);"></span>
    </span>
</li>
```

**Comment by DiamondYuan** [comment]
图标不显示可能是因为网络问题。


阿里OSS，腾讯COS和七牛的图床 这个在规划中。一定会做。

**Comment by DiamondYuan** [comment]
请问你 notion 设置了头像吗

![image](https://user-images.githubusercontent.com/9692408/70760621-36795a80-1d85-11ea-8899-985a15c66968.png)

**Comment by Chandler-Lu** [comment]
emmm，我傻了。。我只设置workspace的头像。。没有设置账号头像= =
