### ISSUE TITLE
求一个Joplin剪藏插件

### ISSUE THREAD

**Issue by SenLief** [webclipper/web-clipper#293]
Joplin本身有剪藏服务的，但是感觉不好用，希望能够web-clipper能够支持。使用token的这个应该比较好支持的。

**Comment by SenLief** [comment]
开源笔记：https://github.com/laurent22/joplin

**Comment by DiamondYuan** [comment]
嗯，会做的。

**Comment by SenLief** [comment]
多谢作者！

发自我的华为手机


-------- 原始邮件 --------
发件人： DiamondYuan <notifications@github.com>
日期： 2019年12月14日周六 半夜12:18
收件人： webclipper/web-clipper <web-clipper@noreply.github.com>
抄送： SenLief <zjanence@gmail.com>, Author <author@noreply.github.com>
主 题： Re: [webclipper/web-clipper] 求一个Joplin剪藏插件 (#293)

嗯，会做的。

―

**Comment by dwdcth** [comment]
正有此需求，感谢作者👍

**Comment by AceAttorney** [comment]
确实不好用，希望早日支持，谢谢作者

**Comment by DiamondYuan** [comment]
[Uploading web-clipper_1.15.1_beta.zip…]()

**Comment by DiamondYuan** [comment]
1.16.0 will support joplin。or you can try 1.15.1 beta.
1.16.0 会正式支持 joplin。等不及可以尝鲜 1.15.1 beta.

**Comment by SenLief** [comment]
感谢作者！明天会做下测试反馈！


-------- 原始邮件 --------
发件人： DiamondYuan <notifications@github.com>
日期： 2019年12月27日周五 半夜11:46
收件人： webclipper/web-clipper <web-clipper@noreply.github.com>
抄送： SenLief <zjanence@gmail.com>, Author <author@noreply.github.com>
主 题： Re: [webclipper/web-clipper] 求一个Joplin剪藏插件 (#293)

1.16.0 will support joplin。or you can try 1.15.1 beta.
1.16.0 会正式支持 joplin。等不及可以尝鲜 1.15.1 beta.

―
