### ISSUE TITLE
github 可以保存在 code 里吗？

### ISSUE THREAD

**Issue by eallion** [webclipper/web-clipper#297]
github 可以保存在 code 里吗？
现在好像是保存在 issues 里

**Comment by DiamondYuan** [comment]
> github 可以保存在 code 里吗？
> 现在好像是保存在 issues 里

issue 自带 tag 功能。所以会比较好用。
未来可能新增 gist ，暂时没有计划支持保存到 code 。

**Comment by eallion** [comment]
但是 issues 打包备份有点麻烦。

**Comment by tangkaichuan** [comment]
@eallion 试试 https://git.io/gissue

**Comment by eallion** [comment]
> @eallion 试试 https://git.io/gissue

这个我知道，还有另一个工具是同样的功能，但是一点也不 geek

**Comment by ministp** [comment]
同求，希望剪辑的保存到code中，后期下载下来
