### ISSUE TITLE
智能提取和提取整个页面会出现混乱

### ISSUE THREAD

**Issue by shenweiyan** [webclipper/web-clipper#3]
不错的工具，有些功能能完善一下就好了~

**Comment by DiamondYuan** [comment]
能详细说一下吗？

**Comment by istevenshen** [comment]
> 能详细说一下吗？

剪取 wordpress 的文章，样式和代码有时候会混乱。例如这篇文章（[https://www.r-bloggers.com/5-ways-to-subset-a-data-frame-in-r/](https://www.r-bloggers.com/5-ways-to-subset-a-data-frame-in-r/)）的剪藏"整个页面"和"智能提取"得到的效果都不是很好。 

- 剪藏整个页面，会导致头部的列表样式混乱，代码块也如此
![01-1](https://user-images.githubusercontent.com/26101369/48750766-c3093480-ecbb-11e8-8e37-515b79876dc9.png)
![剪藏整个页面](https://user-images.githubusercontent.com/26101369/48750640-17f87b00-ecbb-11e8-9a65-ea653909594e.png)

- 智能提取，部分代码块样式没有
![智能提取](https://user-images.githubusercontent.com/26101369/48750645-1dee5c00-ecbb-11e8-920b-e572608d8db4.png)

剪藏简书上面的一些文章，有时候也会出现这些问题。例如这篇文章：[https://www.jianshu.com/p/d4d5e07ea0cd](https://www.jianshu.com/p/d4d5e07ea0cd)

**Comment by DiamondYuan** [comment]
更新到 1.6.1 能解决问题。
