### ISSUE TITLE
现在是不是还不支持代码块呢？

### ISSUE THREAD

**Issue by fr0der1c** [webclipper/web-clipper#305]
https://blog.magrathealabs.com/pythons-covariance-and-contravariance-b422c63f57ac

尝试了一下保存这个网页到notion，网页里面的python代码（用`<pre>`）包围的没有被存成代码格式，导致无法阅读。

**Comment by DiamondYuan** [comment]
> https://blog.magrathealabs.com/pythons-covariance-and-contravariance-b422c63f57ac

一部分代码都兼容了。有一部分需要手动适配。

**Comment by DiamondYuan** [comment]
最近的代码兼容了这个问题。

是这个 commit 修复的 https://github.com/webclipper/ecosystem/commit/77039a728c729b74f90ecc31df59c3a8a2f49b11

我先关闭了，如果有需要，可以自己构建项目。

**Comment by DiamondYuan** [comment]
[Uploading web-clipper_1.15.1.zip…]()


这个是我构建的版本。
