### ISSUE TITLE
possible bug: some images are resized when it shouldn't

### ISSUE THREAD

**Issue by davidpoza** [webclipper/web-clipper#309]
Open this possible bug after posting on forum: https://discourse.joplinapp.org/t/some-low-quality-images-with-web-clipper/4812/2

You can reproduce the behaviour when this article:  https://blog.bitsrc.io/making-api-calls-with-react-hooks-748ebfc7de8c 

It contains the following image: https://miro.medium.com/max/1788/1*e58rQldTQyOijWVWQtp8wQ.png, which is resized from 1788x1280px and not even 500kb to 60x42px and 2.8kb. (so it's unreadable)

As tessus user suggested I build electron app applying this changes: https://github.com/tessus/joplin/commit/6fbb59a69684209a7389b13c0d10727b04cce3c8

Any way, I had no luck, these changes seem to apply only when attaching files on Joplin client.

So the problems looks like to be related to web-clipper.

**Comment by DiamondYuan** [comment]
fix by https://github.com/webclipper/web-clipper/commit/715df72b35998e2ce06bc9346d144d2cc99a3a5b

will release in 1.1.9.0
