### ISSUE TITLE
最近好像出了问题，在登录notion的情况下无法绑定notion账号，提示Cannot read property 'toString' of undefined，请求解决

### ISSUE THREAD

**Issue by hyurpg** [webclipper/web-clipper#313]
最近好像出了问题，在登录notion的情况下无法绑定notion账号，提示Cannot read property 'toString' of undefined，请求解决

**Comment by DiamondYuan** [comment]
我刚才试了一下，自己的账户是没问题的。
可能你的账户有一些特殊的地方，方便加一下钉钉群或者 tg 群吗？

**Comment by DiamondYuan** [comment]
已经解决。可能是因为有未命名的文档。
Has been resolved. It may be because there are untitled documents.
