### ISSUE TITLE
不支持notion的database

### ISSUE THREAD

**Issue by XinArkh** [webclipper/web-clipper#323]
首先感谢作者的辛勤劳动。
在使用过程中发现notion只能剪藏到自己帐号目录下的普通页面（如默认的Get Started），而无法剪藏到notion的database目录中（如notion自带的网页剪藏插件会把网页收集到一个叫做My Links的database中，而web clipper的知识库选项中找不到这个database）。请问可否增加对notion
 database的支持？谢谢！

**Comment by DiamondYuan** [comment]
保存到 notion 的原理是通过 import markdown 来实现的，而 database 是不支持导入 markdown 的。
所以在 notion API 出现一起是不会支持 database 的。
我先关闭来，到时候回第一时间支持的。

**Comment by edisonator** [comment]
Page Block 分两种类型：`page` 和 `collection_view_page`，后者即 Database。
两种页面结构稍有不同，所以需要在创建子页面时稍微判断一下，用不同的字段。

page：和现在的逻辑一致，直接创建。
  ##```typescript
{
  parent_id: pageId,
  parent_table: 'block',
  alive: true
}
```
collection_view_page：此时页面一定会关联一个 collection（即 database），所以需要做的是在这个 collection 下面创建新页面，而不是 page block 下面。
```typescript
{
  parent_id: collectionId,
  parent_table: 'collection',
  alive: true
}
```
在 Notion 自己的逻辑里，也是用以上三个字段来从数据库或缓存中存取 Database 内容的。

#433

**Comment by DiamondYuan** [comment]
will release in 1.25.
