### ISSUE TITLE
读取notion的知识库有点问题

### ISSUE THREAD

**Issue by ShinyeeHwang** [webclipper/web-clipper#330]
绑定notion账号后，只能选择存到某几个知识库，没有读取到全部知识库，有一个还是已被删除的库，清楚浏览器缓存和cookie、重新登录notion多次还是这样，怪怪的（图1，插件读取；图2，我的notion目录）
![image](https://user-images.githubusercontent.com/30626009/72314285-4a3c1780-36c9-11ea-877b-98dde2251eb3.png)
![image](https://user-images.githubusercontent.com/30626009/72314312-6475f580-36c9-11ea-889b-53f0562fb34b.png)

**Comment by DiamondYuan** [comment]
只会读取文档数据库，不支持 database

**Comment by DiamondYuan** [comment]
请问可以加 钉钉群 或 telegram 群吗？我可以一对一来解决这个问题。

**Comment by ShinyeeHwang** [comment]
只读取文档数据库我明白了～晚点有空可以加钉钉群看看，thx

DiamondYuan <notifications@github.com> 于2020年1月14日周二 下午10:29写道：

**Comment by steveyang331** [comment]
如果不支持database，那对我基本没用了。主要用于收藏网页，当做收藏夹来用，clip到列表里面

**Comment by rovernerd** [comment]
> 如果不支持database，那对我基本没用了。主要用于收藏网页，当做收藏夹来用，clip到列表里面

那用官方的不就好了

**Comment by steveyang331** [comment]
> > 如果不支持database，那对我基本没用了。主要用于收藏网页，当做收藏夹来用，clip到列表里面
> 
> 那用官方的不就好了

恩。但是官方不支持截图以及其他功能。

**Comment by DiamondYuan** [comment]
最新版支持了。
