### ISSUE TITLE
Bear 服务校验出现错误

### ISSUE THREAD

**Issue by laoluo8** [webclipper/web-clipper#347]
设置页面选择 Bear 后不能校验服务
<img width="565" alt="截屏2020-02-04下午7 20 48" src="https://user-images.githubusercontent.com/44857747/73740616-75270200-4783-11ea-83d7-4476a764fd12.png">

**Comment by laoluo8** [comment]
> 设置页面选择 Bear 后不能校验服务
> <img alt="截屏2020-02-04下午7 20 48" width="565" src="https://user-images.githubusercontent.com/44857747/73740616-75270200-4783-11ea-83d7-4476a764fd12.png">

添加以后也不能剪藏

**Comment by DiamondYuan** [comment]
> > 设置页面选择 Bear 后不能校验服务
> > <img alt="截屏2020-02-04下午7 20 48" width="565" src="https://user-images.githubusercontent.com/44857747/73740616-75270200-4783-11ea-83d7-4476a764fd12.png">
> 
> 添加以后也不能剪藏

有什么报错吗？

**Comment by DiamondYuan** [comment]
我在本地无法复现这个问题，就先关闭 issus 了。如果还有问题，可以再次打开。
