### ISSUE TITLE
有支持Firefox的计划吗?

### ISSUE THREAD

**Issue by izuolan** [webclipper/web-clipper#349]
我看一个月前有Firefox支持的代码更新, 是不是意味着Firefox版本的插件快来了呢?

**Comment by DiamondYuan** [comment]
> 我看一个月前有Firefox支持的代码更新, 是不是意味着Firefox版本的插件快来了呢?

早就支持了。不过被下架了。

**Comment by izuolan** [comment]
那Firefox怎么安装这个插件呢

**Comment by DiamondYuan** [comment]
firefox 不支持 eval 和远程代码。和目前架构冲突了。

**Comment by DiamondYuan** [comment]
https://addons.mozilla.org/en-US/firefox/addon/universal-web-clipper/
