### ISSUE TITLE
请问能否增加Github为图床

### ISSUE THREAD

**Issue by cuoe** [webclipper/web-clipper#353]
剪藏时把图片上传到code里，或者issues里本身也可以上传图片。
如果可以增加这个功能，剪藏到Github的网页就不需要外链imgur和smms图床了，需要打包下载备份的话也方便。

最近看到两个软件，都可以把Github当图床

[PicGo](https://github.com/Molunerfinn/PicGo) 一个用于快速上传图片并获取图片URL链接的工具

[GitNote](https://github.com/zhaopengme/gitnote) 基于Git的笔记软件

**Comment by linonetwo** [comment]
我现在在用 Github 放 Nodejs 版的 TiddlyWiki https://github.com/linonetwo/Tiddlywiki-NodeJS-Github-Template ，要是能直接剪藏图片和文本到 Github，就相当于能剪藏到 TiddlyWiki 了

**Comment by OkamiWong** [comment]
我正在实现将剪藏的文本和图片都保存到Github的Code里，现在保存文本到Code已经ok了，等我做完图片就开PR

**Comment by linonetwo** [comment]
@OkamiWong 太好啦，能选择保存的位置（自定义保存文件夹）吗？

**Comment by OkamiWong** [comment]
可以的

**Comment by DiamondYuan** [comment]
> 可以的

太棒了。先提交看看

**Comment by OkamiWong** [comment]
提交好啦 @DiamondYuan 
https://github.com/OkamiWong/web-clipper/commit/1b6fe8796313dad02dde7778b4956b7988a919ea

**Comment by DiamondYuan** [comment]
> 保存文本的 Feature 已经提交好啦 @DiamondYuan 
> 
> https://github.com/OkamiWong/web-clipper/commit/1b6fe8796313dad02dde7778b4956b7988a919ea

新增一个类型吧。
初始化的时候设置代码库。然后之前的代码选择变成目录选择。你觉得如何。

**Comment by OkamiWong** [comment]
> 新增一个类型吧。
> 初始化的时候设置代码库。然后之前的代码选择变成目录选择。你觉得如何。

是说添加一个新的账户类型么？还有代码选择和目录选择是指啥？我没太明白

**Comment by DiamondYuan** [comment]
> > 新增一个类型吧。
> > 初始化的时候设置代码库。然后之前的代码选择变成目录选择。你觉得如何。
> 
> 是说添加一个新的账户类型么？还有代码选择和目录选择是指啥？我没太明白

现在选择的是 git 仓库。如果新类型的话，可以改成选择目录。

**Comment by OkamiWong** [comment]
> > > 新增一个类型吧。
> > > 初始化的时候设置代码库。然后之前的代码选择变成目录选择。你觉得如何。
> > 
> > 
> > 是说添加一个新的账户类型么？还有代码选择和目录选择是指啥？我没太明白
> 
> 现在选择的是 git 仓库。如果新类型的话，可以改成选择目录。

是指“知识库”可以直接选择某个仓库的某个文件夹么？
我觉得先选一个仓库再设置目录也挺 Intuitive 的

**Comment by linonetwo** [comment]
<img width="767" alt="截屏2020-12-03 下午4 10 56" src="https://user-images.githubusercontent.com/3746270/100981866-57345480-3582-11eb-892c-2e1817b8dbf4.png">

好像还不支持呀，新版是增加了图床选 Github 并能选文件夹吗？

**Comment by DiamondYuan** [comment]
> <img alt="截屏2020-12-03 下午4 10 56" width="767" src="https://user-images.githubusercontent.com/3746270/100981866-57345480-3582-11eb-892c-2e1817b8dbf4.png">
> 
> 好像还不支持呀，新版是增加了图床选 Github 并能选文件夹吗？

canary ，商店在审核
