### ISSUE TITLE
绑定OneNote时，office365公司或学校账户不能得到授权

### ISSUE THREAD

**Issue by kaisquares** [webclipper/web-clipper#356]
绑定OneNote时，office365公司或学校账户不能得到授权，请问是我个人的问题吗？

**Comment by DiamondYuan** [comment]
请问你用的是最新版本吗？最新版本应该解决了这个问题。

**Comment by kaisquares** [comment]
> 请问你用的是最新版本吗？最新版本应该解决了这个问题。

我用的是1.18.0chrome和edge商店目前最新的版本，是要升级到1.19版本才能修复这个问题吗？目前还是不能登录o365的邮箱，会自动跳转到login.live.com页面去拿授权。

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases

**Comment by DiamondYuan** [comment]
1.22.0 试试看？
