### ISSUE TITLE
sm.ms图床接口不可用

### ISSUE THREAD

**Issue by yjli815** [webclipper/web-clipper#364]
请求响应：
`{
	"success": false,
	"code": "error",
	"message": "API v1 is deprecated, please refer to https://doc.sm.ms/ for v2 API documentation.",
	"RequestId": "1C74B46B-9E00-42AD-9F68-189728CAEDF4"
}`

**Comment by DiamondYuan** [comment]
1.21.0 修复了

**Comment by yjli815** [comment]
> 1.21.0 修复了

谢谢

**Comment by DiamondYuan** [comment]
提交审核了，要过几天。
