### ISSUE TITLE
OneNote connectivity

### ISSUE THREAD

**Issue by premsundaram** [webclipper/web-clipper#365]
Hi
I like your web clipper application for Microsoft Edge Windows 10!

BUT

I try to use OneNote. Its starts OK but then later after a few hours the authentication does not work and I get ‘network error’

Please fix. It cannot be used if the connection to OneNote keeps dropping. 

Thanks!
Prem

**Comment by DiamondYuan** [comment]
Thanks, this is a bug .Will fix in next version.

**Comment by premsundaram** [comment]
That is great to hear!
________________________________
