### ISSUE TITLE
是否可以支持Safari浏览器 

### ISSUE THREAD

**Issue by lipengyu** [webclipper/web-clipper#367]
是否可以支持Safari浏览器

**Comment by DiamondYuan** [comment]
研究过，支持很难。应该不会支持。

**Comment by guohao117** [comment]
safari 14已经支持其他浏览器同样的WebExtensions API ，可否重新考虑移植？

**Comment by DiamondYuan** [comment]
> safari 14已经支持其他浏览器同样的WebExtensions API ，可否重新考虑移植？

天天 996，时间不太够。（有空会移植的

**Comment by Jax0rz** [comment]
Safari Mac版本我会付费购买，麻烦商家苹果Mac AppStore，定价30块以内，我觉得很多人会支持的。

**Comment by Cleverambo** [comment]
同期待Safari版本。大部分剪藏插件都有官方的Chrome和Firefox版本，而缺少Safari版本，这个项目正好可以弥补这个缺憾。（没有催更的意思，作者注意休息😅

**Comment by yushaw** [comment]
附议，希望作者能考虑

**Comment by CoderTonyChan** [comment]
mark

**Comment by pwelyn** [comment]
Mark

**Comment by kennir** [comment]
测试了一下xcode带的扩展转换工具，虽然可以成功转换为safari的extension，但是点击图标后没有任何反应。

**Comment by h4rk8s** [comment]
mark

**Comment by ZER0-Nu1L** [comment]
Mark

**Comment by kalarita** [comment]
mark

**Comment by minspy** [comment]
mark

**Comment by wisinfun** [comment]
Mark
