### ISSUE TITLE
滴答清单绑定失败

### ISSUE THREAD

**Issue by johony** [webclipper/web-clipper#372]
已登录滴答清单网页版，点击效验，但是**提示绑定失败**，如图：

![滴答清单报错](https://user-images.githubusercontent.com/17739505/78344835-88ade800-75cf-11ea-931e-b2273cf5c346.png)

**Comment by DiamondYuan** [comment]
希望可以加群

**Comment by DiamondYuan** [comment]
我试了一下没问题。

**Comment by johony** [comment]
我使用的是 Brave 浏览器，刚刚用 Chrome 浏览器登录是没有问题的。
抱歉
