### ISSUE TITLE
剪辑上传至雨雀后无法在客户端识别

### ISSUE THREAD

**Issue by lipengyu** [webclipper/web-clipper#376]
<img width="489" alt="bug" src="https://user-images.githubusercontent.com/36474/78974675-16945080-7b45-11ea-893e-7b57fba12e1c.png">

**Comment by lipengyu** [comment]
<img width="489" alt="bug" src="https://user-images.githubusercontent.com/36474/78960210-f0a88500-7b1f-11ea-8082-196e48453bd5.png">

**Comment by DiamondYuan** [comment]
没办法。
