### ISSUE TITLE
剪藏到语雀的内容无法搜索到正文的内容

### ISSUE THREAD

**Issue by lawlietc** [webclipper/web-clipper#386]
就是直接用cliper剪藏到语雀的知识库之后，在语雀中无法搜索到文章的正文内容，只能搜到标题。

以及一些信息，不知道有用：
1、我试了一下在语雀中编辑再保存一次（实际我并未更改内容），就能搜到正文了
2、语雀有人反馈类似的问题 https://www.yuque.com/yuque/topics/9990

**Comment by DiamondYuan** [comment]
这个是语雀的问题。
