### ISSUE TITLE
机核网剪藏不全

### ISSUE THREAD

**Issue by NupishCosfuned** [webclipper/web-clipper#388]
机核网中有通过左右标签来切换的图片，如果能将之转化成上下排列的Markdown再存入语雀就好了。
但这个并不致命，要命的是机核网里的文章标题没法保存，存到语雀里那些标题完全就成了空白，只能新建文档然后复制粘贴，可是这样复制粘贴又会失去退格。
拜托作者优化一下机核网的剪藏。

**Comment by DiamondYuan** [comment]
来个链接？

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/80506892-c290c500-89a8-11ea-950a-af57fdcd5dba.png)


顺便提一下，右边的标题是可以编辑的。

**Comment by NupishCosfuned** [comment]
我指的不是那个标题，我指的是正文中的标题：

![网页正文](https://cdn.nlark.com/yuque/0/2020/png/1234935/1588381363570-aff0fcb3-3f84-4bbf-a2fa-4351220f891b.png)

然后裁剪之后就变成了这样，里面的“第一部分：锋芒的指向——日本刀及其发展史”消失了：

![裁剪状态](https://cdn.nlark.com/yuque/0/2020/png/1234935/1588381361984-f5705219-f26a-4318-93a0-d22981d2c00b.png)

类似的所有标题都会消失，但如果手动复制粘贴到语雀中又能正常显示标题。

下面是原文链接：

https://www.gcores.com/articles/111287

另外，还有部分机核网文章在一个图片的位置放置多张图片，这种格式也是没法裁剪的。

比如该文章：https://www.gcores.com/articles/122716

原文：

![原文截图](https://cdn.nlark.com/yuque/0/2020/png/1234935/1588382001502-39346462-88ab-4e12-8586-76fd93004c60.png)

裁剪状态：

![裁剪状态](https://cdn.nlark.com/yuque/0/2020/png/1234935/1588382002930-b40c4826-612a-4ec8-81ff-d8cdf1c24f1f.png?x-oss-process=image%2Fresize%2Cw_1492)

**Comment by DiamondYuan** [comment]
手动选取目前应该还算完美

**Comment by DiamondYuan** [comment]
有问题可以继续 open
