### ISSUE TITLE
剪藏后 在语雀客户端打开后  显示 老的markdown格式不支持客户端打开

### ISSUE THREAD

**Issue by enron2014** [webclipper/web-clipper#407]
![image](https://user-images.githubusercontent.com/38575961/81658516-6d09ed00-946b-11ea-8dba-a6bc41736409.png)

**Comment by DiamondYuan** [comment]
这个是语雀的问题。用 API 创建的都是老文档。

**Comment by DiamondYuan** [comment]
https://www.yuque.com/yuque/help/changelog#WHnE4
