### ISSUE TITLE
获取网页全文或手动选择部分的时候，自动添加原文链接而不是再选择一次扩展

### ISSUE THREAD

**Issue by heartsoarrq** [webclipper/web-clipper#416]
**获取网页全文或手动选择部分的时候，自动添加“在文章末尾添加当前网址”而不是再选择一次扩展**
优化操作步骤。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/82655532-e5836180-9c54-11ea-8f1e-18c885604049.png)

**Comment by DiamondYuan** [comment]
机器人是红色的表示会自动运行。
