### ISSUE TITLE
firefox addon is not available.

### ISSUE THREAD

**Issue by murarisumit** [webclipper/web-clipper#444]
**Bug 描述**
I'm not able to find extension for firefox in addons-store, was getting this. 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/2667258/84295555-5a68fd80-ab68-11ea-9ef9-86f21b369ddd.png">

**Comment by ahkhystrix** [comment]
The same problem.

**Comment by DiamondYuan** [comment]
now available
