### ISSUE TITLE
语雀 formart invalid

### ISSUE THREAD

**Issue by wsqstar** [webclipper/web-clipper#451]
**Bug 描述**

语雀一键授权。
剪藏了一个语雀的文档，存在了语雀内部。
可以正常阅读，想要修改的时候也可以修改，
就是语雀显示 formart invalid。
**复现步骤**

重现的步骤：

1.使用语雀一键授权。
2.剪藏一个语雀的文档，存入语雀内部。
3.前往存储空间，查看（正常）
4. 点击修改
5. 点击保存
6.后果：语雀显示 formart invalid，并无法保存、修改剪藏的文章。
**预期行为**

正常使用、可以修改

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: yuque
- 浏览器  chrome 83.0.4103.106
- 版本 1.24.0 

**其他背景**

语雀相关讨论：https://www.yuque.com/yuque/topics/12864

**Comment by DiamondYuan** [comment]
this is bug of yuque.
