### ISSUE TITLE
Vivaldi浏览器下无法关联语雀

### ISSUE THREAD

**Issue by HuangAdam** [webclipper/web-clipper#460]
在Vivaldi浏览器下，语雀双登录方式均无法使用

点击校验无反应
点击授权登录无反应

流程为：
绑定账号→→语雀/Token输入完成/任意类型库→→点击校验无反应
绑定账号→→语雀(一键授权)→→点击授权登录无反应

- 笔记平台: yuque
- 浏览器 :Vivaldi
- 版本 3.1.1929.45 (Stable channel) （64 位）

以关闭其他扩展排除原因，确认无效

![无效展示](https://user-images.githubusercontent.com/46439030/86011944-e8d9ec00-ba4f-11ea-8efd-ad7740e63aea.png)

**Comment by DiamondYuan** [comment]
已知问题。权限的锅。

**Comment by HuangAdam** [comment]
> 已知问题。权限的锅。

这种情况怎么办，有其他办法解决吗？
是你还要修还是这情况没办法？

**Comment by DiamondYuan** [comment]
试试看 1.25.0 的 firefox 版本

**Comment by DiamondYuan** [comment]
fix in 1.26.0
