### ISSUE TITLE
Firefox无法安装

### ISSUE THREAD

**Issue by BrokenChip** [webclipper/web-clipper#487]
**Bug 描述**

firefox addon商店没有该插件

**复现步骤**

重现的步骤：

1. 打开 'readme.md'
2. 点击链接 'Install Firefox 1.25.0'
3. 跳转到 'https://addons.mozilla.org/en-US/firefox/addon/universal-web-clipper/'
4. 看到错误 'Oops! We can’t find that page'

**截图**

![图片](https://user-images.githubusercontent.com/26518436/88457632-a246a880-ceba-11ea-8ecc-3e5d98f4617f.png)

![图片](https://user-images.githubusercontent.com/26518436/88457621-8d6a1500-ceba-11ea-897d-883d96cd19c6.png)

**请填写以下信息**

- 浏览器 [firefox]
- 版本 [78.0.2 (64 位)]

**Comment by DiamondYuan** [comment]
不好意思，又被下架了。

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/issues/504
