### ISSUE TITLE
合作咨询

### ISSUE THREAD

**Issue by sunbo** [webclipper/web-clipper#498]
您好，我是baklib（https://www.baklib.com ） 的产品，我们是一款云端知识库建设平台，基于人工智能的知识管理、帮助中心、Guide、FAQ、API文档、产品手册制作软件。
现在有个需求是想制作一款浏览器插件，用户可以把当前浏览的网页导入到baklib个人站点内。看web-clipper制作的已经很强大了，不知道能否在里面添加一下baklib的选项。我们已经对外开放了api（https://api.baklib.com ） ，或者您告诉我们相关的代码规范，我们自己写相对应的功能也可以的。

**Comment by krongk** [comment]
目前Web Clipper已经支持baklib（https://www.baklib.com ） API了。
