### ISSUE TITLE
文章中的html代码的时候标签会被转义

### ISSUE THREAD

**Issue by lengthmin** [webclipper/web-clipper#5]
http://bubkoo.com/2014/01/04/emmet-a-toolkit-for-improving-html-css-workflow/
这篇文章中的代码，`标签的>` 和`=`前都有多的 `\` 符号。
这里的代码也没抓出来，是我自己加上的代码标签。 
![image](https://user-images.githubusercontent.com/13938334/51115038-0dcda580-1842-11e9-81fc-92c0fcbd5bce.png)

原网页：
![image](https://user-images.githubusercontent.com/13938334/51115131-49686f80-1842-11e9-81e1-c7e27f4c2c75.png)
印象笔记：
![image](https://user-images.githubusercontent.com/13938334/51115155-58e7b880-1842-11e9-8597-b005f50e6cc6.png)

**Comment by DiamondYuan** [comment]
修复了。支持解析 hexo 的代码块

需要手动选取，而不是智能提取。
