### ISSUE TITLE
希望对掘金网站 code 剪切格式做出适当修改

### ISSUE THREAD

**Issue by jacob-lcs** [webclipper/web-clipper#501]
目前来说，web-clipper 软件对掘金网站中的博文剪切之后呈现的效果不佳，特质代码方面，目前剪切下来的样式是这个样子的
![image](https://user-images.githubusercontent.com/40483898/89733713-099f5380-da8a-11ea-95d8-8b08d364d906.png)
剪切下来的代码有**复制代码**这几个问题，少了还好，如果代码段比较多该起来比较麻烦，所以想问下能不能对特殊网站做适配呢。

**Comment by DiamondYuan** [comment]
文章链接是什么？老哥有兴趣自己提 PR 么。

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/ecosystem/blob/master/packages/turndown/src/plugins/csdnCodeBlock.ts

**Comment by DiamondYuan** [comment]
这里就是做适配的。

**Comment by jacob-lcs** [comment]
当然愿意做适配！让我先来看一下😁

**Comment by DiamondYuan** [comment]
> 当然愿意做适配！让我先来看一下😁

https://github.com/webclipper/ecosystem/pull/7

我搞好了。yarn test 本地跑测试

现在本地跑测试似乎有点问题。估计和 jsdom 的实现有关。

**Comment by jacob-lcs** [comment]
迅速！web-clipper 什么时候会更新呢

**Comment by DiamondYuan** [comment]
> 迅速！web-clipper 什么时候会更新呢

明天或者后天提交审核。

**Comment by DiamondYuan** [comment]
> 迅速！web-clipper 什么时候会更新呢

可以试试看 canary 版本
