### ISSUE TITLE
The link to Firefox extension is dead

### ISSUE THREAD

**Issue by iootaa** [webclipper/web-clipper#504]
On the [main page](https://github.com/webclipper/web-clipper)  of this repository there is a link to Install on Firefox

This link is dead, and the extension is not available anymore on addons.mozilla.org

**Comment by DiamondYuan** [comment]
I am sorry , it's  Awaiting Review.

![image](https://user-images.githubusercontent.com/9692408/89803661-b7cbfb80-db65-11ea-850c-83e74a0509e2.png)

**Comment by iootaa** [comment]
Ack, thank you!

**Comment by DiamondYuan** [comment]
> Ack, thank you!

https://www.yuque.com/web-clipper/help_en/firefox_install

try this

**Comment by DiamondYuan** [comment]
Back
