### ISSUE TITLE
请问可否给一个通过包方式调用 本项目内置 readability 的例子？

### ISSUE THREAD

**Issue by eromoe** [webclipper/web-clipper#506]
Hello, 

因为web-clipper 已经内置了CSDN 等国内网站常用的解析器。 
我想利用这部分功能，结合 https://github.com/akosbalasko/yarle , 将印象笔记的笔记本全部转成 markdown .  用于导入 Tiddlywiki 或者 obsidian (还在想用哪个) 。
很多网上的转换程序的不能很好的处理印象笔记的 web clip 内容。

我对现在的js 项目也不是很熟，所以想问一下。当然如果有现成的转换器推荐的话就太好了 😄

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/readability

**Comment by eromoe** [comment]
我知道readability 项目，我只用过python版的，他内部肯定没有针对特定网站处理
我是想调用这个项目的清理接口

**Comment by DiamondYuan** [comment]
> 我知道readability 项目，我只用过python版的，他内部肯定没有针对特定网站处理
> 我是想调用这个项目的清理接口

我没有用什么特殊的清理。

**Comment by DiamondYuan** [comment]
> 我知道readability 项目，我只用过python版的，他内部肯定没有针对特定网站处理
> 我是想调用这个项目的清理接口

html -> markdown 针对代码块做了一些处理。

https://github.com/webclipper/ecosystem/blob/master/packages/turndown/package.json

在这里。

**Comment by eromoe** [comment]
3Q , 我研究一下怎么用 😄
