### ISSUE TITLE
为什么用这个撷取网页后格式会变好多，还会出现显示出如链接地址，或者源码之类的不需要的东西

### ISSUE THREAD

**Issue by sunnyvGitHub** [webclipper/web-clipper#510]
这个软件能配合较多的笔记软件，这点是非常棒的，能否加强一下撷取功能， 参考一下其他 项目，如maoxian clipper
https://github.com/mika-cn/maoxian-web-clipper/

**Comment by DiamondYuan** [comment]
有具体点的例子么？

**Comment by DiamondYuan** [comment]
先关了，有问题继续反馈。
