### ISSUE TITLE
希望支持选中的网页文字一建转存到notion或滴答清单的功能

### ISSUE THREAD

**Issue by tttsong** [webclipper/web-clipper#514]
**您的功能要求与问题有关吗？ 请描述。**

希望支持选中的网页文字一建转存到notion的功能

**描述您想要的解决方案**

在浏览网页时，鼠标选中一段想要转存的文字，右键能够弹出选项转存到notion或滴答清单，不希望整个网页搬运过去那种，做到简单快捷

**描述您考虑过的替代方案**

对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**

在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by DiamondYuan** [comment]
试试看 canary 版本。
1.30 版本中将会发布这个功能
