### ISSUE TITLE
语雀剪藏的时候突然默认在未编排目录

### ISSUE THREAD

**Issue by asasn** [webclipper/web-clipper#517]
**Bug 描述**

语雀剪藏的时候突然默认在未编排目录

**复现步骤**

一开始是好好的保存并显示在知识库的目录中的

> 但在语雀删除或者更改过文档之后，就默认不显示在目录了

注：复现失败，只知道同样的剪藏，一个知识库能显示在目录，一个不能……
我暂时无法确认是语雀的问题还是插件的设置

**预期行为**

显示在目录中

**Comment by DiamondYuan** [comment]
如果你手动修改过目录，那新文章不会显示在目录中。

**Comment by DiamondYuan** [comment]
这个是语雀的 feature

（先关了，有问题可以继续打开0
