### ISSUE TITLE
无法保存内容到滴答清单，后台403，字段无值

### ISSUE THREAD

**Issue by messchow** [webclipper/web-clipper#530]
**Bug 描述**

无法保存内容到滴答清单，后台403，字段无值

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/32609442/91248113-7737c900-e786-11ea-854d-f166796d0546.png)
![image](https://user-images.githubusercontent.com/32609442/91248135-84ed4e80-e786-11ea-9409-fd9cd3a7e9a8.png)

**请填写以下信息**

- 浏览器 [chromei]

**Comment by DiamondYuan** [comment]
我本地试了一下是可以的。你确定有对应的清单的权限吗？换一个清单试试看？

**Comment by DiamondYuan** [comment]
@mohuishou  问题解决了么

**Comment by mohuishou** [comment]
> @mohuishou 问题解决了么

感觉 @ 错人了

**Comment by DiamondYuan** [comment]
我在本地无法复现这个问题，就先关闭 issus 了。如果还有问题，可以再次打开。
