### ISSUE TITLE
技术支持，火狐浏览器不能用您的插件了。谢谢谢谢！

### ISSUE THREAD

**Issue by WuZhengqiang666** [webclipper/web-clipper#538]
您好，很抱歉打扰您。

方便看一下火狐浏览器吗？它好像不能使用您开发的插件了。

显示下图的页面，请问如何解决，非常感谢，感谢！谢谢。
![图片](https://user-images.githubusercontent.com/49598775/91742577-0b6fb900-ebe9-11ea-9a89-5e171af0911a.jpg)

**Comment by DiamondYuan** [comment]
> 您好，很抱歉打扰您。
> 
> 方便看一下火狐浏览器吗？它好像不能使用您开发的插件了。
> 
> 显示下图的页面，请问如何解决，非常感谢，感谢！谢谢。
> ![图片](https://user-images.githubusercontent.com/49598775/91742577-0b6fb900-ebe9-11ea-9a89-5e171af0911a.jpg)

审核中，不好意思。

**Comment by DiamondYuan** [comment]
https://www.yuque.com/web-clipper/help_cn/firefox_install

**Comment by WuZhengqiang666** [comment]
您好，非常感谢您的回复，一定程度上解决了我的问题。

火狐浏览器一直在审查，审查的速度好慢。o(╥﹏╥)o。很影响我。

我是新人，我有个可能不成熟的的想法：
火狐浏览器审查的是不是**新版本**的web-clipper，那么 我是否可以下载安装**旧版本的web-clipper**，这个想法是可行的吗？ 如果是，我应该如何操作呢？

期待您可以在百忙之中再次回复我一下，谢谢，辛苦您了。
![image](https://user-images.githubusercontent.com/49598775/91838142-9602f780-ec7f-11ea-9ff1-c5ea263f0945.png)
