### ISSUE TITLE
滴答清单书签保存一直 http error

### ISSUE THREAD

**Issue by Jazenx** [webclipper/web-clipper#542]
RT，滴答清单突然无法保存书签好几天了

**Comment by DiamondYuan** [comment]
试试看登陆一下网页版？我本地试了没问题。

你是什么版本的插件？在哪个平台用？

**Comment by eightHundreds** [comment]
我也有这个问题,最新版的插件,在edge.

接口返回403
![image](https://user-images.githubusercontent.com/18695431/93161655-8f778400-f745-11ea-8812-ef25bb617ccc.png)

**Comment by DiamondYuan** [comment]
> RT，滴答清单突然无法保存书签好几天了

是否开启了禁用三方 cookie ？

**Comment by DiamondYuan** [comment]
@Jazenx  问题解决了吗
