### ISSUE TITLE
无法保存到我来，提示 error

### ISSUE THREAD

**Issue by LouieYoung** [webclipper/web-clipper#552]
**Bug 描述**

无法保存到我来，提示 error

**复现步骤**

重现的步骤：

1. 点击保存
2. 出现error

**预期行为**

预期保存成功

**截图**

![image](https://user-images.githubusercontent.com/41049409/93324185-2298e280-f848-11ea-91f8-9d1e3471d065.png)

**请填写以下信息**

- 笔记平台: wolai
- 浏览器 新edge
- 版本 1.23.0

**其他背景**

不知道为啥

**Comment by Lamb-Yang** [comment]
同样遇到了这个问题，我这提示是`http error`，估计是最近wolai有什么调整

**Comment by xgring** [comment]
同问题，等解决方案

**Comment by kiwiflydream** [comment]
保存时报 **http error**

**Comment by DiamondYuan** [comment]
试试看最新版本 1.27
