### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [webclipper/web-clipper#555]
It is sad that the extension is only in English - I suggest translating.
I am ready to help with translation into Russian.
(For example, you can use Weblate or any other service. It's completely free for open source projects.)

**Comment by comradekingu** [comment]
+1 for Weblate

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/blob/master/src/common/locales/data/ru-RU.json

You can make pull request.
