### ISSUE TITLE
代码的剪藏有点问题

### ISSUE THREAD

**Issue by xmyyzy123** [webclipper/web-clipper#560]
代码的剪藏有点问题
![image](https://user-images.githubusercontent.com/20349084/94129671-3b2f7b00-fe8e-11ea-89ee-df8440383eec.png)
到notion里面就全变成一行了
![image](https://user-images.githubusercontent.com/20349084/94129890-86e22480-fe8e-11ea-9356-2fe8d28a10db.png)

希望能改进一下

**Comment by DiamondYuan** [comment]
来个链接，我看看。

**Comment by xmyyzy123** [comment]
https://blog.csdn.net/yiran103/article/details/89521292

**Comment by cjydayang** [comment]
博客园的文章我遇到了代码块没有识别的问题：https://www.cnblogs.com/jin-yuana/p/9921673.html
![image](https://user-images.githubusercontent.com/24446099/95156384-0a720e80-07c9-11eb-908c-97bac11e1587.png)
![屏幕截图 2020-10-06 114129](https://user-images.githubusercontent.com/24446099/95156400-1362e000-07c9-11eb-864a-26c4e13664c9.png)

**Comment by bigheadzen** [comment]
遇到里同样的问题，研究了一下。感觉是 Notion 的 API 无法识别带 语言后缀的 code block 语义。例如 "```python" 就会有问题， "```" 就没问题。感觉最简单的解法就是发给 notion 之前按照正则表达式做个全局替换。

**Comment by bigheadzen** [comment]
> 博客园的文章我遇到了代码块没有识别的问题：https://www.cnblogs.com/jin-yuana/p/9921673.html
> ![image](https://user-images.githubusercontent.com/24446099/95156384-0a720e80-07c9-11eb-908c-97bac11e1587.png)
> ![屏幕截图 2020-10-06 114129](https://user-images.githubusercontent.com/24446099/95156400-1362e000-07c9-11eb-864a-26c4e13664c9.png)

cnblog 这个估计没啥办法。代码块没有用标准的 `<code>` 标签识别不了。。除非比较恶心的特殊处理了。

**Comment by DiamondYuan** [comment]
> > 博客园的文章我遇到了代码块没有识别的问题：https://www.cnblogs.com/jin-yuana/p/9921673.html
> > ![image](https://user-images.githubusercontent.com/24446099/95156384-0a720e80-07c9-11eb-908c-97bac11e1587.png)
> > ![屏幕截图 2020-10-06 114129](https://user-images.githubusercontent.com/24446099/95156400-1362e000-07c9-11eb-864a-26c4e13664c9.png)
> 
> cnblog 这个估计没啥办法。代码块没有用标准的 `<code>` 标签识别不了。。除非比较恶心的特殊处理了。

很多网站都是单独处理的。
