### ISSUE TITLE
[Joplin] 先选择知识库，再选择剪藏方式的话，会跳转回设置的默认知识库。

### ISSUE THREAD

**Issue by vagra** [webclipper/web-clipper#564]
**Bug 描述**

剪藏到 Joplin 。如果先选择知识库，再选择剪藏方式的话，会跳转回设置的默认知识库。

**复现步骤**

1. 我设置了 Joplin 账户，并设置了默认剪藏到 Joplin 的 Develop 知识库；

2. 在每次要剪藏页面的时候，我总是习惯先选择知识库，比方说我先选择 Software 知识库；

3. 然后我再改变剪藏方式，不管点击何种剪藏方式，下面的知识库都会变回默认的 Develop 知识库。

**预期行为**

我在选择剪藏方式的时候，下面的知识库理应保持我选择好的 Software 知识库。

**请填写以下信息**

- 笔记平台: Joplin
- 浏览器: Firefox
- 版本: 1.26.1

**Comment by DiamondYuan** [comment]
> **Bug 描述**
> 
> 剪藏到 Joplin 。如果先选择知识库，再选择剪藏方式的话，会跳转回设置的默认知识库。
> 
> **复现步骤**
> 
> 1. 我设置了 Joplin 账户，并设置了默认剪藏到 Joplin 的 Develop 知识库；
> 2. 在每次要剪藏页面的时候，我总是习惯先选择知识库，比方说我先选择 Software 知识库；
> 3. 然后我再改变剪藏方式，不管点击何种剪藏方式，下面的知识库都会变回默认的 Develop 知识库。
> 
> **预期行为**
> 
> 我在选择剪藏方式的时候，下面的知识库理应保持我选择好的 Software 知识库。
> 
> **请填写以下信息**
> 
> * 笔记平台: Joplin
> * 浏览器: Firefox
> * 版本: 1.26.1

这个问题我似乎修过，确定是新版？ 试试看 1.27.0

**Comment by vagra** [comment]
版本，在 Web Clipper 设置界面的【更新日志】里看的话，是 1.26.1 ，在 Firefox 的【附加组件】那里看的话，是 1.25 。而且检查更新会说没有找到可用更新。然后我去 addons.mozilla.org ，好像找不到 Web Clipper 了。

**Comment by vagra** [comment]
不着急，不是啥大毛病，等上架了再更新就行了。
