### ISSUE TITLE
Cannot download web clipper iOS 14.2, chrome. They get a message that the dustup web clipper was download it and the next time I log on, it will be available. I only have yeah iPad Pro

### ISSUE THREAD

**Issue by drtalisman** [webclipper/web-clipper#581]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**please complete the following information**

- Notebook: [e.g. notion,yuque]
- Version [e.g. 1.23.0]

**Additional context**

**Comment by DiamondYuan** [comment]
I am so sorry, iOS don't support chrome extension.
