### ISSUE TITLE
notion，wolai Not work , [wolai notion 无法绑定]

### ISSUE THREAD

**Issue by fraloow** [webclipper/web-clipper#589]
**Bug 描述**

在进行绑定notion或wolai账户时总会无法成功绑定，弹出错误提示，我确定我处于登录状态，即使退出登录过也一样

**复现步骤**

重现的步骤：

1. 打开绑定账户
2. 点击按钮校验
3. 在notion看到错误授权失败，请登录网页版 Notion。
4. 在wolai看到错误Cannot destructure property 'blocks' of 'this.userContent.data' as it is undefined.

**预期行为**

可能是我绑定的方式不对或是我的浏览器设置有问题？
但绑定onenote以及为知笔记是可行的

**截图**

![image](https://user-images.githubusercontent.com/50948805/97299721-6263d880-1890-11eb-85a5-f5fd65c684bc.png)
![image](https://user-images.githubusercontent.com/50948805/97299744-6d1e6d80-1890-11eb-9d38-8fcbb5c1104d.png)

**请填写以下信息**

- 笔记平台: [notion,wolai]
- 浏览器 [chrome,]
- 版本 [e.g. 1.27.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by chengsluo** [comment]
无法绑定notion+1

**Comment by ZAJINYU** [comment]
+1,我来和notion都不行

**Comment by DiamondYuan** [comment]
@fraloow  @chengsluo @ZAJINYU 

1. Open  `chrome://settings/cookies`

2. Set Allow all cookie

打开 chrome 设置页面 ，选择允许全部 cookie

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases/tag/canary

试试看这个

**Comment by ZAJINYU** [comment]
> +1,我来和notion都不行

已解决，允许全部cookie后

**Comment by DiamondYuan** [comment]
> > +1,我来和notion都不行
> 
> 已解决，允许全部cookie后

上面那个不需要允许的全部 cookie
