### ISSUE TITLE
无法绑定onenote

### ISSUE THREAD

**Issue by love2wind** [webclipper/web-clipper#591]
**Bug 描述**

无法绑定

**复现步骤**

重现的步骤：

登录后出现错误提示
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: hnd1::vt84c-1604027850979-b61fc6c8b1c0

NOTE: webclipper-oauth.yfd.im might be available. Click here to learn how to assign it to a project.

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**
![image](https://user-images.githubusercontent.com/11996852/97656102-9bbf6280-1aa1-11eb-93cb-63ceb3a106eb.png)

**请填写以下信息**

- 笔记平台: [e.g. onenote]
- 浏览器 [e.g. edge]
- 版本 [e.g. 1.26.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/issues/592
