### ISSUE TITLE
语雀一键授权报错 404

### ISSUE THREAD

**Issue by jaychouwii** [webclipper/web-clipper#592]
**Bug 描述**
使用语雀一键授权时 点击确定授权后报错
![image](https://user-images.githubusercontent.com/27796731/97796771-35794200-1c51-11eb-97bc-e946a9bbe7d5.png)

**复现步骤**

重现的步骤：

1. 打开 '...'
2. 点击按钮 '....'
3. 滚动到 '....'
4. 看到错误

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: [e.g. notion,yuque]
- 浏览器 [e.g. chrome, safari]
- 版本 [e.g. 1.23.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
试试看清理 dns 缓存

**Comment by DiamondYuan** [comment]
## Clear DNS  Cache

https://www.wpbeginner.com/wp-tutorials/how-to-clear-your-dns-cache-mac-windows-chrome/

## 清理 dns 缓存

https://zhuanlan.zhihu.com/p/40206730

**Comment by jaychouwii** [comment]
已经可以绑定了，非常感谢，还有个问题请问下使用一键授权的话 图片会自动上传到语雀图床吗 ？需不需要其他设置

**Comment by DiamondYuan** [comment]
> 已经可以绑定了，非常感谢，还有个问题请问下使用一键授权的话 图片会自动上传到语雀图床吗 ？需不需要其他设置

会的，记得设置语雀的内置图床。
