### ISSUE TITLE
希望可以增加对Obsidian的支持

### ISSUE THREAD

**Issue by buzhangjiuzhou** [webclipper/web-clipper#595]
我正在寻找一个好用的笔记、知识管理软件，目前确定的是obsidian，所以希望可以使用网页快速剪贴。但是没有比较好的方案，这个web-clipper很好用，希望可以增加对obsidian的支持。

我看到了一个实现，但是感觉不是那么好用，所以我把他的链接放在这里。

[Until Obsidian supports adding new notes through their custom Obsidian:// URL protocol, this might be the best way.](https://github.com/Liamballin/ObsidianBookmark)

谢谢！

**Comment by DiamondYuan** [comment]
obsidian 没有接口，所以需要自己在本地启动一个服务。
但是我没有精力开发 web clipper 的桌面版本。

**Comment by buzhangjiuzhou** [comment]
大概有点明白了，感谢！我看看还有别的办法没有。

**Comment by DiamondYuan** [comment]
不要 close ，以后会做的

**Comment by akosbalasko** [comment]
Btw Obsidian provides git plugin to store and sync your notes in git. Therefore if you connect Web Clipper with git, then your highlights and clips will appear in git and in Obsidian instantly (after a git pull).

**Comment by ChitaGideon** [comment]
> obsidian 没有接口，所以需要自己在本地启动一个服务。 但是我没有精力开发 web clipper 的桌面版本。

这个问题一年了，目前obsidian 是有 protocal支持创建的，只是不知道符不符合你们要求：https://help.obsidian.md/Advanced+topics/Using+obsidian+URI

```
obsidian://new?vault=vaultName&content=a123123
```

**Comment by huyz** [comment]
Here's an existing (beta) third-party implementation which could help you get started modifying web-clipper: https://github.com/jplattel/obsidian-clipper

**Comment by Mlk1225** [comment]
Obsidian的这个插件（https://github.com/coddingtonbear/obsidian-local-rest-api）
可以提供一个api接口，配套浏览器插件**Obsidian Web**似乎可以实现剪切，但是没有这个插件那么好用。希望可以为你提供参考
（我也迫切希望这个插件可以支持obsidian

**Comment by huyz** [comment]
This is another third-party implementation of an Obsidian web clipper https://gist.github.com/kepano/90c05f162c37cf730abb8ff027987ca3

**Comment by eightHundreds** [comment]
> Obsidian的这个插件（[https://github.com/coddingtonbear/obsidian-local-rest-api）](https://github.com/coddingtonbear/obsidian-local-rest-api%EF%BC%89) 可以提供一个api接口，配套浏览器插件**Obsidian Web**似乎可以实现剪切，但是没有这个插件那么好用。希望可以为你提供参考 （我也迫切希望这个插件可以支持obsidian

已经提了，但是作者消失了，#1120

**Comment by Eyion** [comment]
mark并关注中...

**Comment by DiamondYuan** [comment]
try 1.38.0
