### ISSUE TITLE
网页剪藏到wolai会出现内容丢失。

### ISSUE THREAD

**Issue by yukaze18** [webclipper/web-clipper#607]
**Bug 描述**

网页剪藏到wolai会出现内容丢失。

**复现步骤**

任意网页都会如此。
举例：
https://mp.weixin.qq.com/s/0ybTt7vS32uNTZs29-SESg
上面得剪藏之后，结果是：
https://www.wolai.com/6Hbo34tHDx2pmptcsHPkhc
可以看到有大量的丢失

**请填写以下信息**

- 笔记平台: [wolai]
- 浏览器 [chrome]
- 版本 [86.0.4240.111（正式版本） （64 位）]

**Comment by yukaze18** [comment]
补充，剪藏方式用智能、手动或是整个网页都会丢失
剪藏到有道云笔记则正常

**Comment by DiamondYuan** [comment]
> 补充，剪藏方式用智能、手动或是整个网页都会丢失
> 剪藏到有道云笔记则正常

https://www.wolai.com/Z7RjTDziep9uVSwvuTsYg

我这边是正常的。

**Comment by DiamondYuan** [comment]
> 补充，剪藏方式用智能、手动或是整个网页都会丢失
> 剪藏到有道云笔记则正常

https://github.com/webclipper/web-clipper/releases/tag/canary

试试看这个

**Comment by yukaze18** [comment]
用canary，还是存在问题，试试这个页面在你那ok不。
https://www.gameres.com/876886.html
我的剪藏结果没有正文……
https://www.wolai.com/sGy1bzWQQmG7H9AgPqBz8S




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "webclipper/web-clipper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 凌晨0:44
收件人:&nbsp;"webclipper/web-clipper"<web-clipper@noreply.github.com&gt;;
抄送:&nbsp;"由风十八连斩"<yukaze18@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [webclipper/web-clipper] 网页剪藏到wolai会出现内容丢失。 (#607)





  
补充，剪藏方式用智能、手动或是整个网页都会丢失
 剪藏到有道云笔记则正常
  
https://github.com/webclipper/web-clipper/releases/tag/canary
 
试试看这个

**Comment by DiamondYuan** [comment]
> 用canary，还是存在问题，试试这个页面在你那ok不。 https://www.gameres.com/876886.html 我的剪藏结果没有正文…… https://www.wolai.com/sGy1bzWQQmG7H9AgPqBz8S
> […](#)

你搜搜看 canary 版本

**Comment by DiamondYuan** [comment]
wolai 修复了这个问题。
