### ISSUE TITLE
Cannot destructure property 'blocks' of 'this.userContent.data' as it is undefined.

### ISSUE THREAD

**Issue by systemime** [webclipper/web-clipper#614]
**Bug 描述**

![image](https://user-images.githubusercontent.com/30690006/99811955-ccfef000-2b80-11eb-8ab6-5aa4892b9686.png)

**复现步骤**

重现的步骤：

1. 添加账户
2. 选择wolai
3. 出现如图错误

**预期行为**

绑定wolai账户并剪藏

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: wolai
- 浏览器 chrome
- 版本 laster

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/issues/589
