### ISSUE TITLE
Firefox扩展卡在启动界面，无法使用

### ISSUE THREAD

**Issue by allblue** [webclipper/web-clipper#617]
**Bug 描述**

根据https://www.yuque.com/web-clipper/help_en/firefox_install 安装扩展后。
点击工具栏图标，卡死在启动界面，如截图。

**复现步骤**

重现的步骤：

1. 点击工具栏按钮即可复现

**预期行为**

启动界面停留1~2秒后自动跳过，开始网页剪辑操作。

**截图**

![图片](https://user-images.githubusercontent.com/844763/99935618-03648700-2d9c-11eb-94d3-fb9b0c8eb951.png)

**请填写以下信息**

- 笔记平台:  Notion、wolai、Joplin
- 浏览器: Firefox 80.x x64、Waterfox Current x64
- 版本 [1.27.0]

**其他背景**

Windows/Mac/Linux平台，Firefox及主流衍生版均可复现，

**Comment by DiamondYuan** [comment]
非常抱歉，试试看最新的 1.28.0

**Comment by allblue** [comment]
1.28.0版可正常使用，赞响应速度
