### ISSUE TITLE
转换成的Markdown粗体标记后没有加空格

### ISSUE THREAD

**Issue by liang-tian-yu** [webclipper/web-clipper#625]
**Bug 描述**
网页转换成的Markdown粗体标记后没有加空格，当遇到标记在一段汉字中间时，有道云笔记和浏览器都会显示成其后一段也加粗的情况

当前效果是这样

![FireShot Capture 008 - 高中地理小专题（一）：土壤盐碱化 - 知乎 - zhuanlan.zhihu.com.png](https://i.loli.net/2020/11/29/rWlXyTDnNiHJ4qp.png)

实际效果应该是这样

![FireShot Capture 011 - 高中地理小专题（一）：土壤盐碱化 - 知乎 - zhuanlan.zhihu.com.png](https://i.loli.net/2020/11/29/oLE7NBki8DSzwbC.png)

解决办法就是替换时在末尾的\*\*标记后加空格

- 笔记平台: [有道云笔记]
- 浏览器 [chrome]最新版
- 版本 [1.28.1]和[1.27.0]

**Comment by DiamondYuan** [comment]
> **Bug 描述**
> 网页转换成的Markdown粗体标记后没有加空格，当遇到标记在一段汉字中间时，有道云笔记和浏览器都会显示成其后一段也加粗的情况
> 
> 当前效果是这样
> 
> ![FireShot Capture 008 - 高中地理小专题（一）：土壤盐碱化 - 知乎 - zhuanlan.zhihu.com.png](https://camo.githubusercontent.com/e67196cc77e564d44ff60577bdd7136649b28018dcc123f2999ce97b8cc3eef9/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31312f32392f72576c587954446e4e69484a3471702e706e67)
> 
> 实际效果应该是这样
> 
> ![FireShot Capture 011 - 高中地理小专题（一）：土壤盐碱化 - 知乎 - zhuanlan.zhihu.com.png](https://camo.githubusercontent.com/a7400e1ac9e70d8ae9d297601d4ccf655231752e1ce461927ed4f0a387c8eca6/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31312f32392f6f4c45374e426b693844537a7762432e706e67)
> 
> 解决办法就是替换时在末尾的**标记后加空格
> 
> * 笔记平台: [有道云笔记]
> * 浏览器 [chrome]最新版
> * 版本 [1.28.1]和[1.27.0]

文章地址发一下

**Comment by liang-tian-yu** [comment]
[https://zhuanlan.zhihu.com/p/27626049](https://zhuanlan.zhihu.com/p/27626049)

[https://www.bilibili.com/read/cv8577745?from=category_17](https://www.bilibili.com/read/cv8577745?from=category_17)

[https://mp.weixin.qq.com/s?__biz=MzUzNjU4MjM1Nw==&mid=2247490062&idx=4&sn=cbdd502d5063c1dc4515d6916f1744ee&chksm=faf55bb4cd82d2a26b00213a665fac6850905f8f3d42811623e2cfaedf4dc04a83036a39381a&scene=21#wechat_redirect](https://mp.weixin.qq.com/s?__biz=MzUzNjU4MjM1Nw==&mid=2247490062&idx=4&sn=cbdd502d5063c1dc4515d6916f1744ee&chksm=faf55bb4cd82d2a26b00213a665fac6850905f8f3d42811623e2cfaedf4dc04a83036a39381a&scene=21#wechat_redirect)

[https://mp.weixin.qq.com/s?__biz=MzUzNjU4MjM1Nw==&mid=2247489930&idx=3&sn=8631cbd6d761d1c92d48acbfbdf386f1&chksm=faf55830cd82d126b941f4ffb492c6d1902781bae4862742c4a473a2814788e9837b4c8a574e&scene=21#wechat_redirect](https://mp.weixin.qq.com/s?__biz=MzUzNjU4MjM1Nw==&mid=2247489930&idx=3&sn=8631cbd6d761d1c92d48acbfbdf386f1&chksm=faf55830cd82d126b941f4ffb492c6d1902781bae4862742c4a473a2814788e9837b4c8a574e&scene=21#wechat_redirect)

[https://blog.csdn.net/Taobaojishu/article/details/110152497?utm_medium=distribute.pc_feed.none-task-blog-personrec_hot-20.nonecase&depth_1-utm_source=distribute.pc_feed.none-task-blog-personrec_hot-20.nonecase&request_id=5fc16e5b0693ff3392e5d75e](https://blog.csdn.net/Taobaojishu/article/details/110152497?utm_medium=distribute.pc_feed.none-task-blog-personrec_hot-20.nonecase&depth_1-utm_source=distribute.pc_feed.none-task-blog-personrec_hot-20.nonecase&request_id=5fc16e5b0693ff3392e5d75e)

真的很普遍

**Comment by DiamondYuan** [comment]
了解了，这周解决。

**Comment by DiamondYuan** [comment]
不好意思，空余时间太少了。

**Comment by liang-tian-yu** [comment]
没关系，我也高三了，我能理解

**Comment by DiamondYuan** [comment]
试试看 canary 版本。

预计会在 1.28.3 里带上。
