### ISSUE TITLE
Joplin 1.4.18 failing

### ISSUE THREAD

**Issue by fxshpac** [webclipper/web-clipper#626]
**Describe the bug**

The extension stopped working after I upgrade to version 1.4.18

**To Reproduce**

1. Go to any website
2. Click on web-clipper icon
3. Click Account then Bind Account
4. Choose Joplin as Type, copy/paste Authorization Token from Joplin, click Verify
4. See error screenshot attached

**Expected behavior**

No error should show and Joplin account should be added successfully.

**Screenshots**

<img width="444" alt="2020-11-28 19_24_23-姐妹们帮帮我，我老公的小三是个学心理学的。。。-第1页 and 9 more pages - Default - Microsoft​ Edge" src="https://user-images.githubusercontent.com/5333310/100532725-c3910b80-31b0-11eb-8bb6-29748556eb87.png">

**please complete the following information**

- Notebook: Joplin 1.4.18 (latest)
- Browser: Edge
- Version: 87.0.664.47 (latest)

**Additional context**

- The version of web-clipper is 1.28.0, latest on Edge
- Joplin was working with version 1.3.x

**Comment by DiamondYuan** [comment]
yes ,joplin change the api

**Comment by DiamondYuan** [comment]
try canary version.

will release in 1.28.3
