### ISSUE TITLE
github图床的配置能够提供范例？

### ISSUE THREAD

**Issue by acforu** [webclipper/web-clipper#631]
<img width="384" alt="Snipaste_2020-12-03_22-16-19" src="https://user-images.githubusercontent.com/3379984/101034206-5a950380-35b5-11eb-8f2a-e168a66c40c5.png">

仓库名称这里不知道该怎么填，试了一晚上都不行

**Comment by DiamondYuan** [comment]
非常不好意思，只能填的自己名下的仓库。 

如果我是 webclipper ,要保存的 的 GitHub 仓库地址是 https://github.com/webclipper/web-clipper ,那么 要填入的是 web-cliper

**Comment by DiamondYuan** [comment]
未来会做成下拉列吧，路径也会做成下拉列表。

**Comment by DiamondYuan** [comment]
1.18.0 上传错误的包，所以没完善就上传了 1.18.1

**Comment by acforu** [comment]
> 非常不好意思，只能填的自己名下的仓库。
> 
> 如果我是 webclipper ,要保存的 的 GitHub 仓库地址是 https://github.com/webclipper/web-clipper ,那么 要填入的是 web-cliper

我一直以为仓库地址后面要加.git

**Comment by DiamondYuan** [comment]
> > 非常不好意思，只能填的自己名下的仓库。
> > 如果我是 webclipper ,要保存的 的 GitHub 仓库地址是 https://github.com/webclipper/web-clipper ,那么 要填入的是 web-cliper
> 
> 我一直以为仓库地址后面要加.git. 另外用户名webclipper需要在哪里配置呢？

不需要配置，是从你 token 读取的。
比如你在你的账户下新增了一个叫做 hello 的话，那么你只需要填写 hello 就行了。

**Comment by acforu** [comment]
> > > 非常不好意思，只能填的自己名下的仓库。
> > > 如果我是 webclipper ,要保存的 的 GitHub 仓库地址是 https://github.com/webclipper/web-clipper ,那么 要填入的是 web-cliper
> > 
> > 
> > 我一直以为仓库地址后面要加.git. 另外用户名webclipper需要在哪里配置呢？
> 
> 不需要配置，是从你 token 读取的。
> 比如你在你的账户下新增了一个叫做 hello 的话，那么你只需要填写 hello 就行了。

那它是用的git下的那个分支呢？ master还是main？
我用github作为picgo的图床可以正常工作。 目前webclipper我主要是用于剪切到notion，想用github作为图床，这个是支持的把？

**Comment by DiamondYuan** [comment]
用的是默认分支。新仓库似乎是 main。


支持 notion。可能需要自己点一下上传按钮，或者开启自动上传。

**Comment by acforu** [comment]
> 用的是默认分支。新仓库似乎是 main。
> 
> 支持 notion。可能需要自己点一下上传按钮，或者开启自动上传。

没有找到上传按钮，也没看到自动上传的设置。。

**Comment by DiamondYuan** [comment]
扩展设置 / 上传图片

自动上传好像不支持，我记错了。（以后加一下

**Comment by acforu** [comment]
> 扩展设置 / 上传图片
> 
> 自动上传好像不支持，我记错了。（以后加一下

图片上传到了github上，但是notion里引用的图片还是网页自身的图片，不知是何原因

**Comment by DiamondYuan** [comment]
你关闭所见即所得模式，然后看一下图片链接有没有改。

**Comment by acforu** [comment]
> 你关闭所见即所得模式，然后看一下图片链接有没有改。

图片链接的确没改
