### ISSUE TITLE
在Edge Dev 的88.0.705.15版本里不能使用了

### ISSUE THREAD

**Issue by whimian** [webclipper/web-clipper#637]
**Bug 描述**

清楚简明地描述错误是什么。

**复现步骤**

重现的步骤：

1. 打开 '...'
2. 点击按钮 '....'
3. 滚动到 '....'
4. 看到错误

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: [e.g. notion,yuque]
- 浏览器 [e.g. chrome, safari]
- 版本 [e.g. 1.23.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
@whimian  邮箱私聊，我的邮箱在 GitHub profile 有写。
