### ISSUE TITLE
剪辑完成后无法在语雀知识库看到文章

### ISSUE THREAD

**Issue by diwenfan** [webclipper/web-clipper#640]
最近剪辑完成后可以在语雀中搜索到剪辑的文章，但是在知识库中却没有办法直接看到。不管是web端还是win客户端

**Comment by jakernel** [comment]
我也遇到了同样问题，剪藏的文章默认不在目录中显示了，需要编排目录手动添加到目录中。。

**Comment by Jinshijiming** [comment]
确实如此，今天刚用语雀就遇到这个问题了。

**Comment by Jinshijiming** [comment]
不知道是作者有意为之
还是一个BUG，

**Comment by DiamondYuan** [comment]
这个是 yuque 的设计。如果你手动修改过目录，那么新的文章就不会自动添加到知识库的目录中。

**Comment by DiamondYuan** [comment]
![6D6A93A2-E37A-4591-A099-62E264EDFB8E](https://user-images.githubusercontent.com/9692408/109107098-135d7f80-776c-11eb-8a29-c4991b46366c.jpeg)

可以把知识库设置为专栏。
