### ISSUE TITLE
win10上的edge（版本 87.0.664.60 (官方内部版本) (64 位)）无法弹出插件界面。卸载插件重装无效。

### ISSUE THREAD

**Issue by roverway** [webclipper/web-clipper#647]
**Bug 描述**

win10上的edge（版本 87.0.664.60 (官方内部版本) (64 位)）无法弹出插件界面。卸载插件重装无效。
win10商店有两人提及这个问题了。

清楚简明地描述错误是什么。

**复现步骤**

重现的步骤：

1. 打开 '...'
2. 点击按钮 '....'
3. 滚动到 '....'
4. 看到错误

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: [e.g. notion,yuque]
- 浏览器 [e.g. chrome, safari]
- 版本 [e.g. 1.23.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
Version 87.0.664.60 (Official build) (64-bit)


![image](https://user-images.githubusercontent.com/9692408/102106126-2a7a1a00-3e6b-11eb-828d-05009b33c143.png)

**Comment by DiamondYuan** [comment]
1.  打开控制台
![image](https://user-images.githubusercontent.com/9692408/102106269-52697d80-3e6b-11eb-946f-5bdec49ee849.png)

2.  点击 console

![image](https://user-images.githubusercontent.com/9692408/102106326-6319f380-3e6b-11eb-89d7-9210f2694ad7.png)


3. 点击 icon

**Comment by DiamondYuan** [comment]
要不把你的微信通过发给我，我私聊你解决。

**Comment by roverway** [comment]
按截图操作是这样的。最近的edge似乎是有问题，原先有个叫做tab session manager的扩展现在也不能用了（edge商店的不能用，chrome商店的可以），提示indexeddb不可用，不知道和你这个插件遇到的问题有没有关联。

这阵子比较忙，在准备考试，我先等等看浏览器版本升级后会不会好，不行的话再找时间配合你定位这个问题。
抱歉啊。

按你的截图操作结果是这样的：
![image](https://user-images.githubusercontent.com/657850/102305934-17b33280-3f9c-11eb-8672-15a3e8a5edb5.png)

**Comment by roverway** [comment]
卸载edge稳定版再重装之后问题好了，我觉得这个是edge的问题，不是插件的问题。
