### ISSUE TITLE
the support for  joplin is broken , i cant connect joplin. error :  (intermediate value).forEach is not a function

### ISSUE THREAD

**Issue by lin0kin** [webclipper/web-clipper#648]
**Bug**

hi,the support for  joplin is broken , i cant connect joplin.
when i try to add joplin account, it pop this message  “ (intermediate value).forEach is not a function ”
it happended on chrome and firefox

- 笔记平台: [joplin]
- 浏览器 [chrome 83 ,firefox]

**Comment by DiamondYuan** [comment]
you can try canary version

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases/tag/v1.28.3

**Comment by lin0kin** [comment]
> https://github.com/webclipper/web-clipper/releases/tag/v1.28.3

when i add account , it stuck on verifying

**Comment by DiamondYuan** [comment]
> > https://github.com/webclipper/web-clipper/releases/tag/v1.28.3
> 
> when i add account , it stuck on verifying



Sorry, I made a low-level mistake.

1.28.4 Solved the problem

**Comment by sslyxhz** [comment]
1.28.4 did not solve the problem on my computer.

Joplin 1.4.19 (prod, darwin)
Chrome 87.0.4280.88

<img src="https://user-images.githubusercontent.com/9070153/102339732-8f02b980-3fd0-11eb-8738-93f931f5dd0b.png" alt="something" width="400">

**Comment by lin0kin** [comment]
> > > https://github.com/webclipper/web-clipper/releases/tag/v1.28.3
> > 
> > 
> > when i add account , it stuck on verifying
> 
> Sorry, I made a low-level mistake.
> 
> 1.28.4 Solved the problem

oh man , it's worked . 
thx
