### ISSUE TITLE
希望github上传可以指定分支

### ISSUE THREAD

**Issue by heartAndRain** [webclipper/web-clipper#651]
**您的功能要求与问题有关吗？ 请描述。**
现在github图片上传不支持指定分支

**描述您想要的解决方案**

希望github图床上传可以指定分支，用默认分支的话会计入contribution小绿点里面

**描述您考虑过的替代方案**

no..
**其他内容**

**Comment by DiamondYuan** [comment]
在做了。

**Comment by DiamondYuan** [comment]
图片已经支持。下载最新版本，
