### ISSUE TITLE
markdown导出能否直接为md格式

### ISSUE THREAD

**Issue by abingx** [webclipper/web-clipper#660]
markdown导出能否直接为md格式，现在导出为txt格式，或者增加个选择

**Comment by DiamondYuan** [comment]
我试了一下，Mac 和 Windows 下导出的文档的后缀都是 .md 

请问有什么问题吗？

**Comment by DiamondYuan** [comment]
能否提供一下你的环境。

**Comment by abingx** [comment]
https://user-images.githubusercontent.com/31329925/103289417-18c77380-4a22-11eb-92f0-b5e772e4f8ce.MP4
windows 10，Edge。（电脑不在身边，手机远程录的）

**Comment by abingx** [comment]
已找到原因，FDM插件导致的，换IDM没有问题
