### ISSUE TITLE
web-clipper for Joplin: fill in the url note property

### ISSUE THREAD

**Issue by Del95** [webclipper/web-clipper#664]
**Is your feature request related to a problem? Please describe.**

I use the web-clipper for creating notes in Joplin. In Joplin, I am used to fill in the note properties with the url of the source web page. Unfortunately it seems that this url information in the note properties remains blank after creating notes with the web-clipper

**Describe the solution you'd like**

Similar to the information about the date of creation, the web-clipper could also fill in the url information in the note properties.

**Describe alternatives you've considered**

I know that there is the option to add the url at the end of the note, but for the sake of consistency with my older notes, I would appreciate if the web-clipper would also insert this information in the note properties.

**Additional context**

![image](https://user-images.githubusercontent.com/76838254/103437984-2ea98400-4c2e-11eb-93e1-ae9636dbeac3.png)

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/103554078-5415e680-4ee9-11eb-9f33-4ff763d08c24.png)

**Comment by DiamondYuan** [comment]
You can try canary version.
1.29.0 will include this change.

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases/tag/canary

**Comment by Del95** [comment]
Wow, thank you so much @DiamondYuan . I am new in Github, I didn't think it would go so fast.
