### ISSUE TITLE
对提取的代码块格式支持不友好

### ISSUE THREAD

**Issue by xiaoliangadmin** [webclipper/web-clipper#671]
使用web clipper提取网页内容到我来笔记，对代码块格式支持的不友好。主要就是换行符。

**Comment by DiamondYuan** [comment]
有具体的例子吗？

**Comment by DiamondYuan** [comment]
- issus 的描述太模糊，我先关闭了。如果有问题可以再次打开。
	- 如果某些网站的剪藏效果太差，请附带一下信息。
		- web clipper 的版本
		- 要剪藏的网站
		- 保存到哪一个平台

**Comment by zszoom** [comment]
相同的问题，如从知乎专栏clip，预览时都还好，保存到notion之后的代码段落没了，变成连成一块的代码

**Comment by ladychili** [comment]
> * issus 的描述太模糊，我先关闭了。如果有问题可以再次打开。
>   
>   * 如果某些网站的剪藏效果太差，请附带一下信息。
>     
>     * web clipper 的版本
>     * 要剪藏的网站
>     * 保存到哪一个平台

- web clipper版本：1.30.0
- 简藏网站：知乎
- 保存平台：Notion

主要问题是 **代码块换行失效** ，如下图

webclipper
![webclipper](https://user-images.githubusercontent.com/27876613/117411893-b0941b80-af46-11eb-8ad8-9b7ff0a4512a.png)

Notion官方clipper

![image](https://user-images.githubusercontent.com/27876613/117412357-4af45f00-af47-11eb-9c09-d49cee999d40.png)

原文链接：https://zhuanlan.zhihu.com/p/84397379
