### ISSUE TITLE
是否有、是否可以开发批量 URLs 自动剪藏功能或者 API ？

### ISSUE THREAD

**Issue by vagra** [webclipper/web-clipper#684]
**您的功能要求与问题有关吗？ 请描述。**

我是一个二十多年网龄的老鸟了，我收藏了大量的链接，分散在不同的平台，比方说，收藏夹、Snapbooks、知乎、Pocket、StackOverflow，它们大多只是一个链接，我可以导出这些链接，甚至还可以让每个链接带标签导出，但是我没法全自动地剪藏它们，于是它们的原文会随着岁月而慢慢消失。所以我迫切需要把它们批量地剪藏保存下来，最好带上标签。

我尝试了使用一些脚本，用 Python 控制 Cypress 之类，像按键精灵那样控制 chrome 来把这些链接带标签导入到 evernote ，但是它十分笨拙，大概每晚只能抓取两三百条。

而其它方案比方说通过 IFTT ，差不多都只是抓取个链接和几百字的摘要而已，我需要全文的抓取。

**描述您想要的解决方案**

Web Clipper 是个非常优秀的开源剪藏插件，它甚至远比 Joplin 自己的剪藏插件要优秀，我使用 Joplin CLI （node.js）作为后台服务来配合 Web-Clipper 工作。

所以，如果 Web Clipper 拥有导入 Urls 然后批量剪藏到 Joplin 的功能该多好啊，最好带上标签。
或者有这样的 API ，让我们可以用 Python 写脚本来批量导入也可以。

**Comment by DiamondYuan** [comment]
我觉得你需要的可能是 https://github.com/webclipper/readability

正文内容提取我用的是 fork 的 mozilla/readability
