### ISSUE TITLE
语雀知识库太多，能否自定义不显示某些团队或知识库？

### ISSUE THREAD

**Issue by arvinxx** [webclipper/web-clipper#689]
**您的功能要求与问题有关吗？ 请描述。**

目前我的语雀中包含好多团队，其中有些是工作需要添加的，而在剪藏的时候是不需要这些团队的。一旦显示之后找知识库会花超多时间，导致我现在主要用搜索…

**描述您想要的解决方案**

1. 允许用户设置过滤某些团队；
2. 在设计上优化，默认显示最近修改的 5 个知识库，团队信息打 tag。

**描述您考虑过的替代方案**

优化搜索能力也可以，比如支持拼音分词搜索（这一块可以直接用语雀的搜索 API，是可以实现 拼音分词搜索的）

**其他内容**

**Comment by DiamondYuan** [comment]
剪藏支持只显示自己的知识库

**Comment by xieshengyong** [comment]
现在语雀不支持显示团队知识库了吗，为什么
