### ISSUE TITLE
不能指定为知笔记的端口号

### ISSUE THREAD

**Issue by chuanzz** [webclipper/web-clipper#690]
很多为知笔记的用户会用这个插件应该都是自建后台的吧
虽然说也有办法绕过这个问题，反向代理为80端口，但插件上也没必要限制端口吧
希望能解决

**Comment by DiamondYuan** [comment]
可以的。 origin 直接输入带端口的地址。

如果还是不行，可以创建一个测试账户，然后通过邮箱发给我，我来验证一下。

**Comment by DiamondYuan** [comment]
有问题可以继续打开。

**Comment by chuanzz** [comment]
用ip地址的时候不能指定。
而且ip地址的时候逻辑有点反人类，自动变成类似于0.0.0.1的格式，然后非常难以正常输入，不如全部输入完了再检查ip格式会好点。
我怀疑这个ip的端口号问题也是跟这个格式的要求有关。

**Comment by edwinhuish** [comment]
无法输入端口号，无法输入冒号

**Comment by wellgone** [comment]
没修复这个问题之前，可以通过 先输入端口号 再打冒号 来解决。
