### ISSUE TITLE
图标颜色的选择

### ISSUE THREAD

**Issue by Sostay** [webclipper/web-clipper#694]
暗色的浏览器主题下 图标几乎都看不见了 希望能自适应浏览器暗色主题 或者增加一个设置图标颜色的选项
![image](https://user-images.githubusercontent.com/6897274/105574607-ad628e80-5da0-11eb-9482-fa28cf573fb5.png)

**Comment by DiamondYuan** [comment]
## 临时解决方案

打开设置页面，为 web clipper 设置一个快捷键把。

chrome://extensions/shortcuts

**Comment by Sostay** [comment]
我用的另外一个扩展也有这个问题 前段时间增加了这个选项进去

**Comment by DiamondYuan** [comment]
1.31 支持
