### ISSUE TITLE
“我来”账户无法绑定

### ISSUE THREAD

**Issue by Zurich1994** [webclipper/web-clipper#696]
**Bug 描述**

清楚简明地描述错误是什么。
![image](https://user-images.githubusercontent.com/21177723/105623929-967f7300-5e58-11eb-9afd-3bbe943e77c8.png)

**复现步骤**
正常的绑定步骤，报错，
重现的步骤：

打开绑定账户
点击按钮校验
在notion看到错误授权失败，请登录网页版 Notion。
在wolai看到错误Cannot destructure property 'blocks' of 'this.userContent.data' as it is undefined.

**预期行为**

今天突然无法剪辑，我重新绑定wolai账户，发现绑定失败。
![image](https://user-images.githubusercontent.com/21177723/105623960-ececb180-5e58-11eb-8f5a-2fe80bb3c178.png)

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

笔记平台: [wolai]
浏览器 [chrome,]
版本 [1.28.4，1.28.952]都试过
问题#589 和#614的方法不管用。尝试过了

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
请确认是否登陆了网页版的 wolai。

**Comment by DiamondYuan** [comment]
实在不行可以加钉钉群联系我。

**Comment by DiamondYuan** [comment]
先关了，有问题可以再次打开。
