### ISSUE TITLE
突然无法连接到 Notion 

### ISSUE THREAD

**Issue by Doeye1997** [webclipper/web-clipper#702]
之前正常，今天使用突然变成
Request failed with status code 415

**Comment by DiamondYuan** [comment]
notion 的改动，需要 web clipper 发新版本。

**Comment by CareLaden** [comment]
我这里也是

**Comment by DiamondYuan** [comment]
今天晚上会发布 canary 版本

**Comment by bobyyoung** [comment]
我的也是415了

**Comment by DiamondYuan** [comment]
@bobyyoung @CareLaden @Doeye1997 @PascalNoisette 

https://github.com/webclipper/web-clipper/releases/tag/v1.29.0

**Comment by Heisenberglue** [comment]
notion 官方的剪藏插件差劲爆了，国内不少网站根本贴不过去，去 notion 里查看剪藏结果发现只有一个网页链接。
