### ISSUE TITLE
Notion failed with 415 

### ISSUE THREAD

**Issue by XuShenLZ** [webclipper/web-clipper#704]
**Bug 描述**

之前已经连接Notion帐户，今日发现无法剪藏。重新绑定帐户时，点击“校验”，出现“Request failed with status code 415”提示。

已经同时登录网页版Notion。

**复现步骤**

重现的步骤：

1. 打开 '设置-帐户'，并选择Notion
2. 点击按钮 '校验'
3. 看到错误

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/31999415/106036831-a7afc600-608a-11eb-851a-6f900c4f47b9.png)

**请填写以下信息**

- 笔记平台: Notion
- 浏览器 Edge
- 版本 88.0.705.53

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/issues/702

**Comment by DiamondYuan** [comment]
已经修复了，商店审核中。
