### ISSUE TITLE
轻量抓取网页中的选中内容，并直接保存到默认知识库中

### ISSUE THREAD

**Issue by arvinxx** [webclipper/web-clipper#707]
## **您的功能要求与问题有关吗？ 请描述。**

目前剪藏具有较好的全文抓取能力，也选择提取部分内容的能力。但是针对较为零碎的内容并没有比较流畅的提取路径。

当我们看到某些内容给到自己灵感时，特别希望摘取其中的部分内容，而不是整篇文章。

因此，快速摘录下给自己灵感的 idea、文章、句子或内容，这样可以更好的记录下那些想法和源头。

## **描述您想要的解决方案**

类似 Web 端的 OmniFocus Inbox

![image](https://user-images.githubusercontent.com/28616219/106143474-c6f34400-61ad-11eb-9ac0-f9cd0ed34472.png)

![image](https://user-images.githubusercontent.com/28616219/106143491-cce92500-61ad-11eb-981e-f31ff8999340.png)

操作路径：
1. 选中文本，右键菜单栏中显示 `直接添加到XXX`（例如添加到语雀），同时应允许用户配置相应的快捷键；
2. 激活后弹出一个小窗口，窗口界面类似上图，包含摘录文本内容、URL、以及一个评论输入区。（即允许用户快速写下自己的想法）

保存到云端知识库的文章结构建议如下：
```
标题：网页标题

文章内容结构：

来源 URL： https://baidu.com

## 摘录内容
>  选中的文本信息

## 个人想法
```

## 举个例子：

标题： CSS Utility Classes and "Separation of Concerns"
-----
来源 URL ： https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

### 摘录内容
> If you're using Less as your preprocessor, you can use existing classes as mixins. That means that creating this .btn-purple component takes only a bit of multi-cursor wizardry in your editor:

> ![](https://user-images.githubusercontent.com/4323180/29084097-f16c97c6-7c38-11e7-92dd-d20c1364d869.gif)

> Unfortunately you can't do this in Sass or Stylus without creating a separate mixin for every utility class, so it's a bit more work there.

### 想法
less 直接能把 class 当成原子类来用，这个能力是将样式工程化上非常有意义的一个特性。
在一个设计系统中 design-token 是最底层的原子， 原子类将 token 组合成一个个原子类，原子类又可以复合成组件样式。
这样其实能解决 tailwindcss 被喷成 class 太长的问题。

语雀上的样例：[CSS Utility Classes and "Separation of Concerns"](https://www.yuque.com/arvinxx-fe/css/qolcro)

**Comment by DiamondYuan** [comment]
release in 1.30.0
