### ISSUE TITLE
火狐浏览器如何安装此插件？

### ISSUE THREAD

**Issue by letmesayok** [webclipper/web-clipper#712]
我下载了 web_clipper_firefox 后在从本地文件导入插件，提示已阻止安装未信任的插件，百度解决措施都是修改xpinstall.signatures.required = false，尝试后无效，特来求助！

**Comment by DiamondYuan** [comment]
https://addons.mozilla.org/en-US/firefox/addon/universal-web-clipper/

**Comment by DiamondYuan** [comment]
https://www.yuque.com/web-clipper/help_cn/firefox_install
