### ISSUE TITLE
notion剪藏，原url不能自动放到URL tag上

### ISSUE THREAD

**Issue by mizeng** [webclipper/web-clipper#726]
如题，以前用chrome的Notion官方插件，可以自动把剪藏的URL放到tag上。
![Screen Shot 2021-02-22 at 5 49 01 PM](https://user-images.githubusercontent.com/8059086/108691264-49192300-7536-11eb-8f75-f9188d5e682a.png)

但是咱这个好像不行，我找了半天配置也没看到，只能放到文章末尾？
![Screen Shot 2021-02-22 at 5 49 58 PM](https://user-images.githubusercontent.com/8059086/108691371-65b55b00-7536-11eb-88de-71f97aafddc1.png)

**Comment by DiamondYuan** [comment]
duplicate of https://github.com/webclipper/web-clipper/issues/802

重复我先关了。可以关注新的 issue
