### ISSUE TITLE
在笔记中保存图片源文件而非图片url

### ISSUE THREAD

**Issue by allblue** [webclipper/web-clipper#731]
**您的功能要求与问题有关吗？ 请描述。**

当前的网页剪辑模式，保存的是图片原始url，如果原贴删除/网站关闭/防盗链时，图片就无法正常显示。
另一方面，为知/有道之类的云笔记，都支持将图片源文件和笔记一起保存在云上，即不受原网站影响。

**描述您想要的解决方案**
增加一个图片下载功能，可自动下载源文件，替换笔记中的原始图片url

**描述您考虑过的替代方案**

图片较少时，还可手动替换下，图片多时，只能望洋兴叹。
或者是否可将云笔记配置为图床？

**其他内容**

不确定各家笔记接口是否支持这样操作

**Comment by DiamondYuan** [comment]
> **您的功能要求与问题有关吗？ 请描述。**
> 
> 当前的网页剪辑模式，保存的是图片原始url，如果原贴删除/网站关闭/防盗链时，图片就无法正常显示。
> 另一方面，为知/有道之类的云笔记，都支持将图片源文件和笔记一起保存在云上，即不受原网站影响。
> 
> **描述您想要的解决方案**
> 增加一个图片下载功能，可自动下载源文件，替换笔记中的原始图片url
> 
> **描述您考虑过的替代方案**
> 
> 图片较少时，还可手动替换下，图片多时，只能望洋兴叹。
> 或者是否可将云笔记配置为图床？
> 
> **其他内容**
> 
> 不确定各家笔记接口是否支持这样操作

语雀支持的。

**Comment by DiamondYuan** [comment]
试试看 语雀 ？

**Comment by DiamondYuan** [comment]
这个是一开始就设计好的，你可以在在图床页面设置 GitHub 图床，把图片保存到 GitHub 。（GitHub 可能有防盗链

未来会支持 aliyun 。

**Comment by DiamondYuan** [comment]
我先关啦～有问题可以继续打开。

**Comment by allblue** [comment]
> 
> 
> > **您的功能要求与问题有关吗？ 请描述。**
> > 当前的网页剪辑模式，保存的是图片原始url，如果原贴删除/网站关闭/防盗链时，图片就无法正常显示。
> > 另一方面，为知/有道之类的云笔记，都支持将图片源文件和笔记一起保存在云上，即不受原网站影响。
> > **描述您想要的解决方案**
> > 增加一个图片下载功能，可自动下载源文件，替换笔记中的原始图片url
> > **描述您考虑过的替代方案**
> > 图片较少时，还可手动替换下，图片多时，只能望洋兴叹。
> > 或者是否可将云笔记配置为图床？
> > **其他内容**
> > 不确定各家笔记接口是否支持这样操作
> 
> 语雀支持的。

我用的为知，只能保存图片url。
换joplin，就可以保存源图片。
能把为知的保存机制改进下吗？

**Comment by zhoujiealex** [comment]
> 这个是一开始就设计好的，你可以在在图床页面设置 GitHub 图床，把图片保存到 GitHub 。（GitHub 可能有防盗链
> 
> 未来会支持 aliyun 。

github图床 就是有防盗链， 我把文章 上传了语雀， 图床选择 github。  
会遇到 无法 加载图片的问题。
