### ISSUE TITLE
Request failed with status code 415

### ISSUE THREAD

**Issue by laball** [webclipper/web-clipper#733]
最近每次裁剪都遇到这个问题；
现象是接口 https://www.notion.so/api/v3/loadUserContent 415 了

{"errorId":"04ecd050-7b00-44e4-a63f-91a5d1701770","name":"UnsupportedMediaTypeError","message":"Incorrect content type."}

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/issues/704

商店下载最新版本 (1.29.0 以上
