### ISSUE TITLE
[功能建议]Notion支持模板、URL、Tag等

### ISSUE THREAD

**Issue by hostage007** [webclipper/web-clipper#738]
关于Notion的支持
1. 希望可以支持模板
2. 希望可以在剪藏的时候直接把URL写在对应的字段上而不是文章结尾
3. 希望可以支持在剪藏的时候直接打Tag
感谢您的优秀作品，造福广大生产力洁癖者

**Comment by DiamondYuan** [comment]
duplicate of #802

重复我先关了。可以关注新的 issue
