### ISSUE TITLE
直接保存图片已上传图床的md文件到本地

### ISSUE THREAD

**Issue by kingone51** [webclipper/web-clipper#753]
**您的功能要求与问题有关吗？ 请描述。**

清楚，简洁地说明问题所在。 例如 当[...]时，我总是感到沮丧

**描述您想要的解决方案**

对您想要发生的事情的简洁明了的描述。

**描述您考虑过的替代方案**

对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**

在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by DiamondYuan** [comment]
1. 先点击上传图片
2. 点击保存 markdown

这样就行了
