### ISSUE TITLE
WebDAV not working

### ISSUE THREAD

**Issue by rocky-III** [webclipper/web-clipper#758]
Just discovers your nice and promising ff add-on - webclipper THANKS ... and it is suppose to work also with WebDAV too.   :-) 

I´m using a great- social network app called hubzilla 

https://hubzilla.org//page/hubzilla/hubzilla-project
https://framagit.org/hubzilla/core

and it works also with WebDAV very well 

https://hub.netzgemeinde.eu/help/de/member/member_guide#Personal_Cloud_Storage

but I could not connect by webclipper. 
I´m doing something wrong? 
Do you think it could work?
Thanks a lot

**Comment by ccw55ccw** [comment]
I also encountered the same problem
origin url to delete the path followed by the URL path, resulting in a 405 error

**Comment by apas008** [comment]
I ran the same problem

**Comment by IvanLi-CN** [comment]
I've submitted a PR that may fix this issue, test it if interested #1179.
