### ISSUE TITLE
chrome插件 绑定语雀无法选择知识库

### ISSUE THREAD

**Issue by lisansang** [webclipper/web-clipper#782]
**Bug 描述**

chrome插件 语雀正常授权，但是保存网页时知识库选择器显示‘暂无数据’。（语雀下有知识库）

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**

![image](https://user-images.githubusercontent.com/35590647/117535955-03df9a00-b02b-11eb-971c-a0e01e23ac95.png)

**请填写以下信息**

- 笔记平台: [yuque]
- 浏览器 [chrome]
- 版本 [e.g. 1.30.0]

**Comment by DiamondYuan** [comment]
你好，能否刷新页面再试一次看看，还是不行吗？

**Comment by lisansang** [comment]
具体原因未定位到，但是当我不使用一键授权，换为授权码手动授权的时候就可以了。 
另外，点赞这个插件 👍
