### ISSUE TITLE
被墙网站的图片无法正确上传

### ISSUE THREAD

**Issue by zz5678** [webclipper/web-clipper#809]
一个相关翻墙问题
web-clipper 上传的时候，是本地 chrome 上传，还是用目标笔记网站的图床 api 去拉图片？

我发现用语雀上传文章，如果**图片是被墙网站提供的**，就无法成功，最后在文章里都是嵌入的原始网站的 url 的图片，点击 web-clipper 的 「把文章内图片上传图床」按钮，也都是失败。设置全局代理，还是不行，看来是用的图床 api 去拉远程图片时遭遇了 wall ???
![image](https://user-images.githubusercontent.com/67672527/119289609-7f715600-bc7d-11eb-8721-06f8293c13ef.png)

是否可能从本地上传图片？

@web-clipper

**Comment by DiamondYuan** [comment]
网站地址发一下？

**Comment by zz5678** [comment]
> 网站地址发一下？

https://www.bcbay.com/news/2021/05/22/746732.html

**Comment by DiamondYuan** [comment]
试试看 1.31
