### ISSUE TITLE
生成Markdown文档显示有问题

### ISSUE THREAD

**Issue by BonjourL** [webclipper/web-clipper#820]
**Bug 描述**

csdn上面的文章智能提取生成Markdown文档后，排版有问题，代码块会把代码块下面的很多内容都包括进去
链接：https://blog.csdn.net/hello_cmy/article/details/104996007

**截图**
![image](https://user-images.githubusercontent.com/37428385/120413419-d3b9bb80-c38a-11eb-9059-ebacf1fef5cd.png)

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: [e.g. notion,yuque] mac
- 浏览器 [e.g. chrome, safari]   chrome 90
- 版本 [e.g. 1.23.0]   1.30

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
> **Bug 描述**
> 
> csdn上面的文章智能提取生成Markdown文档后，排版有问题，代码块会把代码块下面的很多内容都包括进去
> 链接：https://blog.csdn.net/hello_cmy/article/details/104996007
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/37428385/120413419-d3b9bb80-c38a-11eb-9059-ebacf1fef5cd.png)
> 
> 如果适用，请添加屏幕截图以帮助解释您的问题。
> 
> **请填写以下信息**
> 
> * 笔记平台: [e.g. notion,yuque] mac
> * 浏览器 [e.g. chrome, safari]   chrome 90
> * 版本 [e.g. 1.23.0]   1.30
> 
> **其他背景**
> 
> 在此处添加有关该问题的任何其他上下文。

你好，你发的链接是不是有问题。

**Comment by DiamondYuan** [comment]
链接点进去，搜不到 `动态表名` 这一段。

**Comment by DiamondYuan** [comment]
https://juejin.cn/post/6964009565683712036

这篇文章和 csdn 是一样的，我试了一下也没有复现。


先关闭了，还有问题的话可以重新打开。
