### ISSUE TITLE
【语雀】收藏文档到语雀后，通过语雀客户端无法打开文档，提示不支持老markdown

### ISSUE THREAD

**Issue by yi1991er** [webclipper/web-clipper#844]
![image](https://user-images.githubusercontent.com/30147020/122500802-0bc92b80-d026-11eb-939e-161623fbc148.png)

**Comment by yi1991er** [comment]
看到了之前有同学反馈过

**Comment by DiamondYuan** [comment]
这个是yuque自己的问题
