### ISSUE TITLE
保存到本地 TiddlyWiki

### ISSUE THREAD

**Issue by linonetwo** [webclipper/web-clipper#845]
**您的功能要求与问题有关吗？ 请描述。**

我想要一个 TiddlyWiki 的剪藏插件，剪藏后调用本地 NodeJS 版 TW 的 API 存储内容。这个有可能通过 web-clipper 的插件来实现吗？

或者我参考你的代码，做一个新的浏览器插件？我目前是打算做一个插件支持 TW 的搜索结果展示 https://github.com/webclipper/web-clipper/issues/685#issuecomment-760610452 ，看是用 web-clipper 插件还是基于这个改改。

**描述您想要的解决方案**

或许可以通过一个插件，填入本地 nodejs tw 的端口即可。然后保存时调用新增 tiddler 的接口。

**描述您考虑过的替代方案**

做一个全新的插件，复制黏贴这里剪藏相关的代码，简化 TW 用不到的功能。

**Comment by DiamondYuan** [comment]
## 1. web clipper 支持 tiddly wiki

这个很简单，只需要新增一个文件夹，然后实现三个接口。

https://github.com/webclipper/web-clipper/pull/762

对接方法可以看上面


## 2. 搜索结果展示

web clipper 准备在搜索引擎里嵌入各个平台的搜索结果，不过最近没时间搞。

**Comment by DiamondYuan** [comment]
上面两个需求都欢迎 MR ，第一个简单一点，第二个会麻烦一点。如果要讨论的话，可以发微信号到我的邮箱，我加你微信。

telegram 也可以

**Comment by linonetwo** [comment]
保存到 TW 需要能填一些配置项，例如 tiddler 加上什么标签（例如加上 private 就可以利用 fileSystemPath 机制自动保存到一个私有的 tw 仓库里），我一般默认填 APrivateContent ，所以这个配置项需要能记住并每次自动填写。

类似于这个表单项，这是放在 form.tsx  里吗？

![截屏2021-06-21 下午8 15 16](https://user-images.githubusercontent.com/3746270/122760173-67691280-d2cd-11eb-90dd-fffffcf89ffc.png)

还有为了防止图片失效我可能需要把图片也存成 tiddler ，即把 tw 当成图床，我在哪一步里可以拿到图片列表信息呢？

还有剪藏的结果是 HTML 吗，对于 HTML 如何引用其他图片 tiddler，我还没想好。或许我得保存下 markdown 版本（或者 tid 版本，不过估计没有好的 HTML2tid 转换器，只有 HTML2MD 转换器）的剪藏内容，才好引用别的图片，那我能拿到 md 版本的剪藏内容吗？

**Comment by DiamondYuan** [comment]
> ### 保存到 TW 需要能填一些配置项，例如 tiddler 加上什么标签（例如加上 private 就可以利用 fileSystemPath 机制自动保存到一个私有的 tw 仓库里），我一般默认填 APrivateContent ，所以这个配置项需要能记住并每次自动填写。
> 类似于这个表单项，这是放在 form.tsx 里吗？
> 
> ![截屏2021-06-21 下午8 15 16](https://user-images.githubusercontent.com/3746270/122760173-67691280-d2cd-11eb-90dd-fffffcf89ffc.png)
> 
> ### 还有为了防止图片失效我可能需要把图片也存成 tiddler ，即把 tw 当成图床，我在哪一步里可以拿到图片列表信息呢？
> ### 还有剪藏的结果是 HTML 吗，还是说可以获得 MD 版本？
> 对于 HTML 如何引用其他图片 tiddler，我还没想好 [https://github.com/Jermolene/TiddlyWiki5/discussions/5814。](https://github.com/Jermolene/TiddlyWiki5/discussions/5814%E3%80%82)
> 或许我得保存下 markdown 版本的剪藏内容（或者 tid 版本，不过估计没有好的 HTML2tid 转换器，只有 HTML2MD 转换器），才好引用保存下来的图片。
> 
> 我们就github上讨论吧，讨论结果还能被搜索引擎抓取到。我平时飞书和QQ用得多，微信和 tg 都不咋打开了，还不如就 Github 上聊啦。

1.   保存图片可以看这个、builtIn 代表内置图床，只能给对应的笔记用。
src/common/backend/imageHosting/joplin/index.ts

点击上传按钮，会自动上传全部图片。

2.  统一的表单配置，可以看 `src/common/backend/services/ticktick/form.tsx`

3. 每次剪藏的配置，可以看 `src/common/backend/services/yuque/headerForm.tsx`

**Comment by DiamondYuan** [comment]
createDocument 的 info.content 参数就是最终的 html，你可以用正则来找出全部的图片。


可以用 remark 把 content 从 markdown 转成 html

**Comment by linonetwo** [comment]
tw 需要发请求到 localhost:xxx 端口按用户配置来，这个能实现吗？

```
    permission: {
      origins: ['http://localhost/*'],
    },
```

会不会对端口号有限制？

**Comment by linonetwo** [comment]
还有这个怎么给外国人用呀，在哪里添加 react-i18next 之类的字段呢？

**Comment by linonetwo** [comment]
对于多文件版 （NodeJS 版、太记）请使用 https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector

最后还是自己开发了！因为我还想加入很多功能，比如直接在地址栏搜索，在网页上展示双链等等功能，所以必须要写个自己的插件啦，谢谢之前的支持。
