### ISSUE TITLE
Joplin 2.1.7 更新API

### ISSUE THREAD

**Issue by Felix2yu** [webclipper/web-clipper#854]
**Bug 描述**

更新至Joplin 2.1.7后无法剪裁，提示http error。[Joplin更新日志](https://github.com/laurent22/joplin/releases/tag/v2.1.7)中也提到老clipper不兼容。

**复现步骤**

重现的步骤：

1. 打开 '...'
2. 点击按钮 '....'
3. 滚动到 '....'
4. 看到错误

**预期行为**

对您期望发生的事情的简洁明了的描述。

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: [e.g. notion,yuque]
- 浏览器 [e.g. chrome, safari]
- 版本 [e.g. 1.23.0]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
> **Bug 描述**
> 
> 更新至Joplin 2.1.7后无法剪裁，提示http error。[Joplin更新日志](https://github.com/laurent22/joplin/releases/tag/v2.1.7)中也提到老clipper不兼容。
> 
> **复现步骤**
> 
> 重现的步骤：
> 
> 1. 打开 '...'
> 2. 点击按钮 '....'
> 3. 滚动到 '....'
> 4. 看到错误
> 
> **预期行为**
> 
> 对您期望发生的事情的简洁明了的描述。
> 
> **截图**
> 
> 如果适用，请添加屏幕截图以帮助解释您的问题。
> 
> **请填写以下信息**
> 
> * 笔记平台: [e.g. notion,yuque]
> * 浏览器 [e.g. chrome, safari]
> * 版本 [e.g. 1.23.0]
> 
> **其他背景**
> 
> 在此处添加有关该问题的任何其他上下文。

我试了一下，功能一切正常。

**Comment by DiamondYuan** [comment]
<img width="341" alt="CleanShot 2021-06-30 at 00 27 05@2x" src="https://user-images.githubusercontent.com/9692408/123834342-ea2b4680-d939-11eb-8aca-8aac97e1e214.png">

**Comment by DiamondYuan** [comment]
重新绑定一下试试看？

**Comment by Felix2yu** [comment]
重新绑就好了，谢谢。
