### ISSUE TITLE
建议同一类型笔记本可以设置多个帐户

### ISSUE THREAD

**Issue by allblue** [webclipper/web-clipper#861]
我在windows和linux双系统下都安装了firefox、joplin，但不同系统下joplin的令牌是不一样的，而firefox同步会自动将webclipper的配置同步，导致每次系统切换时都要删掉之前的配置重建。
希望可以为joplin配置多个帐户，比如windows一个，linux下一个，然后每次更换下默认帐户就可以方便切换了

**Comment by DiamondYuan** [comment]
可以试试看 v1.31.0-alpha.1

**Comment by DiamondYuan** [comment]
更理想的方式是绑定多个 token，方便切换。

**Comment by DiamondYuan** [comment]
有问题可以再次打开
