### ISSUE TITLE
语雀剪藏，代码块有问题（只显示一行）

### ISSUE THREAD

**Issue by xsblooo** [webclipper/web-clipper#862]
剪藏链接为：
https://mp.weixin.qq.com/s?__biz=MzI5MDU1NDk2MA==&mid=2247498027&idx=1&sn=6800b032fb7d44edf98b8a95187a3d73&chksm=ec1cac14db6b25022aecbca4b54b9e76f8c5de9a448d0fcc4f36b7ef45daaa25b32829c24b6b&mpshare=1&scene=1&srcid=0705wiugytlqGGwTNXkOLbDg&sharer_sharetime=1625461719842&sharer_shareid=281a1f9b75644e2eb48c1428a30cf0a9#rd

<img width="614" alt="image" src="https://user-images.githubusercontent.com/67937785/124441514-554ba180-ddae-11eb-90d2-88e660c25fa1.png">

**Comment by DiamondYuan** [comment]
试试看 1.31.0-alpha.2

**Comment by DiamondYuan** [comment]
欢迎提交代码块的转换逻辑 https://github.com/webclipper/ecosystem/commit/fd226b673d2691338bba92dd820444808a7afeaa

**Comment by CNAHYZ** [comment]
> 试试看 1.31.0-alpha.2

使用了这个版本，还是有问题
![image](https://user-images.githubusercontent.com/33870926/134152399-6b96dbec-f7a9-4dec-b204-5af85cbfb5e9.png)
[https://mp.weixin.qq.com/s/Mh7ltwytt5K0yeqjbQJi_w](url)
