### ISSUE TITLE
Manual selection add more

### ISSUE THREAD

**Issue by remydev** [webclipper/web-clipper#866]
When I use the Manual selection tool

I have only 2 choice, do it again, or save the selection

I wish have the option "add more"

So i can go again to the Manual selection and add a new zone from the DOM before i save it

Thanks

**Comment by DiamondYuan** [comment]
> When I use the Manual selection tool
> 
> I have only 2 choice, do it again, or save the selection
> 
> I wish have the option "add more"
> 
> So i can go again to the Manual selection and add a new zone from the DOM before i save it
> 
> Thanks

![CleanShot 2021-07-12 at 23 48 48@2x](https://user-images.githubusercontent.com/9692408/125317718-ce796480-e36b-11eb-8c5f-fcae41e8e0d4.png)

**Comment by DiamondYuan** [comment]
you can click this to add more
