### ISSUE TITLE
还请更新Joplin的API，老版本已无法使用

### ISSUE THREAD

**Issue by mapleshadow** [webclipper/web-clipper#867]
RT，新版本的Joplin已经更新了API的调用方式，有个什么授权机制，还请更新API调用方法，不然老版本的插件均无法使用Joplin了

**Comment by DiamondYuan** [comment]
> RT，新版本的Joplin已经更新了API的调用方式，有个什么授权机制，还请更新API调用方法，不然老版本的插件均无法使用Joplin了

重新绑定一下试试看？

**Comment by caitlingao** [comment]
> > RT，新版本的Joplin已经更新了API的调用方式，有个什么授权机制，还请更新API调用方法，不然老版本的插件均无法使用Joplin了
> 
> 重新绑定一下试试看？

重新绑定了也不行，还是无法使用

**Comment by DiamondYuan** [comment]
> > > RT，新版本的Joplin已经更新了API的调用方式，有个什么授权机制，还请更新API调用方法，不然老版本的插件均无法使用Joplin了
> > 
> > 
> > 重新绑定一下试试看？
> 
> 重新绑定了也不行，还是无法使用

我从官网下载了最新的 Joplin 2.1.9 (prod, darwin) ，还是可以，请问你用的是什么版本

**Comment by caitlingao** [comment]
> > > > RT，新版本的Joplin已经更新了API的调用方式，有个什么授权机制，还请更新API调用方法，不然老版本的插件均无法使用Joplin了
> > > 
> > > 
> > > 重新绑定一下试试看？
> > 
> > 
> > 重新绑定了也不行，还是无法使用
> 
> 我从官网下载了最新的 Joplin 2.1.9 (prod, darwin) ，还是可以，请问你用的是什么版本

我又从官网重新下了最新的版本，可以了，应该是我的问题，抱歉抱歉

**Comment by DiamondYuan** [comment]
我试了一下没问题，有问题可以重新 open
