### ISSUE TITLE
1.31 firefox版闪退

### ISSUE THREAD

**Issue by allblue** [webclipper/web-clipper#870]
**Bug 描述**

点击运行出现下面这个界面，然后约3秒后自动关闭，无后续弹窗。
![图片](https://user-images.githubusercontent.com/844763/126038183-3920fa94-b475-43ac-9063-5fcef50ebb3e.png)

**复现步骤**

见描述

**预期行为**

与1.30版操作流程一致。

**截图**

见描述

**请填写以下信息**

- 笔记平台: joplin
- 浏览器 firefox 
- 版本 x64 90

**其他背景**

alpha0、alpha1、alpha.2均为同样问题

**Comment by DiamondYuan** [comment]
try alpha 5
