### ISSUE TITLE
语雀剪藏不会在目录中显示

### ISSUE THREAD

**Issue by uangunai** [webclipper/web-clipper#871]
![image](https://user-images.githubusercontent.com/18063251/126053936-e830faa4-43d2-44fe-adc4-8ab272cd063f.png)

利用插件剪藏，不填写路径的情况下，剪藏成功无法在目录中看到具体的目录列表。多次测试均是如此。只有对该剪藏的内容进行编辑——随意增删改内容，再更新发布才会显示。

**Comment by uangunai** [comment]
经测试，是剪藏的文章不会自动添加进目录，需要进入编排目录的页面进行手动添加，希望能完善下。
![image](https://user-images.githubusercontent.com/18063251/126054063-f7f3cb0e-5cf0-4075-909f-c806e00390ab.png)

**Comment by DiamondYuan** [comment]
和这个重复 https://github.com/webclipper/web-clipper/issues/517
