### ISSUE TITLE
暗主题下图标看不清

### ISSUE THREAD

**Issue by maboloshi** [webclipper/web-clipper#877]
如图，显示器上更看不清
<img width="202" alt="微信截图_20210726105343" src="https://user-images.githubusercontent.com/7850715/126926784-c82fe769-03bd-4ef8-a4a3-3dc6a5cb8977.png">

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/127001506-ba36cbff-c095-42e6-910d-3d35e9919539.png)
