### ISSUE TITLE
语雀剪藏英文单引号双引号标点格式为中文标点

### ISSUE THREAD

**Issue by pickalexrener** [webclipper/web-clipper#878]
**Bug 描述**

语雀剪藏英文，插件内预览时单双引号是正常英文格式，但在语雀文档中打开是中文标点格式。测试过notion、onenote，均正常显示。

**复现步骤**

文章链接：https://www.theverge.com/22590708/trans-youth-gender-affirming-healthcare-bans-science

**截图**

插件内预览正常
![4](https://user-images.githubusercontent.com/51726771/127744165-430c01ab-38d2-4b46-b827-917bfd39bd7e.png)

以下为语雀
![1](https://user-images.githubusercontent.com/51726771/127744116-0b12cacc-92f6-4f88-805b-e2dc843336a0.png)

以下为notion
![2](https://user-images.githubusercontent.com/51726771/127744113-f25b67d3-9b54-4d90-8916-b4dc6407d031.png)

以下为onenote
![3](https://user-images.githubusercontent.com/51726771/127744111-219a9dcc-d933-4e12-be03-601204ed0bda.png)

**请填写以下信息**

- 笔记平台: [yuque]
- 浏览器 [chrome]
- 版本 [1.30.0]

**Comment by DiamondYuan** [comment]
原文本身就是中文标点。

**Comment by DiamondYuan** [comment]
[`"`]===[`"`]


可以把这段代码复制到控制台，如果显示 trule 就说明符号相同。

**Comment by DiamondYuan** [comment]
```
`"`.charCodeAt(0) === 8220
`“`.charCodeAt(0) === 34
```
