### ISSUE TITLE
leanote上传笔记时携带图片数据

### ISSUE THREAD

**Issue by hyfree** [webclipper/web-clipper#881]
**您的功能要求与问题有关吗？ 请描述。**

如果原网站防盗链或者图片删除后，保存的笔记中的图片会丢失。

**描述您想要的解决方案**

leanote(当然，其他笔记系统也一样)现在剪辑保存网页的时候，网页中的图片是源网站的图片URL。
我希望，支持上传网页剪辑内容携带图片数据。对于其他笔记系统，如果支持上传笔记笔记图片，应该一并上传图片，而不是储存在第三方图床。
因为第三方图床的安全性和便利性太让人失望。众多周知，github也经常因为网络原因不稳定。

**描述您考虑过的替代方案**

使用第三方图床🛏️

**关联问题**
#874
#857
#816
#813
#794
#755
#742
#633
#586
#422
#234

**Comment by DiamondYuan** [comment]
支持 leannote 图床的，绑定的时候选择内置图床即可。


（保存笔记之前，需要手动点击上传图片

**Comment by DiamondYuan** [comment]
有问题可以重新 open

**Comment by hyfree** [comment]
没有问题，请关闭这个issues
