### ISSUE TITLE
Repository目录 搜索文件夹时忽略大小写

### ISSUE THREAD

**Issue by hyfree** [webclipper/web-clipper#883]
**Is your feature request related to a problem? Please describe.**

Repository 搜索时识别大小写，比如我无法用 `jq` 搜索 `JQ`文件夹

**Describe the solution you'd like**

Repository 搜索时忽略大小写

**Describe alternatives you've considered**

无

**Additional context**
无

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/commit/e596b48115102184ea1eb30c8516d80cc6898448
