### ISSUE TITLE
惠普网站无法剪藏

### ISSUE THREAD

**Issue by Wrandz** [webclipper/web-clipper#885]
**Bug 描述**

https://support.hp.com/cn-zh/product/omen-by-hp-15-dc0000-laptop-pc-series/20329817/model/22297560/document/c06038427
惠普网站想要剪藏时，失败，webclipper菜单被遮挡，无法全部展开。

**复现步骤**

重现的步骤：

1. 打开 'Microsoft Edge'
2. 点击 'https://support.hp.com/cn-zh/product/omen-by-hp-15-dc0000-laptop-pc-series/20329817/model/22297560/document/c06038427'
3. 点击 'webclipper'剪藏
4. 看到错误

**截图**
![Snipaste_2021-08-06_23-06-03](https://user-images.githubusercontent.com/70056470/128531461-47ac4fb8-c13b-41c8-b882-a23efb4002ff.png)

**请填写以下信息**

- 笔记平台: [wolai]
- 浏览器 [Edge]
- 版本 [92.0.902.62]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by DiamondYuan** [comment]
1.31.0-alpha.8 修复了这个问题
