### ISSUE TITLE
思源笔记，保存到笔记中无法显示

### ISSUE THREAD

**Issue by huoshiyinggong** [webclipper/web-clipper#889]
现在鉴权问题OK了，但是剪藏完网页，保存到笔记中无法显示

![1](https://user-images.githubusercontent.com/54787855/128958391-c1780d34-25f3-4cfe-a6a2-0a8dab9adf22.png)
![2](https://user-images.githubusercontent.com/54787855/128958392-af8424bd-0934-44ef-ba80-35b6d8821ad0.png)
![3](https://user-images.githubusercontent.com/54787855/128958395-a0c9dcd0-4702-45f0-a021-c5a0a17844b9.png)

- 笔记平台: [思源笔记]
- 浏览器 [chrome]
- 版本 [1.2.31]

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by 88250** [comment]
@huoshiyinggong 这个问题估计要等思源笔记 v1.2.5 正式版发布以后 Web Clipper 才好跟进处理。

@DiamondYuan 我这里发现 v1.2.5-alpha3 上配置 Token 时会报错 
![image](https://user-images.githubusercontent.com/873584/129162647-a72f0150-6544-4a29-94f3-01980e7ca7bd.png)

**Comment by huoshiyinggong** [comment]
@88250 我发现标题短是可以显示的，标题过长就不会显示了

**Comment by 88250** [comment]
@huoshiyinggong 思源 v1.2.5 里面改进了存储机制，不再以显示的文字作为文件名，而是用固定长度的 id 作为文件名，应该可以避免现在标题长或者一些特殊字符引起的问题。

**Comment by DiamondYuan** [comment]
试试看 beta 11
