### ISSUE TITLE
无法保存内容

### ISSUE THREAD

**Issue by zlr3538** [webclipper/web-clipper#897]
**Bug 描述**

能够正确提取网页，但是“保存内容“的按钮始终是灰色的，测试了语雀和有道都是这样

浏览器 chrome 92.0.4515.159
插件 1.30.0

**Comment by DiamondYuan** [comment]
请问你是否选择了下方的知识库？
需要先选择知识库才能保存。

**Comment by DiamondYuan** [comment]
> 谢谢，是这个原因。
> 因为没有任何提示，所以没有发现，这里可以做一个提醒可能会好一些。

谢谢提醒、

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/129928437-7e710dd3-7ff0-4490-a881-99a08955390c.png)
