### ISSUE TITLE
绑定账户中没有思源笔记

### ISSUE THREAD

**Issue by abtxu** [webclipper/web-clipper#898]
![2021-08-20_151459](https://user-images.githubusercontent.com/48761002/130199087-3fd1a953-0402-401f-955a-1f56ff09d44d.png)

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper/releases/tag/v1.31.0-alpha.10

**Comment by DiamondYuan** [comment]
试试看 beta

**Comment by DiamondYuan** [comment]
https://www.yuque.com/web-clipper/help_cn/install_offline 这个是教程

**Comment by abtxu** [comment]
感谢答复，安装后输入api token， 得到http error
