### ISSUE TITLE
SM.MS 图床添加 API Token 登录功能

### ISSUE THREAD

**Issue by breathiness** [webclipper/web-clipper#899]
目前 SM.MS 图床只有免费方式上传。没办法统一管理图片。

我是SM.MS图床的专业版用户，想将收集的图片上传到自己账号上。
这样可以让我看到所有上传的图片。比较方便跨设备管理。
![图片](https://user-images.githubusercontent.com/11361630/130344293-115940a6-081b-4b8e-8f1a-ba1db6c1ffd0.png)

**Comment by DiamondYuan** [comment]
试试看 1.31.0-alpha.12

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/130494366-eee1e7c7-fe6b-4cfd-baa5-16332d0f6856.png)
