### ISSUE TITLE
思源笔记无法绑定账户

### ISSUE THREAD

**Issue by H-Tung** [webclipper/web-clipper#904]
**Bug 描述**

绑定账户时提示“http error”，无论是否填入API token

- 笔记平台: 思源笔记 v1.2.7-v1.3.0
- 浏览器：Vivaldi | 4.1.2369.21 (Stable channel) （64 位）
- web-clipper版本：v1.31.0-alpha.10
- 操作系统	Windows 10 OS Version 2009 (Build 19043.1165)

![image](https://user-images.githubusercontent.com/67063101/131206431-d7fcd5e4-8518-418b-9cef-13293c3d7013.png)

![image](https://user-images.githubusercontent.com/67063101/131206473-2c6957d5-7162-4f41-afa1-0ec6433b419f.png)

**Comment by abtxu** [comment]
同样的问题

**Comment by ingmeing** [comment]
我也同样问题，隔两天就过来看看有没有新版本发布。没有web-clipper的日子，太太太难受了。

**Comment by Achuan-2** [comment]
同样的问题

**Comment by Achuan-2** [comment]
@DiamondYuan

**Comment by 88250** [comment]
FYI 思源笔记 API 文档 https://github.com/siyuan-note/siyuan/blob/master/API.md

**Comment by H-Tung** [comment]
问题其实就是API的事, 有新的issue说的更清楚: https://github.com/webclipper/web-clipper/issues/926
希望大佬有空尽快修复吧...
