### ISSUE TITLE
为什么下载解压，加载扩展程序的时候说目录清单缺失呀？

### ISSUE THREAD

**Issue by yanxiaowei1997** [webclipper/web-clipper#905]
![image](https://user-images.githubusercontent.com/48235202/131219617-1b3d8e27-a0d5-4184-b2f0-62ebdfdf564e.png)

**Comment by DiamondYuan** [comment]
去这里下载。 https://github.com/webclipper/web-clipper/releases

你下载的是源码、不是插件。



对了、安装完插件以后，不能删除这个文件夹。
