### ISSUE TITLE
希望能支持为知笔记

### ISSUE THREAD

**Issue by abe520** [webclipper/web-clipper#906]
或支持第三方编译的客户端https://github.com/altairwei/WizNotePlus

**Comment by DiamondYuan** [comment]
已经支持了，有什么问题可以继续打开。

**Comment by abe520** [comment]
> 已经支持了，有什么问题可以继续打开。

授权填不了带端口的地址，所以私有部署没法用？最好像ntion有个使用说明

**Comment by elfzweik** [comment]
在别的地方写好带端口的地址，拷贝粘贴
