### ISSUE TITLE
notion 用户名显示 undefinedundefined

### ISSUE THREAD

**Issue by i207M** [webclipper/web-clipper#912]
**Bug 描述**

使用notion登录后，“用户名”处显示`undefinedundefined`

**复现步骤**

重现的步骤：

1. 安装web clipper
2. 点击账户->绑定账户->Notion
3. 绑定成功后，“用户名”处显示`undefinedundefined`

**预期行为**

不显示`undefinedundefined`

**截图**

![image.png](https://i.loli.net/2021/09/08/amNiIonWtbG4SHL.png)

**请填写以下信息**

- 笔记平台: notion
- 浏览器 chromium edge
- 版本 1.30.0

**其他背景**

暂无，谢谢！

**Comment by DiamondYuan** [comment]
notion 的字段改了。 在最新的 v1.31.0-alpha.16 修复了这个问题
