### ISSUE TITLE
思源笔记，请求的api接口不是最新的，无法绑定账户

### ISSUE THREAD

**Issue by Tukali** [webclipper/web-clipper#926]
**Bug 描述**

api接口不是最新的，无法绑定账户

**复现步骤**

重现的步骤：
填写了正确的token，无法绑定账户，抓包查看
![image](https://user-images.githubusercontent.com/45891208/135744196-7388178e-01be-40c6-b638-bf91d225087a.png)
使用了/api/notebook/ls 这个接口，没有返回

找官方api文档（https://github.com/siyuan-note/siyuan/blob/master/API.md）
发现最新的接口是/api/notebook/lsNotebooks
![image](https://user-images.githubusercontent.com/45891208/135744143-c0fda07a-1266-4165-a045-6678a15b7970.png)
这个可以正确返回，应该是api接口版本不一样，所以这里返回不了正确的信息，无法绑定，能否更新一下呢

**请填写以下信息**

- 笔记平台: 思源1.39
- 浏览器 chrome
- 版本 最新的bate版本

**Comment by netdog2019** [comment]
这么好用的工具，想试试，但是也存在无法绑定思源账户的问题，希望开发者更新一下啊，非常感谢。~~~

**Comment by DiamondYuan** [comment]
最新的测试版本已经支持了

**Comment by DiamondYuan** [comment]
https://chrome.google.com/webstore/detail/web-clipper-beta/finhmpmkpbacljcdemplngnnjdenihpp?hl=en&authuser=0
