### ISSUE TITLE
能否实现剪裁鼠标选中内容

### ISSUE THREAD

**Issue by wwjCMP** [webclipper/web-clipper#929]
现在都是基于区域选取，有点不灵活，区域中往往会过大或者出现其他不需要的元素

**Comment by DiamondYuan** [comment]
选择文本 右键即可

<img width="762" alt="image" src="https://user-images.githubusercontent.com/9692408/182040879-1b097ea1-50b7-4dc9-9436-bd9a3f771523.png">
