### ISSUE TITLE
Bind an account - not explained

### ISSUE THREAD

**Issue by wweber99** [webclipper/web-clipper#965]
When I try to clip something for the first time, I'm asked to "bind an account". What? How?

<img width="644" alt="2021-12-03 at 13 43 37@2x" src="https://user-images.githubusercontent.com/95479317/144598326-ccf341a1-d1c4-41cd-9da8-095bdb6ef71a.png">

<img width="408" alt="2021-12-03 at 13 54 08@2x" src="https://user-images.githubusercontent.com/95479317/144598397-7fa05676-a04c-42a2-ad1e-9a96f1a80400.png">

**Comment by DiamondYuan** [comment]
Click bind account, then select the note-taking platform you want to save。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/144709388-ea27a0de-487c-4549-a918-5a4d74bb3d37.png)
