### ISSUE TITLE
希望 Firefox 扩展商店版本可以更新新版本

### ISSUE THREAD

**Issue by breathiness** [webclipper/web-clipper#977]
目前火狐扩展商店的版本还停留在 1.29.0 ，上次更新还是2021年1月27日。  
想要使用新版本只能从 GitHub 下载。而且压缩包的形式，普通版本的 Firefox 没办法安装。调试模式安装后再次开启就需要再次安装。  
希望可以更新一下 Firefox 扩展商店版本。

**Comment by renxingblack** [comment]
**万人血书更新新版本~
1.29.0，用不了flowus，太惨了**

**Comment by H-Tung** [comment]
2023-12-20 ，Firefox 商店停留在1.32.0，有空的话烦请更新下，谢谢！

**Comment by DiamondYuan** [comment]
更新了
