### ISSUE TITLE
绑定为知笔记docker版账号校验出现Cannot read properties of undefined (reading 'displayName')

### ISSUE THREAD

**Issue by elfzweik** [webclipper/web-clipper#985]
**Describe the bug**

NAS上安装为知笔记docker版，上个月可以绑定https://ddns:端口号，并剪藏网页，在为知笔记重构版中显示正确，并可同步。最近在mac上安装web clipper，无法正常剪藏，出现Cannot read properties of undefined (reading 'displayName')报错，但是windows下的edge仍可正常剪藏。把webclipper从edge中去除，再安装，1.30版，windows下和mac下均不能绑定账户，出现Cannot read properties of undefined (reading 'displayName')报错。

**Comment by elfzweik** [comment]
找到问题原因了，在做绑定的时候，一定要网页登录为知笔记docker，就可以绑定了。

**Comment by goodenn** [comment]
绑定完成后，过不了多久还是会出现上面的问题。
头痛ing...

**Comment by 6769** [comment]
解决方法：
1. Chrome卸载插件重新安装，
2. 删除本地私有站点域名下的关联cookies，
3. 重新网页版登陆后即可添加 为知笔记docker
