### ISSUE TITLE
上传图片到图床总是报CORS问题

### ISSUE THREAD

**Issue by HappyJustyn** [webclipper/web-clipper#988]
是我的使用方式不对吗？

![image](https://user-images.githubusercontent.com/35069723/147931761-def8847e-7463-45ed-b2fe-eeeece6a74a2.png)

**Comment by DiamondYuan** [comment]
发一下地址？

**Comment by HappyJustyn** [comment]
比如这样：
![image](https://user-images.githubusercontent.com/35069723/148024190-bd187941-302b-4945-b5bc-9ba80a4bdefc.png)
![image](https://user-images.githubusercontent.com/35069723/148024350-ef2f1faf-7406-4a75-8fe2-414f744f38ed.png)
https://gitee.com/coder-baobao/blogpic/raw/master/image-20210723214832957.png

请求头：
GET /coder-baobao/blogpic/raw/master/image-20210723214832957.png HTTP/1.1
Host: gitee.com
Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Microsoft Edge";v="96"
Accept: application/json, text/plain, */*
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
sec-ch-ua-platform: "Windows"
Origin: chrome-extension://mhfbofiokmppgdliakminbgdgcmbhbac
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
If-None-Match: W/"661a07db9c86966cd49f67a5f3330405"

响应头：
HTTP/1.1 200 OK
Date: Tue, 04 Jan 2022 07:29:14 GMT
Server: nginx
X-UA-Compatible: chrome=1
Expires: Sun, 1 Jan 2000 01:00:00 GMT
Pragma: must-revalidate, no-cache, private
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Disposition: inline; filename="image-20210723214832957.png"
Content-Transfer-Encoding: binary
Cache-Control: no-cache
Set-Cookie: oschina_new_user=false; path=/; expires=Sat, 04 Jan 2042 07:29:14 -0000
Set-Cookie: gitee-session-n=K2RuR2NWSmdlLzFjUXNXVHBVOEQzakRydXNqMW9tTURFdXhTY09XeUV5bHZlMXpmMGFIeEQ4eEJYWFEvWG5zVWdISkhSUVBhNkZHV2lRVGQ5WitRWlE9PS0tSWkwOE5CRHgwZGFkZXhxc3JoNGJpZz09--eff4db328d16c510eb3982d1605c26f5b30c5826; domain=.gitee.com; path=/; HttpOnly
X-Request-Id: 1b2e7f8770faa258e0dbbb7dce2eaa22
X-Runtime: 0.036511
Content-Type: image/png
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"661a07db9c86966cd49f67a5f3330405"
X-Frame-Options: SAMEORIGIN

**Comment by appdev** [comment]
同样的问题，之前以为上传到图床都有问题，后来发现是有的网站有问题 不提示 `CORS 错误` 目前测试了 CSDN、segmentfault 这些没问题，小众软件、微信公众号 都不行。

**Comment by idealspark** [comment]
@appdev 我也遇到了和你同样的问题
