### ISSUE TITLE
授权语雀时提示 yfd.im 域名ssl证书已过期

### ISSUE THREAD

**Issue by hongjiang** [webclipper/web-clipper#994]
**Bug 描述**

绑定语雀账户时，提示 *.yfd.im 域名证书已过期

**截图**
<img width="695" alt="截屏2022-01-10 上午10 24 38" src="https://user-images.githubusercontent.com/822582/148712654-0f06c8ed-84f4-4e17-9ea2-67d6fa49752c.png">

**Comment by DiamondYuan** [comment]
谢谢提示。修复了
